// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Tue Oct 14 14:46:05 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 5640
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "5640" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
numJets_40                    numJets_40                    numJets_40                    numJets_40                                                      'F'    [0,5]
MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_D_mass_of_leps_jets MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_mass_of_leps_jets                                           'F'    [0.256867796183,0.974646389484]
jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt                                                 'F'    [25.0019645691,135.314666748]
jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex                                         'F'    [0.679145395756,1]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0163956359029,0.999999165535]
Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq                                           'F'    [-15.0804004669,3.01573562622]
Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq                                           'F'    [-14.7622289658,2.7041785717]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numJets_40", "MT_of_leps_jets_mass_of_leps_jets", "jets_by_pt_5_pt", "jets_by_CSV_1_btagCombinedSecVertex", "jets_by_CSV_2_btagCombinedSecVertex", "Match_ttbar_jj_Bq_bqq", "Match_ttbar_jj_Bqq_bq" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 5;
      fVmin[1] = 0.256867796182632;
      fVmax[1] = 0.974646389484406;
      fVmin[2] = 25.0019645690918;
      fVmax[2] = 135.314666748047;
      fVmin[3] = 0.679145395755768;
      fVmax[3] = 1;
      fVmin[4] = 0.0163956359028816;
      fVmax[4] = 0.999999165534973;
      fVmin[5] = -15.0804004669189;
      fVmax[5] = 3.0157356262207;
      fVmin[6] = -14.7622289657593;
      fVmax[6] = 2.70417857170105;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639354,0.0278708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448113,-0.0103774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201729,-0.0596542) , 
5, -2.12668, 0, 0, 0.29517,-0.20483) , 
3, 0.908386, 0, 0, 0.501434,0.00143369)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67058,0.0328815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489451,-0.00145404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225335,-0.0535768) , 
1, 0.697239, 0, 0, 0.347911,-0.146668) , 
4, 0.442851, 0, 0, 0.499827,-0.000287529)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645586,0.0254441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537267,0.00769169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259526,-0.0426294) , 
6, -1.49628, 0, 0, 0.328693,-0.149624) , 
3, 0.923606, 0, 0, 0.499822,-0.000294485)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637218,0.0255517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532213,0.00057981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238842,-0.0462765) , 
4, 0.629768, 0, 0, 0.32715,-0.159234) , 
1, 0.663364, 0, 0, 0.505032,0.00499578)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612549,0.021229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659459,0.0246925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275926,-0.0424192) , 
5, -0.251644, 0, 0, 0.332016,-0.161033) , 
0, 3.09524, 0, 0, 0.486304,-0.0146832)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60442,0.0169854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354559,-0.0261883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0912548,-0.0667533) , 
3, 0.847339, 0, 0, 0.281971,-0.182526) , 
1, 0.632847, 0, 0, 0.493126,-0.00793225)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674009,0.0279991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677419,0.0320074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297276,-0.0328828) , 
1, 0.834794, 0, 0, 0.353584,-0.113395) , 
4, 0.44286, 0, 0, 0.507959,0.00778977)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627586,0.0213594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57337,0.0145145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259858,-0.0414732) , 
2, 39.0855, 0, 0, 0.344878,-0.127562) , 
6, -2.41415, 0, 0, 0.490916,-0.00750913)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613451,0.0185508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483037,-0.00764507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171561,-0.051662) , 
3, 0.923669, 0, 0, 0.323855,-0.144343) , 
0, 3.09524, 0, 0, 0.485124,-0.01349)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585532,0.0130344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518519,0.0031198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172232,-0.0491266) , 
1, 0.825043, 0, 0, 0.227474,-0.191925) , 
3, 0.847309, 0, 0, 0.501217,0.00342824)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594283,0.0139457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484663,0.00170256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21189,-0.0434734) , 
2, 37.0061, 0, 0, 0.266178,-0.161695) , 
1, 0.604321, 0, 0, 0.498756,0.000950029)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559475,0.0100521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29661,-0.0373826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0761421,-0.0690626) , 
5, -2.1512, 0, 0, 0.196305,-0.243597) , 
0, 2.14286, 0, 0, 0.504702,0.00434954)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609984,0.0143328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335727,-0.0201951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126074,-0.0552257) , 
6, -3.72329, 0, 0, 0.254967,-0.155764) , 
3, 0.877871, 0, 0, 0.496288,-0.00267447)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637037,0.0176782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602076,0.00688264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269899,-0.0304655) , 
4, 0.814881, 0, 0, 0.339363,-0.10483) , 
1, 0.701207, 0, 0, 0.486457,-0.0108544)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707182,0.0303586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617591,0.0182197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324247,-0.0249015) , 
2, 37.2801, 0, 0, 0.404278,-0.0606448) , 
5, -1.29287, 0, 0, 0.501417,0.00543603)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54828,0.00702464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248603,-0.0384093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0208333,-0.0806511) , 
0, 1.04762, 0, 0, 0.200441,-0.217023) , 
0, 2.14286, 0, 0, 0.493198,-0.00641732)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776935,0.038633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518176,0.00214241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203733,-0.0390416) , 
1, 0.59132, 0, 0, 0.424397,-0.0446533) , 
5, -0.757003, 0, 0, 0.506927,0.00836514)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676519,0.0212061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606936,0.013139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307329,-0.024788) , 
1, 0.799141, 0, 0, 0.371517,-0.0754807) , 
3, 0.954193, 0, 0, 0.502647,0.000135718)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657942,0.0228688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587087,0.00687378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28932,-0.0269784) , 
6, -1.59732, 0, 0, 0.40625,-0.0611182) , 
2, 32.8652, 0, 0, 0.505706,0.0053487)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62099,0.0123886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,-0.000345985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193922,-0.0375694) , 
4, 0.430003, 0, 0, 0.268116,-0.116166) , 
3, 0.893137, 0, 0, 0.499465,-0.00190265)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591223,0.0103627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0224164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232143,-0.0308505) , 
6, -0.265257, 0, 0, 0.263694,-0.115519) , 
1, 0.595615, 0, 0, 0.499822,0.00266505)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567957,0.00903657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219585,-0.041034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0686275,-0.0655115) , 
0, 1.04762, 0, 0, 0.18451,-0.201004) , 
0, 2.14286, 0, 0, 0.509243,0.00433796)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70339,0.0228422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.71875,0.0239636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357394,-0.0171818) , 
5, -0.431147, 0, 0, 0.404592,-0.0526605) , 
1, 0.769567, 0, 0, 0.501722,-0.00138279)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723042,0.0246664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594976,0.0121722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302827,-0.0223854) , 
2, 35.5103, 0, 0, 0.396769,-0.04856) , 
5, -1.20419, 0, 0, 0.497205,0.000606547)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622337,0.0138929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432234,-0.00858492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202198,-0.0357494) , 
0, 2.14286, 0, 0, 0.350078,-0.0774079) , 
0, 3.09524, 0, 0, 0.499469,-0.000218358)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598515,0.00949922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479042,0.00103203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202112,-0.030999) , 
2, 37.2801, 0, 0, 0.257831,-0.0993198) , 
1, 0.604321, 0, 0, 0.499298,0.00176741)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725753,0.0219161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675926,0.0237502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369449,-0.014268) , 
2, 44.661, 0, 0, 0.404199,-0.0427617) , 
4, 0.672131, 0, 0, 0.507138,0.00208919)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616835,0.0123101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429134,-0.00951621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101587,-0.0501493) , 
3, 0.816807, 0, 0, 0.351615,-0.0785028) , 
5, -2.29187, 0, 0, 0.491477,-0.00834052)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735526,0.0249682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490083,-0.000259846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294256,-0.0244047) , 
2, 29.0969, 0, 0, 0.409113,-0.0428943) , 
1, 0.791992, 0, 0, 0.496989,-0.0015672)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639724,0.0117173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350526,-0.0108125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157658,-0.0403891) , 
1, 0.471653, 0, 0, 0.313993,-0.0669167) , 
1, 0.667027, 0, 0, 0.501806,0.00193364)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581307,0.00696923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368687,-0.00737869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164969,-0.0339952) , 
4, 0.41361, 0, 0, 0.223512,-0.0999567) , 
3, 0.847212, 0, 0, 0.492821,-0.00138881)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605212,0.0100472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313175,-0.0150617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109375,-0.0456325) , 
5, -3.61643, 0, 0, 0.229885,-0.105433) , 
3, 0.862491, 0, 0, 0.502277,0.00343502)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638705,0.0155207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404393,-0.00518361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25462,-0.032675) , 
2, 27.1097, 0, 0, 0.34655,-0.0648029) , 
0, 3.09524, 0, 0, 0.505946,0.00755826)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548228,0.00394219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.062937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153453,-0.0387255) , 
4, 0.862844, 0, 0, 0.159353,-0.159497) , 
0, 2.14286, 0, 0, 0.489332,-0.00970191)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569144,0.00576141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256684,-0.0365014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15082,-0.0245047) , 
1, 0.722845, 0, 0, 0.191057,-0.112653) , 
3, 0.816771, 0, 0, 0.502851,0.00087552)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752066,0.0228554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752475,0.0300387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362813,-0.0140118) , 
1, 0.860641, 0, 0, 0.400673,-0.0403172) , 
4, 0.765808, 0, 0, 0.491622,-0.00475094)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585629,0.00991894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506045,-0.00372507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.128079,-0.0380146) , 
3, 0.877871, 0, 0, 0.350254,-0.0651557) , 
6, -3.22211, 0, 0, 0.503879,0.00479462)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648,0.0153907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784314,0.0419573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360847,-0.0131777) , 
1, 0.890383, 0, 0, 0.376056,-0.0454377) , 
5, -2.15459, 0, 0, 0.509839,0.00896666)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630279,0.0119162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42629,-0.00658989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191874,-0.0306623) , 
0, 2.14286, 0, 0, 0.343675,-0.0582255) , 
0, 3.09524, 0, 0, 0.501431,0.00179413)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560768,0.00616707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.386139,-0.0126427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.118541,-0.0403168) , 
6, -1.03895, 0, 0, 0.181395,-0.119286) , 
0, 2.14286, 0, 0, 0.501982,0.00354196)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618363,0.00724335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654762,0.014448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24569,-0.0226185) , 
6, -0.230929, 0, 0, 0.279644,-0.0741261) , 
1, 0.632847, 0, 0, 0.496808,-0.00674743)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620968,0.010555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41676,-0.00423829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232911,-0.0328153) , 
4, 0.213259, 0, 0, 0.360465,-0.0519702) , 
5, -2.39829, 0, 0, 0.5,-0.000634685)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692478,0.0149387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561856,0.00496277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300745,-0.0157845) , 
4, 0.421407, 0, 0, 0.41027,-0.0268197) , 
3, 0.969468, 0, 0, 0.502905,0.00272201)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742647,0.0208475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605852,0.00949464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350809,-0.0131311) , 
2, 35.2946, 0, 0, 0.420508,-0.0263911) , 
1, 0.803747, 0, 0, 0.498574,0.00053124)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74442,0.0192695) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478445,-0.00128986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174825,-0.028273) , 
3, 0.831933, 0, 0, 0.391042,-0.0317143) , 
4, 0.672131, 0, 0, 0.500867,0.0023651)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678774,0.015979) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578947,0.000914194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259295,-0.019669) , 
3, 0.938935, 0, 0, 0.402836,-0.0383316) , 
2, 35.5079, 0, 0, 0.490126,-0.00522867)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75814,0.0201268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802083,0.0238706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418658,-0.00776679) , 
6, 0.075064, 0, 0, 0.449747,-0.0212798) , 
1, 0.834794, 0, 0, 0.497141,-0.00588513)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621928,0.00838468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367279,-0.0105416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588235,-0.0564951) , 
0, 1.14286, 0, 0, 0.343077,-0.0514547) , 
0, 3.09524, 0, 0, 0.496363,-0.00431768)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681344,0.013654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542388,0.000680044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265418,-0.0173255) , 
5, -2.34634, 0, 0, 0.416958,-0.0273556) , 
2, 35.5079, 0, 0, 0.496513,-0.00234334)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587383,0.00487711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.0199806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194127,-0.0208925) , 
4, 0.639181, 0, 0, 0.218045,-0.0579079) , 
3, 0.847212, 0, 0, 0.499822,0.00161192)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615508,0.00688857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334951,-0.00692779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19346,-0.0289849) , 
1, 0.512527, 0, 0, 0.282234,-0.0531586) , 
1, 0.634537, 0, 0, 0.500525,1.9485e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676337,0.012049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.0325914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366275,-0.0100533) , 
1, 0.883834, 0, 0, 0.384797,-0.0308464) , 
5, -1.66633, 0, 0, 0.499643,0.000114263)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624514,0.0060105) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775862,0.0277279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30795,-0.0160862) , 
4, 0.95372, 0, 0, 0.329609,-0.0517918) , 
0, 3.09524, 0, 0, 0.492308,-0.00991504)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585891,0.00866007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405488,-0.00570014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236301,-0.0287498) , 
4, 0.210719, 0, 0, 0.353376,-0.0486669) , 
6, -3.35854, 0, 0, 0.507308,0.00613077)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661326,0.00816981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552058,0.00746896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248532,-0.0196588) , 
4, 0.500007, 0, 0, 0.335889,-0.0409095) , 
3, 0.938924, 0, 0, 0.495014,-0.00481953)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.845018,0.0325302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78125,0.0198402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401217,-0.00876399) , 
6, -0.413987, 0, 0, 0.459127,-0.0177901) , 
1, 0.868155, 0, 0, 0.496596,-0.00479295)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607287,0.0104584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4494,0.00215422) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221053,-0.0250986) , 
6, -3.07257, 0, 0, 0.346881,-0.0341539) , 
4, 0.297425, 0, 0, 0.508432,0.012128)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.79703,0.034316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771812,0.0158068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418572,-0.00602835) , 
6, -0.517052, 0, 0, 0.479537,-0.00957221) , 
2, 51.2669, 0, 0, 0.502507,0.000611601)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558369,0.00268713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221557,-0.0188363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0606061,-0.0532621) , 
0, 1.04762, 0, 0, 0.184758,-0.0845995) , 
0, 2.14286, 0, 0, 0.499819,-0.00437168)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561484,0.00513889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.262411,-0.0420185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156716,-0.013068) , 
3, 0.938935, 0, 0, 0.193154,-0.0863377) , 
1, 0.527272, 0, 0, 0.507835,0.00450353)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806452,0.0335325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57681,0.0030444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311609,-0.0148097) , 
6, -2.93298, 0, 0, 0.479672,-0.0124257) , 
2, 51.2689, 0, 0, 0.500872,-0.0036559)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834559,0.0274993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641611,0.00806836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395048,-0.00821972) , 
2, 35.5079, 0, 0, 0.467883,-0.0122313) , 
1, 0.868155, 0, 0, 0.503579,-0.00186756)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638283,0.00967601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507874,0.0110369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308617,-0.0142585) , 
2, 31.3923, 0, 0, 0.349042,-0.0323682) , 
0, 3.09524, 0, 0, 0.505147,0.00542295)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80344,0.0218078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460509,-0.00183957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279412,-0.0306933) , 
6, -7.9986, 0, 0, 0.450147,-0.0133921) , 
1, 0.840272, 0, 0, 0.501796,-0.000347961)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600795,0.00571492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550186,0.00600173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264741,-0.0188255) , 
6, -1.65381, 0, 0, 0.334545,-0.0437486) , 
4, 0.312937, 0, 0, 0.498427,-0.00345898)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72,0.0153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441221,-0.00210956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195652,-0.0313857) , 
5, -6.71499, 0, 0, 0.425107,-0.0144158) , 
2, 36.7501, 0, 0, 0.504517,0.00512147)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640878,0.00636255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309816,-0.00512552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159509,-0.0346382) , 
4, 0.142304, 0, 0, 0.288344,-0.0311732) , 
3, 0.908327, 0, 0, 0.50087,0.00254986)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522332,0.00139244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325301,-0.016717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132075,-0.0531188) , 
6, -7.09742, 0, 0, 0.298701,-0.0803841) , 
4, 0.16429, 0, 0, 0.491616,-0.00658019)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576159,0.00347157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441558,0.00284766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150206,-0.0247791) , 
0, 4.04762, 0, 0, 0.190053,-0.0589015) , 
3, 0.831933, 0, 0, 0.499293,-0.000856136)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560181,0.00393016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235294,-0.0269664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136564,-0.00868137) , 
1, 0.64966, 0, 0, 0.185268,-0.0614372) , 
0, 2.14286, 0, 0, 0.50174,0.00290678)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552697,0.00260515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232493,-0.010274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,-0.0429802) , 
1, 0.419726, 0, 0, 0.203501,-0.053001) , 
1, 0.533954, 0, 0, 0.497035,-0.000175973)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560362,0.00432286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38342,-0.00902838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187773,-0.0302274) , 
4, 0.203745, 0, 0, 0.32797,-0.0519552) , 
6, -3.94969, 0, 0, 0.493205,-0.00361912)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719416,0.0117913) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455137,-0.00297242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143646,-0.0263804) , 
0, 2.14286, 0, 0, 0.395789,-0.0240762) , 
1, 0.772651, 0, 0, 0.499104,-0.00283961)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495675,-0.00173086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384615,-0.043527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213592,-0.0271391) , 
3, 0.941795, 0, 0, 0.270968,-0.124475) , 
6, -8.01561, 0, 0, 0.483298,-0.0128086)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780877,0.0260715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508315,0.00116764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299451,-0.0209993) , 
2, 26.1188, 0, 0, 0.478949,-0.00614568) , 
2, 48.4738, 0, 0, 0.505634,0.00265041)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829181,0.0207863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560811,0.00194391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324818,-0.0108485) , 
6, -2.70437, 0, 0, 0.460404,-0.0119638) , 
1, 0.866819, 0, 0, 0.496675,-0.00440113)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798995,0.029537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526214,0.00425609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311644,-0.0125218) , 
4, 0.203748, 0, 0, 0.47882,0.00241702) , 
2, 51.2669, 0, 0, 0.501231,0.00944224)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653874,0.00552144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691176,0.0197754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320616,-0.0104285) , 
2, 51.2677, 0, 0, 0.338225,-0.0305832) , 
1, 0.701351, 0, 0, 0.493243,-0.00553607)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641657,0.00616625) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292683,-0.00768868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0967742,-0.0502235) , 
4, 0.107735, 0, 0, 0.281915,-0.0330837) , 
3, 0.908386, 0, 0, 0.496421,0.000689431)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541916,0.00160272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221311,-0.0346677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168712,-0.00844677) , 
4, 0.545318, 0, 0, 0.183036,-0.0535143) , 
0, 2.14286, 0, 0, 0.484207,-0.00362494)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552373,0.00286767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258621,0.0116768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174785,-0.0241042) , 
6, -7.03612, 1, 0, 0.186732,-0.0561757) , 
1, 0.527865, 0, 0, 0.500175,0.00102385)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537671,0.00379928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.165468,-0.00696775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149425,-0.0436918) , 
6, -3.02223, 1, 0, 0.159292,-0.065258) , 
1, 0.469658, 0, 0, 0.507708,0.00760297)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840336,0.0211194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574294,0.00370047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354912,-0.00617795) , 
2, 30.2549, 0, 0, 0.465965,-0.00355617) , 
1, 0.873865, 0, 0, 0.496721,0.00205768)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519515,0.0020181) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378947,-0.036138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274725,-0.0151043) , 
1, 0.626797, 0, 0, 0.327957,-0.0998182) , 
5, -7.41028, 0, 0, 0.506903,0.000140931)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56213,0.00264053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244444,-0.049387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169951,-0.0170519) , 
5, -0.163152, 0, 0, 0.177384,-0.0662691) , 
0, 2.14286, 0, 0, 0.500533,-0.00254229)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701844,0.00981661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567775,0.00277376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27518,-0.0143206) , 
4, 0.42975, 0, 0, 0.395987,-0.0236042) , 
3, 0.969482, 0, 0, 0.5,-0.00330335)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628846,0.00564758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,-0.004371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0344828,-0.0485676) , 
1, 0.467381, 0, 0, 0.339211,-0.0239754) , 
0, 3.09524, 0, 0, 0.503453,0.00123305)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820823,0.0211166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51891,-0.00054497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183178,-0.0148548) , 
3, 0.831933, 0, 0, 0.44192,-0.0110279) , 
6, -0.334709, 0, 0, 0.498908,0.000598495)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537037,0.00169456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461929,-0.0240739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.00753195) , 
3, 0.954202, 0, 0, 0.320405,-0.047814) , 
5, -4.73975, 0, 0, 0.491272,-0.0053529)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59873,0.0055283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579268,0.00754139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288991,-0.00971926) , 
2, 40.6658, 0, 0, 0.334942,-0.0221663) , 
4, 0.305817, 0, 0, 0.5,0.0042274)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625162,0.00418791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38481,-0.00268361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255061,-0.0175726) , 
2, 27.0545, 0, 0, 0.334891,-0.0274509) , 
0, 3.09524, 0, 0, 0.493277,-0.00420721)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865306,0.0267888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525022,0.00158587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158333,-0.0161099) , 
3, 0.78633, 0, 0, 0.474211,-0.000710814) , 
1, 0.873649, 0, 0, 0.507914,0.00603735)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551724,0.00248474) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149425,0.0147244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138996,-0.0309881) , 
5, -5.32674, 1, 0, 0.141618,-0.0572805) , 
3, 0.770818, 0, 0, 0.502266,0.000931847)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748031,0.0191177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585303,0.00308831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307841,-0.00879336) , 
5, -2.66052, 0, 0, 0.474981,-0.00496507) , 
2, 48.473, 0, 0, 0.499299,0.00133664)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66722,0.00420882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753731,0.010034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332221,-0.00755738) , 
1, 0.866613, 0, 0, 0.36681,-0.0207618) , 
3, 0.954223, 0, 0, 0.494362,-0.00542867)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510251,0.00102274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52381,-0.0056271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17,-0.0364826) , 
2, 40.7822, 0, 0, 0.331522,-0.0729911) , 
5, -7.32491, 0, 0, 0.498375,-0.00153556)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63413,0.00607888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382287,-0.000808384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247911,-0.0163605) , 
2, 26.4078, 0, 0, 0.343725,-0.0168738) , 
0, 3.09524, 0, 0, 0.500368,0.00398873)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529634,0.00212137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0679612,-0.0426964) , 
0, 1.19048, 0, 0, 0.512355,0.00318682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195652,-0.0446569) , 
6, -9.93909, 0, 0, 0.507148,0.000434021)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597984,0.00535113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485714,-0.0132895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256569,0.000714519) , 
1, 0.694598, 0, 0, 0.362883,-0.0226498) , 
2, 29.7013, 0, 0, 0.496421,0.000918866)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671126,-0.00978597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511412,0.0090962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28799,-0.00613679) , 
2, 28.9356, 0, 0, 0.42021,0.0117734) , 
4, 0.676045, 0, 0, 0.497928,-0.00235449)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529389,0.00161728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230769,-0.031963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0814815,-0.0186287) , 
3, 0.923669, 0, 0, 0.141593,-0.069878) , 
1, 0.465367, 0, 0, 0.498032,-0.000399391)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732746,0.00678789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47044,-0.000819799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258383,-0.0120847) , 
4, 0.213259, 0, 0, 0.41917,-0.0115813) , 
1, 0.798183, 0, 0, 0.49604,-0.0034329)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520741,0.00253448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0862069,-0.0192761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0465116,-0.0658625) , 
4, 0.373062, 1, 0, 0.0693069,-0.105656) , 
1, 0.426241, 0, 0, 0.504463,0.0046142)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59655,0.00387029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393423,-0.0020868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181185,-0.0287529) , 
5, -5.00047, 0, 0, 0.338448,-0.0290733) , 
4, 0.303575, 0, 0, 0.498107,-0.00268009)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602618,0.00609415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508772,-0.012128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255474,-0.000447506) , 
2, 35.5183, 0, 0, 0.356705,-0.0197125) , 
6, -2.96648, 0, 0, 0.503189,0.00476354)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569911,0.00338835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295775,-0.029662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179144,-0.0063082) , 
6, -0.571755, 0, 0, 0.197753,-0.0345431) , 
0, 2.14286, 0, 0, 0.510722,0.00453514)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598002,0.00339415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375335,-0.00474326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0322581,-0.045631) , 
3, 0.72521, 0, 0, 0.34901,-0.021914) , 
5, -2.54518, 0, 0, 0.49076,-0.00276527)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661922,0.00522065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610526,-0.0256082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333078,-0.00289518) , 
6, 0.075064, 0, 0, 0.351931,-0.0151401) , 
1, 0.701207, 0, 0, 0.507314,0.0016263)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587989,0.00429304) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.249527,-0.00458729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0803571,-0.0371273) , 
6, -6.3968, 0, 0, 0.219969,-0.0258526) , 
3, 0.847212, 0, 0, 0.503406,0.00599431)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786026,0.0237301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513683,0.00258723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258427,-0.0212989) , 
4, 0.16429, 0, 0, 0.47853,-0.00174285) , 
2, 48.4738, 0, 0, 0.503554,0.00476731)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.781186,0.0116858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742081,0.0147876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396803,-0.00541853) , 
2, 48.4738, 0, 0, 0.429302,-0.0121571) , 
6, -0.476307, 0, 0, 0.489954,-0.003976)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703354,0.0064484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434618,-0.00905785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180952,0.00513417) , 
1, 0.527272, 0, 0, 0.392518,-0.0248039) , 
3, 0.969468, 0, 0, 0.496494,-0.00900709)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527206,0.00397351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0952381,-0.0494944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0447761,-0.0344222) , 
1, 0.664722, 0, 0, 0.0642202,-0.100426) , 
0, 1.19048, 0, 0, 0.509367,0.00926447)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.873362,0.0250455) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589852,0.00189703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31845,-0.00898532) , 
0, 3.09524, 0, 0, 0.466232,-0.00958944) , 
1, 0.872107, 0, 0, 0.499118,-0.00341728)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708833,0.00777363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.700535,0.0122501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369762,-0.00522655) , 
4, 0.906319, 0, 0, 0.401434,-0.0114636) , 
5, -1.29287, 0, 0, 0.499652,0.000437296)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557486,0.0023422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0348658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163043,-0.0101216) , 
4, 0.862946, 0, 0, 0.174334,-0.0388659) , 
0, 2.14286, 0, 0, 0.50159,0.00131076)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544617,0.000354156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518987,-0.0310876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315956,-0.00673553) , 
4, 0.906292, 0, 0, 0.338483,-0.0326686) , 
5, -4.19925, 0, 0, 0.491709,-0.00749877)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679167,0.00276229) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776596,0.0136046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338643,-0.00964874) , 
5, -0.21256, 0, 0, 0.382369,-0.0243125) , 
3, 0.969482, 0, 0, 0.482589,-0.0128497)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654434,0.00478492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375854,-0.00721833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19186,0.0245364) , 
1, 0.493991, 0, 0, 0.3546,-0.0164926) , 
4, 0.44286, 0, 0, 0.494816,-0.00113637)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53892,0.00413444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218391,-0.0299347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0833333,-0.00987625) , 
3, 0.923669, 0, 0, 0.136986,-0.0545998) , 
1, 0.469658, 0, 0, 0.506759,0.00845865)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708197,0.00409737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482353,-0.0225439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392179,-0.00407478) , 
6, -0.851818, 0, 0, 0.396267,-0.0170078) , 
5, -1.29287, 0, 0, 0.498566,-0.00701309)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55218,0.00548635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357447,-0.00315071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207317,-0.0393939) , 
5, -5.5163, 1, 0, 0.335145,-0.0277105) , 
5, -5.03626, 0, 0, 0.509741,0.00936461)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516425,0.00213147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44898,-0.0392393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284768,-0.0101302) , 
4, 0.813643, 0, 0, 0.325,-0.0635867) , 
5, -7.32491, 0, 0, 0.502839,0.00208401)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760726,0.0115567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648111,-0.0110716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357965,-0.000523221) , 
4, 0.812629, 0, 0, 0.42572,-0.0105801) , 
1, 0.806678, 0, 0, 0.499275,-0.000500491)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664675,0.00408329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398601,-0.0169053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27662,-0.00122025) , 
3, 0.876985, 0, 0, 0.317092,-0.022356) , 
3, 0.923606, 0, 0, 0.504109,-0.00259777)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570316,0.00226583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213942,-0.0125779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,0.0255052) , 
0, 2.14286, 0, 0, 0.194231,-0.0224813) , 
3, 0.816854, 0, 0, 0.501236,0.00236622)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733696,0.0109202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485112,-0.00069927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303797,-0.0186233) , 
2, 25.8952, 0, 0, 0.462185,-0.00920685) , 
2, 43.7788, 0, 0, 0.497035,-0.00344143)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788337,0.00905631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448797,-0.00216547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278351,-0.0193581) , 
6, -7.34358, 0, 0, 0.434501,-0.0120039) , 
1, 0.832257, 0, 0, 0.493516,-0.00561818)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560255,0.00527584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481132,0.00455958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18956,-0.0237891) , 
6, -2.84811, 0, 0, 0.325513,-0.0292621) , 
4, 0.210719, 0, 0, 0.504686,0.00646784)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522566,0.0022057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12963,-0.0464531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0632911,-0.0236344) , 
3, 0.923669, 0, 0, 0.0902256,-0.0891735) , 
1, 0.433635, 0, 0, 0.502132,0.00282782)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.73494,-0.0137687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490355,0.00141326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439394,0.0238339) , 
6, -9.15345, 0, 0, 0.48909,0.00665816) , 
4, 0.95316, 0, 0, 0.503541,0.00375669)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756972,0.00981301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695724,0.00354882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400517,-0.00425945) , 
1, 0.796203, 0, 0, 0.471097,-0.00825825) , 
2, 48.4738, 0, 0, 0.496779,-0.00471334)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68379,-0.00770786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423845,0.00482225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,-0.0315644) , 
4, 0.0898158, 0, 0, 0.417387,0.012588) , 
4, 0.676048, 0, 0, 0.499472,0.000932669)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524689,0.0016307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.13,-0.00913317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0930233,-0.0487163) , 
4, 0.337502, 1, 0, 0.118881,-0.0533458) , 
3, 0.724982, 0, 0, 0.503934,0.0024874)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514804,0.00107371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.047619,-0.0158786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0434783,-0.0521074) , 
6, -2.6376, 1, 0, 0.0454545,-0.0769472) , 
0, 1.19048, 0, 0, 0.5,0.00103518)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772222,0.0102756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485485,-0.00103996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316574,-0.0125412) , 
4, 0.185872, 0, 0, 0.449704,-0.0113785) , 
4, 0.906303, 0, 0, 0.48981,-0.00592435)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641771,0.00502501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356792,-0.00385459) , 
0, 3.09524, 0, 0, 0.514442,0.00386061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,-0.0298413) , 
6, -9.44722, 0, 0, 0.508747,0.00131072)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599546,0.00401529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507375,-0.0117884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250338,-0.00113401) , 
1, 0.764988, 0, 0, 0.331169,-0.0161616) , 
4, 0.303576, 0, 0, 0.497712,0.00222026)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515988,-0.00112866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,-0.0457155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0952381,0.00214167) , 
3, 0.923669, 0, 0, 0.104348,-0.068927) , 
1, 0.42541, 0, 0, 0.499477,-0.00637717)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616732,0.000477704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504831,-0.0173135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240826,-0.000915233) , 
5, -1.22933, 0, 0, 0.325816,-0.0232323) , 
0, 3.09524, 0, 0, 0.484441,-0.00968346)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546917,0.00565867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158333,0.00855086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.097561,-0.0478412) , 
3, 0.71402, 1, 0, 0.133663,-0.0406008) , 
3, 0.740261, 0, 0, 0.517241,0.0147564)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0522865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504293,0.000973639) , 
6, -8.82674, 1, 0, 0.505874,0.00599157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244898,-0.0289493) , 
5, -9.64403, 0, 0, 0.501262,0.00419289)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670157,0.00405789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571429,-0.0071542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31426,0.000842095) , 
4, 0.537812, 0, 0, 0.415427,-0.00841689) , 
2, 34.3904, 0, 0, 0.503249,-0.000863427)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.014185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454507,-0.00195632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0383513) , 
5, -8.50974, 0, 0, 0.447358,-0.00885775) , 
2, 42.6686, 0, 0, 0.492147,-0.000982303)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864979,0.019212) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616641,-0.00401614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336283,0.00427508) , 
3, 0.938936, 0, 0, 0.472748,-0.000174084) , 
1, 0.872107, 0, 0, 0.505036,0.00379359)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680816,0.00601396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.857143,0.0436346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361165,-0.00415536) , 
4, 0.905522, 0, 0, 0.374291,-0.00925046) , 
3, 0.954193, 0, 0, 0.507824,0.00367732)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715076,-0.00391865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594444,0.00795441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361131,0.00111874) , 
1, 0.694579, 0, 0, 0.441162,0.0123975) , 
1, 0.797676, 0, 0, 0.511339,0.00623355)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717978,0.00558804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627907,-0.0133528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331165,-0.00175674) , 
4, 0.814269, 0, 0, 0.390852,-0.0140862) , 
1, 0.773568, 0, 0, 0.494314,-0.00412642)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55663,0.00282551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528053,0.00509507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185393,-0.0178792) , 
3, 0.908445, 0, 0, 0.342944,-0.01719) , 
4, 0.214485, 0, 0, 0.506888,0.00314479)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783088,0.0113684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451477,-0.00441329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348285,0.00998408) , 
6, -5.9198, 0, 0, 0.434286,-0.0070973) , 
4, 0.86116, 0, 0, 0.501596,0.00108003)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5622,0.000497928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269608,-0.0186373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114754,-0.00347311) , 
1, 0.722509, 0, 0, 0.176817,-0.0296923) , 
3, 0.816655, 0, 0, 0.492143,-0.00400068)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621231,0.0044107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490079,-0.0151036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252401,0.00266972) , 
3, 0.938936, 0, 0, 0.349554,-0.0190828) , 
6, -2.52425, 0, 0, 0.502655,-7.25119e-05)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638601,0.00474871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483636,-0.0177762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286004,-0.00244415) , 
1, 0.78903, 0, 0, 0.329104,-0.0200533) , 
0, 3.09524, 0, 0, 0.499465,-0.000268429)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597932,0.00168715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40201,-0.0001582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300493,-0.0144552) , 
2, 27.0087, 0, 0, 0.350746,-0.0224413) , 
2, 29.6962, 0, 0, 0.493333,-0.00628724)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709581,-0.00798007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460784,0.00207138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133333,-0.0213802) , 
1, 0.44714, 0, 0, 0.436281,0.00276773) , 
1, 0.806317, 0, 0, 0.499826,-0.00333555)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516247,0.000377885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0625,-0.0448744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0,-0.0536078) , 
3, 0.90964, 0, 0, 0.032967,-0.0828858) , 
0, 1.19048, 0, 0, 0.500707,-0.00146133)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599371,-0.00582872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642045,-0.0124711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321924,0.00595947) , 
5, -0.251644, 0, 0, 0.366746,0.00966181) , 
0, 3.09524, 0, 0, 0.496663,-0.00648342)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649099,0.00461056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462222,-0.0112865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275782,0.00176723) , 
2, 33.1878, 0, 0, 0.33968,-0.0114081) , 
1, 0.682784, 0, 0, 0.504623,0.00288169)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605538,-0.000172482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514286,-0.0169602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368049,0.00950388) , 
6, -0.841389, 0, 0, 0.380452,0.0219653) , 
4, 0.354411, 0, 0, 0.508208,0.00917344)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562728,-0.0008285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648515,0.0211451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330028,0.00470854) , 
3, 0.984734, 0, 0, 0.400881,0.0290574) , 
5, -3.43125, 0, 0, 0.510781,0.00749053)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591671,0.00151798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581731,-0.0203062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307865,-0.000683243) , 
6, -0.638132, 0, 0, 0.359745,-0.0149793) , 
2, 29.0944, 0, 0, 0.501592,-0.00275015)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594023,0.0037434) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296296,-0.0339276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180258,0.00443402) , 
1, 0.800608, 0, 0, 0.202091,-0.0160105) , 
3, 0.83204, 0, 0, 0.512186,0.00683402)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784367,0.00923528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456755,-0.00204005) , 
4, 0.907778, 0, 0, 0.500179,-0.00209478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258065,-0.0273041) , 
5, -9.57677, 0, 0, 0.494932,-0.00409536)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603984,0.00284023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467347,-0.00996567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252459,5.94074e-06) , 
2, 33.1966, 0, 0, 0.348182,-0.0164146) , 
5, -2.89215, 0, 0, 0.503741,-0.000800478)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890244,0.0263048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490061,-0.00139538) , 
5, 1.02812, 0, 0, 0.502224,-0.00244431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447761,0.0213059) , 
6, -9.30238, 0, 0, 0.500904,-0.000548192)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508071,-0.00359872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581395,0.0212885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111888,-0.0222497) , 
3, 0.878275, 0, 0, 0.393855,0.0308037) , 
5, -6.13751, 0, 0, 0.493653,-0.00632176)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74259,0.0034718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423585,-0.00260404) , 
1, 0.806317, 0, 0, 0.497646,-0.00435196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211538,-0.0281887) , 
5, -9.64403, 0, 0, 0.492357,-0.00599565)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664937,0.00440432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752,0.0157678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309668,-0.0045667) , 
5, -0.165842, 0, 0, 0.347826,-0.00850508) , 
1, 0.705897, 0, 0, 0.500715,0.00257558)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797849,0.0100846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540182,-0.00672142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273319,0.00501856) , 
3, 0.893117, 0, 0, 0.435614,-0.0094907) , 
5, -0.431147, 0, 0, 0.495387,-0.00313338)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689139,-0.00809621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610442,0.00777332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346542,-0.00390275) , 
0, 3.04762, 0, 0, 0.461673,0.00460402) , 
0, 4.04762, 0, 0, 0.504792,-0.00104457)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657353,0.00434382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462039,-0.0111075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285294,0.00125858) , 
6, -1.57352, 0, 0, 0.340311,-0.0101683) , 
1, 0.705319, 0, 0, 0.49208,0.00151052)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667526,-0.00454772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457618,0.00375018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393103,0.0259936) , 
5, -7.46025, 0, 0, 0.453095,0.0167096) , 
3, 0.984721, 0, 0, 0.511603,0.00804307)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601347,-0.000126848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37344,0.00767505) , 
4, 0.336951, 0, 0, 0.50853,0.00963949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.025532) , 
4, 0.0714344, 0, 0, 0.504466,0.00825724)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843206,0.0161959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484807,-0.00137257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371681,0.00804593) , 
6, -6.44489, 0, 0, 0.469534,-0.000491195) , 
1, 0.86362, 0, 0, 0.507863,0.00376802)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562712,0.00102128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284024,-0.023342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139785,0.00189689) , 
3, 0.939054, 0, 0, 0.194196,-0.0312129) , 
1, 0.534157, 0, 0, 0.503917,-0.00209001)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695652,-0.0151729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511739,0.000459274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413249,0.0156139) , 
6, -6.15421, 0, 0, 0.499809,0.00743701) , 
2, 56.5206, 0, 0, 0.508053,0.00528523)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515901,-0.00074505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350649,-0.0198417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283784,0.0164612) , 
1, 0.529823, 0, 0, 0.334426,-0.0411451) , 
6, -6.68061, 0, 0, 0.496494,-0.00656898)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,-0.0055089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546875,0.0174651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361856,0.000628641) , 
4, 0.400833, 0, 0, 0.384468,0.00916043) , 
4, 0.489289, 0, 0, 0.489415,-0.00270612)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54717,0.00226931) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328273,-0.00650432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229508,-0.0452293) , 
4, 0.194717, 1, 0, 0.318027,-0.0341446) , 
4, 0.203749, 0, 0, 0.499289,-0.00128471)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656863,0.00318424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538462,-0.0445344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290879,-0.00577551) , 
1, 0.892328, 0, 0, 0.301024,-0.0228575) , 
3, 0.923606, 0, 0, 0.495534,-0.00442752)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515613,0.00192945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389706,-0.00428565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0361046) , 
6, -8.19683, 1, 0, 0.362162,-0.043181) , 
6, -7.48877, 0, 0, 0.505278,0.00296498)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7429,0.00403902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540362,-0.00725188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253968,0.00107074) , 
3, 0.908427, 0, 0, 0.419847,-0.014563) , 
1, 0.801795, 0, 0, 0.498011,-0.00818543)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626059,0.00227011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346328,-0.00898119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165217,0.0480112) , 
3, 0.740476, 0, 0, 0.329228,-0.020394) , 
0, 3.09524, 0, 0, 0.494733,-0.00482469)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578188,0.00272574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55303,-0.0139102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289172,-0.0024687) , 
4, 0.672129, 0, 0, 0.355577,-0.018792) , 
6, -3.11796, 0, 0, 0.494249,-0.00150852)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600449,0.003226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477876,-0.0183389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250362,-0.00260511) , 
1, 0.755769, 0, 0, 0.325243,-0.0274679) , 
4, 0.297424, 0, 0, 0.499644,-0.00334366)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592541,-0.00147245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429842,0.00985694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292614,-0.0108778) , 
2, 26.0012, 0, 0, 0.394428,0.0156668) , 
2, 30.256, 0, 0, 0.496444,0.00509225)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729017,-0.0160089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539244,-0.00456155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334572,0.00697516) , 
4, 0.344263, 0, 0, 0.449429,0.000696774) , 
1, 0.839983, 0, 0, 0.490066,-0.00576192)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741403,0.00762878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478323,-0.00540786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297177,0.00707408) , 
4, 0.257147, 0, 0, 0.419712,-0.00602618) , 
1, 0.798863, 0, 0, 0.503028,0.00137496)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511202,0.000814904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0634921,-0.0403518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0408163,-0.00513689) , 
3, 0.879519, 0, 0, 0.0535714,-0.0582104) , 
0, 1.19048, 0, 0, 0.492832,0.00025396)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514563,0.00129351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432099,-0.0305958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212598,-0.00721641) , 
3, 0.939568, 0, 0, 0.298077,-0.0586563) , 
6, -7.43129, 0, 0, 0.49896,-0.000324481)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513879,0.00100238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.121951,0.0011784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.04,-0.0479231) , 
1, 0.381005, 1, 0, 0.0769231,-0.0560348) , 
1, 0.419097, 0, 0, 0.499823,0.0014033)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764463,0.0127187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759109,0.00584692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409373,-0.00462377) , 
6, -0.54307, 0, 0, 0.476209,-0.00921716) , 
2, 48.4763, 0, 0, 0.500884,-0.00511448)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617009,0.00228715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474227,-0.00695005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289267,0.0156478) , 
6, -1.18152, 0, 0, 0.326722,0.0305392) , 
1, 0.632847, 0, 0, 0.516141,0.0156456)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847826,0.0260504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492754,0.00138047) , 
2, 53.1679, 0, 0, 0.510507,0.00804152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232143,-0.0211511) , 
6, -9.77183, 0, 0, 0.504972,0.00652613)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.841629,0.0140855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484009,-0.000728952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320675,-0.0106516) , 
5, -6.92895, 0, 0, 0.469016,-0.00534815) , 
6, 0.208977, 0, 0, 0.498395,-0.00204214)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511174,-0.00360343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450161,0.0180972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0638298,-0.0323029) , 
3, 0.755853, 0, 0, 0.399441,0.0453457) , 
4, 0.15691, 0, 0, 0.496985,-0.00455492)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.836066,0.0290387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546866,-0.00400394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384925,0.00434605) , 
2, 28.5499, 0, 0, 0.48793,-0.00358562) , 
2, 62.5562, 0, 0, 0.495528,-0.00165654)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675523,0.00559256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527704,-0.0152802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335479,0.00156308) , 
3, 0.984734, 0, 0, 0.380395,-0.01008) , 
5, -1.79767, 0, 0, 0.50838,0.00211146)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.87931,0.0365227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503097,0.00226073) , 
2, 60.3829, 0, 0, 0.510881,0.00933784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269231,-0.0246152) , 
6, -9.37544, 0, 0, 0.50648,0.00761836)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588003,-0.00418478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684524,0.0189705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326679,0.00383646) , 
4, 0.859484, 0, 0, 0.374016,0.0197572) , 
6, -2.50996, 0, 0, 0.490492,0.00150361)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
