// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Mon Nov 17 18:24:19 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 5272
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "5272" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
numJets_40                    numJets_40                    numJets_40                    numJets_40                                                      'F'    [0,11]
MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_D_mass_of_leps_jets MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_mass_of_leps_jets                                           'F'    [0.308375239372,0.968413054943]
jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt                                                 'F'    [25.011598587,182.589538574]
jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex                                         'F'    [0.679110705853,1]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0389463827014,0.999999940395]
Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq                                           'F'    [-12.109536171,2.87168049812]
Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq                                           'F'    [-11.6571483612,3.19305086136]
Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq                                          'F'    [-20.3663883209,3.28406143188]
log_chiSquared_               log_chiSquared_               log_chiSquared_               log_chiSquared_                                                 'F'    [-2.29015135765,7.99216556549]
FinalBDT_ttZ_vs_ttbar_OS      FinalBDT_ttZ_vs_ttbar_OS      FinalBDT_ttZ_vs_ttbar_OS      FinalBDT_ttZ_vs_ttbar_OS                                        'F'    [-0.995288193226,0.998393058777]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numJets_40", "MT_of_leps_jets_mass_of_leps_jets", "jets_by_pt_5_pt", "jets_by_CSV_1_btagCombinedSecVertex", "jets_by_CSV_2_btagCombinedSecVertex", "Match_ttbar_jj_Bq_bqq", "Match_ttbar_jj_Bqq_bq", "Match_ttbar_jj_Bqq_bqq", "log_chiSquared_", "FinalBDT_ttZ_vs_ttbar_OS" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 11;
      fVmin[1] = 0.308375239372253;
      fVmax[1] = 0.968413054943085;
      fVmin[2] = 25.0115985870361;
      fVmax[2] = 182.589538574219;
      fVmin[3] = 0.679110705852509;
      fVmax[3] = 1;
      fVmin[4] = 0.0389463827013969;
      fVmax[4] = 0.999999940395355;
      fVmin[5] = -12.1095361709595;
      fVmax[5] = 2.87168049812317;
      fVmin[6] = -11.6571483612061;
      fVmax[6] = 3.19305086135864;
      fVmin[7] = -20.3663883209229;
      fVmax[7] = 3.28406143188477;
      fVmin[8] = -2.29015135765076;
      fVmax[8] = 7.99216556549072;
      fVmin[9] = -0.995288193225861;
      fVmax[9] = 0.998393058776855;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68808,0.037616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394,-0.0212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174894,-0.0650212) , 
9, -0.4077, 0, 0, 0.265509,-0.234491) , 
9, 0.239065, 0, 0, 0.492337,-0.00766284)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737834,0.0438689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414266,-0.0163163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.170243,-0.0597101) , 
9, -0.453151, 0, 0, 0.294818,-0.187136) , 
9, 0.428355, 0, 0, 0.503701,0.00437423)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739093,0.0399523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.385439,-0.0169411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140481,-0.0650586) , 
6, -1.49368, 0, 0, 0.295593,-0.171421) , 
9, 0.523707, 0, 0, 0.491679,-0.00789308)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740883,0.0366271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400206,-0.0139063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201022,-0.0492137) , 
6, -1.39943, 0, 0, 0.325208,-0.133612) , 
9, 0.618003, 0, 0, 0.491734,-0.00778945)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672704,0.0249575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297636,-0.0268813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133136,-0.056698) , 
9, -0.796331, 0, 0, 0.245033,-0.17659) , 
9, 0.0492327, 0, 0, 0.49904,0.0010316)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745234,0.0325359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451292,0.000800928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23127,-0.0383314) , 
5, -0.445743, 0, 0, 0.308989,-0.117923) , 
9, 0.523657, 0, 0, 0.504267,0.00542379)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681877,0.0229835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314152,-0.0196013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134529,-0.0502825) , 
9, -0.69717, 0, 0, 0.240588,-0.151194) , 
9, 0.0492327, 0, 0, 0.500189,0.00308689)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690411,0.0305924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530541,0.00619808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248205,-0.042319) , 
2, 47.5227, 0, 0, 0.352713,-0.11467) , 
7, -2.347, 0, 0, 0.492622,-0.00652836)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63651,0.0162237) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274648,-0.0219885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127135,-0.0476309) , 
9, -0.645786, 0, 0, 0.178792,-0.174179) , 
9, -0.329558, 0, 0, 0.497947,0.00139193)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6716,0.0265423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569288,0.0117901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277,-0.0348413) , 
2, 55.2556, 0, 0, 0.338595,-0.115106) , 
5, -0.695276, 0, 0, 0.51452,0.0118532)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809896,0.0375624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428904,-0.00370624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250438,-0.0403336) , 
3, 0.908605, 0, 0, 0.374058,-0.0696392) , 
9, 0.80892, 0, 0, 0.501523,0.00148336)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855046,0.0443146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57162,0.0152429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321094,-0.0254898) , 
2, 44.3322, 0, 0, 0.408708,-0.0515788) , 
9, 0.903456, 0, 0, 0.499441,-0.000448769)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64367,0.019215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376794,-0.0120182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226829,-0.0501753) , 
3, 0.877756, 0, 0, 0.327448,-0.111349) , 
6, -0.790769, 0, 0, 0.495098,-0.00552202)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649259,0.0199539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465324,-0.00389151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232425,-0.037147) , 
1, 0.685805, 0, 0, 0.323427,-0.106879) , 
5, -0.83687, 0, 0, 0.503709,0.00295011)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684791,0.0221803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566667,0.0140396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280651,-0.0272988) , 
2, 53.8899, 0, 0, 0.349345,-0.0762673) , 
5, -0.490903, 0, 0, 0.510405,0.00893875)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.84629,0.0378498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454933,-0.00137357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255717,-0.0362981) , 
3, 0.877756, 0, 0, 0.409797,-0.0417633) , 
9, 0.903242, 0, 0, 0.501673,0.00122855)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753642,0.029726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643917,0.0207383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328525,-0.0222132) , 
2, 57.1451, 0, 0, 0.385607,-0.0637362) , 
7, -1.32691, 0, 0, 0.491784,-0.00737094)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714286,0.0166452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483607,0.0156542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244949,-0.0231651) , 
1, 0.811409, 0, 0, 0.267176,-0.0842408) , 
9, 0.333629, 0, 0, 0.493595,-0.00430897)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656138,0.0127173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390625,0.00499302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187141,-0.0299206) , 
1, 0.802151, 0, 0, 0.20107,-0.114208) , 
9, -0.140853, 0, 0, 0.493303,-0.00442063)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634783,0.0169372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452138,-0.00427639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277632,-0.030565) , 
4, 0.679649, 0, 0, 0.346123,-0.0859868) , 
2, 40.075, 0, 0, 0.497529,-0.00250972)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682617,0.022718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564706,0.00589768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26638,-0.0270457) , 
8, 2.43776, 1, 0, 0.392303,-0.0550854) , 
2, 45.4531, 0, 0, 0.505123,0.00423105)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59882,0.0137987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420959,-0.00652807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211031,-0.0417998) , 
4, 0.424391, 0, 0, 0.331633,-0.0890281) , 
1, 0.625567, 0, 0, 0.500935,0.00513251)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612867,0.0116315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411905,-0.0111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16699,-0.0404651) , 
1, 0.654404, 0, 0, 0.277005,-0.109613) , 
6, -1.24018, 0, 0, 0.49686,-0.00510815)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631579,0.0135277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596774,0.0107252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254184,-0.0282772) , 
2, 55.2922, 0, 0, 0.338073,-0.0760832) , 
7, -3.47321, 0, 0, 0.492515,-0.00558874)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518364,0.0035554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288136,-0.0666863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169492,-0.0271391) , 
9, 0.437983, 0, 0, 0.228814,-0.203223) , 
3, 0.786238, 0, 0, 0.492401,-0.00462568)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602345,0.0104723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29623,-0.0178677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.169492,-0.0455087) , 
5, -3.44711, 0, 0, 0.258512,-0.104359) , 
5, -1.40867, 0, 0, 0.500187,0.000283418)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633158,0.0158897) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424354,-0.00512036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263598,-0.0308323) , 
3, 0.923656, 0, 0, 0.364833,-0.0601643) , 
2, 40.019, 0, 0, 0.501143,0.00424157)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624694,0.0113733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316502,-0.0119123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14557,-0.0513603) , 
5, -4.04602, 0, 0, 0.28866,-0.0728535) , 
5, -1.16342, 0, 0, 0.499616,0.00319425)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864376,0.0335414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454602,0.000163561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.240426,-0.0319227) , 
0, 3.42857, 0, 0, 0.40616,-0.029044) , 
9, 0.903456, 0, 0, 0.502471,0.00374863)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535211,0.00414806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.370717,-0.0194443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129252,-0.0605835) , 
7, -6.54921, 0, 0, 0.294872,-0.130855) , 
3, 0.862581, 0, 0, 0.491917,-0.00958211)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744792,0.0268339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740741,0.0307476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403538,-0.00928623) , 
1, 0.836431, 0, 0, 0.439506,-0.020226) , 
0, 5.14286, 0, 0, 0.507113,0.00793473)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596539,0.00831881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674419,0.0290075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242079,-0.0255385) , 
1, 0.854066, 0, 0, 0.264423,-0.0858173) , 
6, -1.46992, 0, 0, 0.493473,-0.00275457)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747312,0.0275973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621971,0.0127652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347301,-0.0166933) , 
1, 0.741879, 0, 0, 0.431179,-0.0302443) , 
0, 5.14286, 0, 0, 0.49942,-0.000303242)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642314,0.00767751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241279,-0.0284403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178218,-0.0151823) , 
6, -0.684656, 0, 0, 0.201053,-0.0788493) , 
9, -0.140853, 0, 0, 0.48478,-0.00765918)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562593,0.00853498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402597,0.000941261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239374,-0.0331766) , 
2, 31.0783, 0, 0, 0.281198,-0.0951452) , 
2, 32.5153, 0, 0, 0.498093,0.00455792)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648649,0.0114937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212963,-0.0331522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166163,-0.0210634) , 
8, 1.98088, 1, 0, 0.172727,-0.0830857) , 
9, -0.330728, 0, 0, 0.508779,0.00903215)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693947,0.0148691) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405631,0.000194719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236538,-0.0334669) , 
3, 0.893119, 0, 0, 0.34618,-0.0445037) , 
5, -0.398407, 0, 0, 0.5,0.00146246)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.853211,0.0260928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501311,0.00141224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.155722,-0.0218518) , 
9, -0.633628, 0, 0, 0.41185,-0.0145088) , 
9, 0.903456, 0, 0, 0.504224,0.00747606)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557202,0.007196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38435,-0.0160231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138462,-0.0632102) , 
4, 0.144298, 0, 0, 0.367238,-0.0760598) , 
3, 0.923598, 0, 0, 0.489508,-0.00914794)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723951,0.0180902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516563,0.0031644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27933,-0.0200295) , 
1, 0.648777, 0, 0, 0.402472,-0.0289255) , 
6, 0.159597, 0, 0, 0.493846,-0.00086461)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.028668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.844512,0.0250757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373025,-0.00887259) , 
9, 0.903125, 0, 0, 0.446667,-0.0162005) , 
2, 55.0264, 0, 0, 0.507241,0.00857065)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623967,0.0106059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450899,-0.00356289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188372,-0.0298692) , 
2, 35.4029, 0, 0, 0.352992,-0.0468811) , 
1, 0.654109, 0, 0, 0.504031,0.00259866)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558794,0.00377438) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357798,-0.0383793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175824,-0.00951304) , 
9, 0.332063, 0, 0, 0.243986,-0.0823625) , 
5, -1.83594, 0, 0, 0.487558,-0.0072788)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736501,0.019319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651219,0.0161946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315379,-0.0107193) , 
2, 53.9412, 0, 0, 0.396807,-0.014987) , 
7, -1.79814, 0, 0, 0.517004,0.0163344)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711845,0.0147804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419585,-0.00415778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171642,-0.0481803) , 
3, 0.770969, 0, 0, 0.401319,-0.0275899) , 
8, 2.11656, 1, 0, 0.50241,-0.00064299)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749671,0.0185247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740741,0.0323569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378063,-0.0101236) , 
2, 71.2157, 0, 0, 0.404543,-0.0266665) , 
6, 0.159597, 0, 0, 0.504985,0.000887954)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720189,0.014721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,0.0118596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359386,-0.0103878) , 
1, 0.780008, 0, 0, 0.407887,-0.0222011) , 
8, 2.11656, 1, 0, 0.508772,0.00247034)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565291,0.0058272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105263,-0.0274734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0327869,-0.0640402) , 
1, 0.69993, 1, 0, 0.0924855,-0.107832) , 
9, -0.805414, 0, 0, 0.504635,0.00574937)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72381,0.0191826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693787,0.00925251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326846,-0.0140506) , 
5, 0.143291, 0, 0, 0.441367,-0.0249934) , 
2, 55.0264, 0, 0, 0.49647,-0.00635991)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864151,0.0225546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424412,-0.00365455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195946,-0.0331736) , 
2, 29.6479, 0, 0, 0.391931,-0.0293859) , 
9, 0.903201, 0, 0, 0.487749,-0.00941296)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5432,0.00410537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0584389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15534,-0.0309811) , 
9, 0.801552, 0, 0, 0.191057,-0.126943) , 
5, -3.18097, 0, 0, 0.510694,0.00205504)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527902,0.00403151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0532998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136364,-0.0196185) , 
6, -0.843551, 0, 0, 0.172185,-0.151478) , 
0, 2.09524, 0, 0, 0.507291,0.00516386)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562051,0.00493238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358255,-0.00904498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161137,-0.0410047) , 
3, 0.924153, 0, 0, 0.280075,-0.0735367) , 
2, 32.5153, 0, 0, 0.504773,-0.000406965)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534453,0.00279352) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317204,-0.0406223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133929,-0.00910674) , 
9, 0.244744, 0, 0, 0.248322,-0.116649) , 
3, 0.816635, 0, 0, 0.501908,-0.00419657)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722397,0.0179893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485154,-0.00115831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174342,-0.0303116) , 
5, -2.50845, 0, 0, 0.437626,-0.0187585) , 
1, 0.779831, 0, 0, 0.506484,0.00173242)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624549,0.00832539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.829268,0.0158575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305681,-0.0116676) , 
9, 0.900144, 0, 0, 0.357955,-0.033301) , 
2, 39.6451, 0, 0, 0.499045,0.000346362)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668808,0.00809511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215238,-0.0199918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203753,0.000435317) , 
4, 0.454511, 0, 0, 0.210468,-0.0428666) , 
9, -0.13985, 0, 0, 0.511111,0.0049752)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744755,0.01628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562096,0.000778056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156773,-0.0169834) , 
9, -0.426348, 0, 0, 0.432195,-0.0144546) , 
0, 5.2381, 0, 0, 0.500381,0.000650093)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581201,0.00480343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383065,-0.00284411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192982,-0.0340711) , 
4, 0.383513, 0, 0, 0.3137,-0.0467265) , 
1, 0.591649, 0, 0, 0.500194,-0.00179844)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5278,0.00355334) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205607,-0.0247802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0652174,-0.0625375) , 
2, 28.1178, 0, 0, 0.163399,-0.117982) , 
0, 2.38095, 0, 0, 0.506641,0.00511801)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548661,0.00388026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367347,0.0253891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179577,-0.0339362) , 
4, 0.863543, 0, 0, 0.207207,-0.0819631) , 
6, -2.83825, 0, 0, 0.506329,0.00217856)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565294,0.00942509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648649,0.0115621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326843,-0.0163696) , 
1, 0.787575, 0, 0, 0.392699,-0.0356986) , 
3, 0.923598, 0, 0, 0.505376,0.00983648)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521102,0.00279176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277228,-0.0502397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152381,-0.0095621) , 
9, 0.430008, 0, 0, 0.213592,-0.119633) , 
3, 0.786381, 0, 0, 0.496044,-0.000618956)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858382,0.0260517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659449,0.0101348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377841,-0.00843934) , 
1, 0.772844, 0, 0, 0.440917,-0.0148614) , 
7, -0.0945743, 0, 0, 0.496174,-0.0025853)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548718,0.00496638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0581136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159851,-0.0200834) , 
9, 0.804652, 0, 0, 0.181538,-0.0924853) , 
6, -2.83825, 0, 0, 0.50394,0.00426301)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551123,0.00307219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455285,-0.0407487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226064,-0.0115668) , 
9, 0.422714, 0, 0, 0.282565,-0.0689094) , 
0, 3.33333, 0, 0, 0.501119,-0.00394139)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555657,0.00196838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38961,-0.0373661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214493,-0.00879821) , 
9, 0.236026, 0, 0, 0.268537,-0.0663186) , 
0, 3.14286, 0, 0, 0.502237,-0.00665669)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685829,0.00890122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500668,0.0021693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377798,-0.00888025) , 
3, 0.969483, 0, 0, 0.427117,-0.0155655) , 
2, 50.6481, 0, 0, 0.501148,-0.002449)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783237,0.0250514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720513,0.0104717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413613,-0.00571773) , 
1, 0.803145, 0, 0, 0.465652,-0.01046) , 
2, 62.5773, 0, 0, 0.507181,0.00189807)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795322,0.0179161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453699,-0.000971427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300926,-0.0230609) , 
4, 0.181808, 0, 0, 0.438343,-0.0116611) , 
8, 1.53639, 1, 0, 0.507137,0.00146214)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730392,0.0141505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517772,-0.00120164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225862,-0.0232298) , 
7, -6.1537, 0, 0, 0.443122,-0.0226938) , 
2, 59.6531, 0, 0, 0.486921,-0.012109)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674497,0.0108565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425507,0.00207889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283972,-0.0133797) , 
4, 0.359294, 0, 0, 0.368011,-0.0138498) , 
7, -2.8569, 0, 0, 0.508253,0.00989488)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619622,0.00313626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171103,-0.0349935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145055,-0.0043895) , 
5, -0.668137, 0, 0, 0.154596,-0.0587644) , 
9, -0.425665, 0, 0, 0.492378,-0.00769103)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587065,0.0061917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422897,-0.00366596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189526,-0.0237682) , 
6, -2.19153, 0, 0, 0.310012,-0.0420924) , 
7, -5.72563, 0, 0, 0.5,0.00171134)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795455,0.0270655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535186,0.00282753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34464,-0.013833) , 
3, 0.908317, 0, 0, 0.477348,-0.00731137) , 
2, 70.0339, 0, 0, 0.503776,0.000351361)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537282,0.000927693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325301,-0.0345178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150407,-0.0149068) , 
9, 0.614769, 0, 0, 0.194529,-0.0659675) , 
6, -2.82822, 0, 0, 0.495142,-0.00526552)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589381,0.0046387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484487,-0.0208247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.00235641) , 
9, 0.142605, 0, 0, 0.323013,-0.038837) , 
1, 0.623004, 0, 0, 0.492492,-0.00368943)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549767,0.00143766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45045,-0.0367673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220745,-0.00739334) , 
9, 0.422714, 0, 0, 0.273101,-0.0520765) , 
0, 3.33333, 0, 0, 0.498673,-0.00558871)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533766,0.00334594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342657,-0.0369447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.154321,-0.00978425) , 
9, 0.530899, 0, 0, 0.242623,-0.0850602) , 
3, 0.816775, 0, 0, 0.499809,0.000238406)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51063,5.11474e-06) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.0655226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,-0.0301971) , 
9, 0.320814, 0, 0, 0.115702,-0.144355) , 
6, -4.58562, 0, 0, 0.492349,-0.00666535)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530351,0.00280002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181102,-0.0222115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.06,-0.0589727) , 
5, -4.55833, 1, 0, 0.146893,-0.0965696) , 
5, -3.85349, 0, 0, 0.505035,0.00274749)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565457,0.00383152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392638,-0.0310099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211009,-0.00643957) , 
9, 0.235141, 0, 0, 0.271429,-0.0550436) , 
0, 3.33333, 0, 0, 0.511436,0.000601)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572603,0.00640964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616883,0.0142607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317935,-0.0159895) , 
1, 0.795948, 0, 0, 0.369663,-0.0349172) , 
4, 0.359298, 0, 0, 0.506077,0.00306679)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726126,0.0115763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468004,-0.00213675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244361,-0.0189465) , 
2, 29.2989, 0, 0, 0.43981,-0.0141835) , 
2, 55.0264, 0, 0, 0.499437,-0.00334495)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555556,0.00315726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328125,-0.0196897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185393,0.00501475) , 
7, -4.32794, 0, 0, 0.282918,-0.0455796) , 
2, 32.5153, 0, 0, 0.497141,-0.00115438)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511085,0.000450604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318182,-0.00827646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0506329,-0.06402) , 
4, 0.349969, 0, 0, 0.172414,-0.11835) , 
3, 0.755513, 0, 0, 0.492699,-0.00496912)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536765,0.00615152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171429,-0.00231334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14,-0.0535562) , 
6, -0.575257, 1, 0, 0.158333,-0.0939262) , 
0, 2.14286, 0, 0, 0.519081,0.0156848)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519819,-0.00756151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627648,0.0149847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345178,-0.00235828) , 
1, 0.649326, 0, 0, 0.495549,0.0245419) , 
3, 0.984731, 0, 0, 0.503894,0.00719934)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502864,-0.00508231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0446671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239583,-0.00829458) , 
5, -2.55386, 0, 0, 0.403409,0.0605387) , 
8, 5.73111, 1, 0, 0.496183,-0.0121014)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598063,0.00493124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145503,-0.00347259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14094,-0.0370703) , 
7, -2.74253, 1, 0, 0.144213,-0.0459234) , 
9, -0.61565, 0, 0, 0.505787,0.00470739)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57319,0.00334675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526946,-0.0240342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255,-0.00757437) , 
9, 0.807052, 0, 0, 0.314211,-0.0385438) , 
7, -5.79579, 0, 0, 0.49772,-0.0031001)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517364,0.00160956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175676,-0.0467055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122807,0.00274457) , 
9, 0.157734, 0, 0, 0.152672,-0.0968556) , 
3, 0.7557, 0, 0, 0.499437,0.000416352)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551198,0.00492796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379518,0.00747595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183333,-0.028107) , 
3, 0.969661, 0, 0, 0.263547,-0.0397865) , 
2, 30.8877, 0, 0, 0.50796,0.00830443)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.839763,0.0227257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601116,-0.00979194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376543,-0.00041946) , 
5, -0.157565, 0, 0, 0.445443,-0.0116959) , 
8, 1.13729, 1, 0, 0.495138,-0.00219252)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671596,0.0047213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283401,-0.0261821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220102,0.00244886) , 
6, -0.157181, 0, 0, 0.235237,-0.0211627) , 
9, -0.0438566, 0, 0, 0.501883,0.00164797)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.808271,0.0227589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490728,0.00205685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192982,-0.0319667) , 
1, 0.434097, 0, 0, 0.476129,0.00238909) , 
5, 1.11172, 0, 0, 0.510228,0.00914715)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687199,0.00661113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522095,0.00300285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265837,-0.0125549) , 
1, 0.68554, 0, 0, 0.370569,-0.0190095) , 
7, -2.3882, 0, 0, 0.500395,-0.0022363)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524293,-0.000952992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705263,0.0580931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304511,0.000466869) , 
6, -1.32199, 0, 0, 0.409972,0.055127) , 
8, 5.10246, 1, 0, 0.508571,0.00481389)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862559,0.0222062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549602,0.00237361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357988,-0.00746722) , 
4, 0.450821, 0, 0, 0.468476,-0.00589368) , 
8, 0.7679, 1, 0, 0.500384,-0.000837797)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546578,0.00170507) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328947,-0.0453647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192053,0.00208241) , 
9, 0.143354, 0, 0, 0.237885,-0.054905) , 
1, 0.528388, 0, 0, 0.495035,-0.00442454)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524244,0.00203905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355932,-0.0375637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14094,-0.0151271) , 
9, 0.140494, 0, 0, 0.201923,-0.0688093) , 
1, 0.465999, 0, 0, 0.498665,0.000866737)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550871,0.00325315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.0588499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232493,-0.00342527) , 
9, 0.806371, 0, 0, 0.256595,-0.0389036) , 
1, 0.52581, 0, 0, 0.503655,0.00307237)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.849442,0.0155932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5097,-0.0119524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369709,0.000103745) , 
1, 0.748607, 0, 0, 0.407888,-0.0123077) , 
9, 0.903539, 0, 0, 0.498663,-0.00140351)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5577,0.0011078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114815,-0.0101301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.078125,-0.0509799) , 
6, -0.00515386, 1, 0, 0.107784,-0.0550764) , 
9, -0.805414, 0, 0, 0.502392,-0.00342727)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.720957,0.00497954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487654,0.00866454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338687,-0.0115424) , 
8, 2.48786, 1, 0, 0.366173,-0.0259583) , 
7, -1.67413, 0, 0, 0.484434,-0.0119904)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574304,0.00493029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4375,-0.0144214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.190476,0.0085923) , 
9, -0.23574, 0, 0, 0.354633,-0.0288223) , 
4, 0.409233, 0, 0, 0.495814,0.000174105)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746528,0.0149504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440619,-0.00226509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0961538,-0.0501135) , 
1, 0.402666, 0, 0, 0.431907,-0.011028) , 
0, 5.2381, 0, 0, 0.50076,0.00126905)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520178,-0.000457816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306122,0.0144823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0875,-0.0521601) , 
8, 5.45765, 1, 0, 0.170543,-0.0771398) , 
6, -4.40044, 0, 0, 0.502877,-0.00526173)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499195,0.000115398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35,-0.0500811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243243,-0.00343965) , 
9, 0.709068, 0, 0, 0.280702,-0.0755485) , 
4, 0.138488, 0, 0, 0.489615,-0.00295038)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708618,0.0132372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447894,-0.00222777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122449,-0.0312137) , 
3, 0.755513, 0, 0, 0.431125,-0.0112244) , 
2, 50.7017, 0, 0, 0.508166,0.00364039)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576651,0.00506542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508806,-0.0118018) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228637,0.00550072) , 
9, 0.143651, 0, 0, 0.380297,-0.0163712) , 
4, 0.409081, 0, 0, 0.506439,0.00475148)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580856,0.00842623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.782946,0.0135197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3485,-0.00840668) , 
7, -1.13858, 0, 0, 0.435321,-0.0141361) , 
3, 0.954159, 0, 0, 0.510487,0.00767066)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.938776,0.0430499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487136,-0.00544816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392157,0.0152841) , 
8, 5.62422, 1, 0, 0.479612,-0.0126786) , 
8, -0.299893, 1, 0, 0.488186,-0.0105992)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507327,-0.00134001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3125,0.00264028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0322581,-0.0677269) , 
4, 0.513097, 0, 0, 0.174603,-0.0836922) , 
1, 0.432233, 0, 0, 0.491513,-0.00819461)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.687136,0.00475019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234591,-0.00665384) , 
9, 0.0493864, 0, 0, 0.50038,0.000480897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372093,0.0507382) , 
5, -6.4732, 0, 0, 0.498319,0.00284889)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.895604,0.0307601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742268,0.015637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43956,-0.00415801) , 
2, 70.1262, 0, 0, 0.463345,-0.00898585) , 
8, 0.647653, 1, 0, 0.493021,-0.0035281)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740995,0.0115158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462415,-0.00210636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224409,-0.0182025) , 
2, 29.4739, 0, 0, 0.432338,-0.013303) , 
0, 5.2381, 0, 0, 0.501735,-0.00260794)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541214,0.00228581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346614,-0.0308687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194313,0.00511753) , 
2, 47.7654, 0, 0, 0.277056,-0.0571401) , 
7, -8.03742, 0, 0, 0.495506,-0.00371956)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525227,0.00136117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206349,-0.0405289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185185,0.00110571) , 
1, 0.707352, 0, 0, 0.191919,-0.0469998) , 
5, -3.67285, 0, 0, 0.5,0.000588144)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659381,0.0048716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.227991,-0.0192906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208068,0.0109829) , 
4, 0.59957, 0, 0, 0.217724,-0.0193698) , 
9, -0.140599, 0, 0, 0.501757,0.00352244)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584793,0.00640171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.140065,0.000252263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135135,-0.0272752) , 
1, 0.652712, 1, 0, 0.138462,-0.028162) , 
9, -0.709819, 0, 0, 0.507429,0.0129857)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852518,0.0145428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504747,-0.00774049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272059,0.0056605) , 
5, -1.16787, 0, 0, 0.413462,-0.0108864) , 
9, 0.903041, 0, 0, 0.50607,-0.00104639)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734807,-0.0229463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843424,0.0151793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398587,-0.000413372) , 
9, 0.902905, 0, 0, 0.485169,0.00638845) , 
6, 1.24668, 0, 0, 0.502271,0.00191468)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546846,0.00174086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426966,0.0141352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191837,-0.0329704) , 
4, 0.371894, 0, 0, 0.29078,-0.0395081) , 
3, 0.847196, 0, 0, 0.504847,-0.00169377)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796154,0.0200069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603643,0.00461924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341382,-0.00516734) , 
2, 40.1234, 0, 0, 0.469839,-0.00102581) , 
1, 0.84281, 0, 0, 0.502295,0.0049111)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590884,0.00666534) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362525,0.00432383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301136,-0.0198522) , 
8, 4.51058, 0, 0, 0.336892,-0.0179547) , 
7, -5.72563, 0, 0, 0.510511,0.0092411)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727664,0.00848654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593548,-0.0129093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263804,-0.000943473) , 
9, 0.522859, 0, 0, 0.379898,-0.0182019) , 
6, -0.118693, 0, 0, 0.5,-0.00304544)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530228,-0.00306865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649635,0.0251819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345291,0.00190444) , 
1, 0.774994, 0, 0, 0.41681,0.0266266) , 
4, 0.272718, 0, 0, 0.504806,-0.0015969)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52457,0.00213892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373913,-0.0403005) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259259,0.00463585) , 
9, 0.524479, 0, 0, 0.312,-0.0628164) , 
4, 0.17624, 0, 0, 0.504829,0.000403521)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522029,-0.000906257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514403,0.0279952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,-0.00942091) , 
5, -3.50209, 0, 0, 0.4047,0.0485804) , 
8, 5.05436, 1, 0, 0.504943,0.00456225)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566667,-0.0124555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615854,-0.00236535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336008,0.00727728) , 
5, -0.896887, 0, 0, 0.485781,0.00645414) , 
4, 0.908471, 0, 0, 0.501318,-0.00231681)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783784,0.0221171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536195,0.0013653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371854,-0.00767879) , 
3, 0.923598, 0, 0, 0.477207,-0.00586927) , 
2, 71.3027, 0, 0, 0.498855,-0.000938476)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.848649,0.0109358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632124,-0.01936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369085,-0.00282166) , 
7, -0.0674874, 0, 0, 0.393317,-0.015033) , 
9, 0.903456, 0, 0, 0.488679,-0.00644341)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503765,4.58337e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302326,-0.0492831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215686,-0.00899946) , 
9, 0.528831, 0, 0, 0.255319,-0.105765) , 
4, 0.130475, 0, 0, 0.494841,-0.00365785)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522755,0.00211655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1625,-0.0350428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129032,0.00925169) , 
9, -0.711114, 0, 0, 0.147887,-0.058231) , 
0, 2.09524, 0, 0, 0.502476,0.00339223)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570928,0.000845975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147368,0.0365164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110119,-0.0259838) , 
3, 0.908605, 1, 0, 0.118329,-0.0435332) , 
9, -0.710477, 0, 0, 0.499079,-0.00451564)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626953,-0.00529799) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570156,0.0102119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241477,-0.00240666) , 
6, -1.16059, 0, 0, 0.425718,0.016665) , 
1, 0.71593, 0, 0, 0.504189,0.00345595)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558325,0.00285914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326613,-0.00234929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211538,-0.0307787) , 
4, 0.229164, 0, 0, 0.29908,-0.0288775) , 
7, -6.70377, 0, 0, 0.494733,-0.000136378)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562753,0.00384072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533186,0.00275807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250482,-0.0170356) , 
1, 0.664287, 0, 0, 0.38208,-0.022138) , 
3, 0.923598, 0, 0, 0.497778,5.97821e-05)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517255,0.000474554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291667,-0.00694239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253731,-0.032595) , 
8, 4.23608, 0, 0, 0.269565,-0.0782958) , 
4, 0.138488, 0, 0, 0.506449,-0.00197324)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522345,5.67444e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191011,-0.0358203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.120879,-0.00503197) , 
9, -0.233763, 0, 0, 0.155556,-0.0674029) , 
5, -3.85349, 0, 0, 0.497136,-0.00446195)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713885,0.00750916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.290441,-0.0127607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247974,0.00881943) , 
4, 0.590904, 0, 0, 0.267873,-0.00820483) , 
9, 0.238538, 0, 0, 0.513722,0.0093576)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588668,-0.00538571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,0.0395596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397458,0.00605182) , 
5, -6.22666, 1, 0, 0.397551,0.0233361) , 
8, 2.99892, 1, 0, 0.498065,0.00228279)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564,-0.0124023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57935,0.00662863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407111,-0.00111527) , 
4, 0.452972, 0, 0, 0.490097,0.00826819) , 
4, 0.908471, 0, 0, 0.503931,-0.000441018)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506723,-0.000740575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0117622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106383,-0.049941) , 
8, 5.93306, 1, 0, 0.152174,-0.0973874) , 
5, -5.07896, 0, 0, 0.49462,-0.00561369)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528768,-0.0043369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654762,0.0385007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264706,-0.00983397) , 
6, -1.56049, 0, 0, 0.393701,0.022287) , 
8, 4.57779, 1, 0, 0.502489,-0.00685161)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772093,0.0203107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526786,0.000329089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324967,-0.0119177) , 
3, 0.908317, 0, 0, 0.464095,-0.0107327) , 
2, 70.0461, 0, 0, 0.489065,-0.00530679)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870968,0.0346838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663609,-0.0113813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468218,0.00164552) , 
1, 0.814107, 0, 0, 0.493167,8.68914e-05) , 
1, 0.898556, 0, 0, 0.502097,0.00241453)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516449,0.0014523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254902,0.00597006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,-0.0500794) , 
8, 5.75304, 1, 0, 0.169811,-0.0658577) , 
6, -4.78773, 0, 0, 0.502472,0.00179681)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527559,0.00122551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3,-0.0489391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17341,-0.00153594) , 
9, 0.810146, 0, 0, 0.201794,-0.0465044) , 
3, 0.786074, 0, 0, 0.5,-0.00031549)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684917,-0.00695662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646154,0.019409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346485,0.000300254) , 
1, 0.793522, 0, 0, 0.393591,0.0118523) , 
5, -0.157565, 0, 0, 0.501144,-0.00030101)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486317,-0.0031765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463415,0.0722049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133333,-0.0133142) , 
3, 0.939847, 0, 0, 0.290698,0.0736876) , 
1, 0.419061, 0, 0, 0.479955,-0.00747541)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.834225,0.0195937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578652,0.0142229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461335,-0.00277694) , 
4, 0.954534, 0, 0, 0.469889,-0.00490746) , 
5, 1.24855, 0, 0, 0.495814,-0.000924703)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53762,-0.0029025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561644,0.0703438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303191,0.00736862) , 
2, 30.8789, 0, 0, 0.345212,0.0540747) , 
2, 31.493, 0, 0, 0.504921,0.00143677)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507296,-0.000344579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682927,0.06356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136364,-0.0175937) , 
5, -3.23947, 0, 0, 0.4,0.0874676) , 
8, 6.23912, 1, 0, 0.503905,0.00169391)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507602,0.00127991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0357353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204545,-0.000618475) , 
0, 4.09524, 0, 0, 0.240385,-0.0788212) , 
4, 0.136353, 0, 0, 0.49719,0.000845823)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81106,0.0240003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872611,0.021558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443862,-0.00360658) , 
8, 0.516973, 1, 0, 0.471382,-0.00783281) , 
2, 69.9692, 0, 0, 0.499061,-0.0021427)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545662,-0.00359843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311688,0.0223852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.112903,-0.0265745) , 
8, 6.32026, 1, 0, 0.284116,0.045164) , 
5, -2.26674, 0, 0, 0.501327,-0.00207247)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588276,0.00714242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488506,-0.023734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427103,0.000779793) , 
3, 0.941024, 0, 0, 0.435691,-0.00867526) , 
3, 0.954159, 0, 0, 0.51737,0.00822529)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594624,0.00523562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528226,-0.0234941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252129,0.00213844) , 
9, 0.618999, 0, 0, 0.334132,-0.0200655) , 
7, -5.59401, 0, 0, 0.512792,0.00530073)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549407,-0.0156362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.852713,0.0278657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483799,0.00066732) , 
5, 1.27675, 0, 0, 0.503778,0.00590751) , 
4, 0.954235, 0, 0, 0.508159,0.000753666)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552792,-0.00220452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594203,0.0426321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351974,0.00231693) , 
7, -5.5471, 0, 0, 0.396783,0.0316876) , 
8, 3.86583, 1, 0, 0.507241,0.00430617)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785558,0.0083597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357912,-0.00820663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314815,0.0103975) , 
4, 0.329208, 0, 0, 0.344591,-0.0100802) , 
9, 0.713383, 0, 0, 0.496054,0.0012016)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.701721,0.0065009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468235,-0.00983065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250356,0.00174779) , 
0, 4.19048, 0, 0, 0.369607,-0.0172273) , 
7, -2.347, 0, 0, 0.503271,-0.00231376)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508313,-0.000801147) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617284,0.0478938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257426,-0.00626052) , 
1, 0.630662, 0, 0, 0.417582,0.0669353) , 
8, 5.66337, 1, 0, 0.501932,0.00234385)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513309,-0.000551302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119048,-0.0335817) , 
3, 0.752038, 0, 0, 0.500577,-0.00441831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321429,0.0299467) , 
3, 0.709672, 0, 0, 0.496801,-0.00255466)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566491,-0.00187836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56383,0.0258343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348238,0.000507189) , 
7, -5.66227, 0, 0, 0.392009,0.018562) , 
8, 3.60225, 1, 0, 0.505127,0.00268678)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746377,0.0111337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544695,-0.00713429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274942,0.00385207) , 
6, -0.998873, 0, 0, 0.431763,-0.00979623) , 
0, 5.28571, 0, 0, 0.498277,-0.00104186)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514872,0.00089813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335821,-0.0274386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235294,-0.00190966) , 
0, 4.28571, 0, 0, 0.292373,-0.0580931) , 
4, 0.182015, 0, 0, 0.494853,-0.00265312)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627042,0.00767429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439516,-0.00159332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0714286,-0.0523267) , 
1, 0.402666, 0, 0, 0.429412,-0.00862426) , 
4, 0.681814, 0, 0, 0.512158,0.00490296)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565392,-0.00961472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664653,0.00838622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409606,-4.28898e-05) , 
1, 0.748607, 0, 0, 0.487737,0.00849311) , 
4, 0.909315, 0, 0, 0.502257,0.00141458)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581433,0.00166384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360153,-0.00633783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197324,-0.0248689) , 
4, 0.326058, 0, 0, 0.300853,-0.0388075) , 
7, -5.72563, 0, 0, 0.494931,-0.00833109)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543338,-0.00311335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44382,0.0318956) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288557,0.00285437) , 
1, 0.520632, 0, 0, 0.336207,0.0366055) , 
1, 0.556092, 0, 0, 0.497114,0.000297464)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6186,0.00462781) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429372,-0.00563853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346154,0.0312362) , 
3, 0.710505, 0, 0, 0.426763,-0.0147545) , 
4, 0.771178, 0, 0, 0.496942,-0.00410285)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711222,0.00409973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33687,-0.0171792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214115,-0.00141185) , 
6, -0.360054, 0, 0, 0.252267,-0.0245637) , 
9, 0.238706, 0, 0, 0.498086,-0.00466278)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689878,0.00700003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276119,-0.0302799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22659,0.00152466) , 
8, 1.79749, 1, 0, 0.233233,-0.0131407) , 
9, -0.0456599, 0, 0, 0.51098,0.00832531)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550391,-0.000543901) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407692,-0.0303721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18984,-0.00617547) , 
9, 0.329266, 0, 0, 0.246032,-0.0421758) , 
0, 3.33333, 0, 0, 0.493089,-0.00933824)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743158,0.0111997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552632,-0.00660637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281723,0.00650352) , 
5, -0.950461, 0, 0, 0.442499,-0.00532977) , 
2, 57.0572, 0, 0, 0.497682,0.00149448)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588385,0.00481554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449165,0.00168599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.226829,-0.021898) , 
3, 0.893037, 0, 0, 0.363891,-0.021408) , 
4, 0.450824, 0, 0, 0.497344,0.000366712)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541054,0.00443248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325444,-0.0241254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,0.0277968) , 
9, 0.338571, 0, 0, 0.257627,-0.0272696) , 
3, 0.816635, 0, 0, 0.509007,0.00965419)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533714,-0.00793449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669131,0.0141552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389845,-0.00367726) , 
1, 0.741359, 0, 0, 0.478567,0.00722407) , 
3, 0.98472, 0, 0, 0.497285,-0.00374295)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557453,0.00544435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403226,-0.0372224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274011,0.000356935) , 
5, -0.23279, 0, 0, 0.293269,-0.0177725) , 
3, 0.847196, 0, 0, 0.514905,0.0117827)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644068,0.00625032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578723,0.0114075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286538,-0.0102261) , 
1, 0.763044, 0, 0, 0.340392,-0.0175983) , 
7, -3.47321, 0, 0, 0.493587,0.00127907)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547977,0.00187889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31401,-0.0246891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287449,-0.00377904) , 
7, -9.55913, 0, 0, 0.299559,-0.0422225) , 
7, -7.81353, 0, 0, 0.504264,-0.00254567)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544423,-0.00238039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533333,-0.00362072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266254,0.0275562) , 
9, 0.524131, 0, 0, 0.391447,0.031636) , 
3, 0.877928, 0, 0, 0.509112,0.00147195)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510751,-0.00183176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430894,0.0181316) , 
8, 5.84125, 1, 0, 0.506955,-0.00291307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,0.0332776) , 
5, -6.2442, 0, 0, 0.503794,-0.00112411)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511214,-0.00101184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446429,0.0416128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116279,-0.00465097) , 
7, -6.86855, 0, 0, 0.30303,0.0673896) , 
3, 0.740431, 0, 0, 0.503538,-0.000620401)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614275,-0.000468803) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407407,0.0416962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39966,0.00529005) , 
2, 26.5426, 1, 0, 0.4,0.0219549) , 
0, 4.19048, 0, 0, 0.513565,0.00954346)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575812,0.00337875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49904,-0.016889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229858,0.00800974) , 
9, 0.142934, 0, 0, 0.378579,-0.0225145) , 
4, 0.405062, 0, 0, 0.504415,-0.00151264)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555509,0.00310983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245509,0.00551096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164634,-0.0300795) , 
8, 5.32697, 1, 0, 0.205438,-0.0358474) , 
6, -2.84209, 0, 0, 0.512593,0.00437879)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515612,-0.00166827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303704,0.00305588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30137,0.0474804) , 
8, 4.06243, 1, 0, 0.302885,0.0451416) , 
3, 0.786074, 0, 0, 0.498865,-0.00134246)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74395,0.00376769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304847,-0.012242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273196,0.00905548) , 
4, 0.454539, 0, 0, 0.291362,-0.01382) , 
9, 0.42877, 0, 0, 0.510389,-0.00186287)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530485,0.00374864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34,0.0262478) , 
7, -11.57, 0, 0, 0.522899,0.014472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146667,-0.0232113) , 
3, 0.724952, 0, 0, 0.511988,0.0123703)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608069,-0.00176268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469441,0.0161793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321277,-0.00354536) , 
7, -7.95586, 0, 0, 0.413236,0.0282161) , 
8, 2.97134, 1, 0, 0.516178,0.0104016)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633503,0.0043275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490798,-0.00229449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197605,-0.0193635) , 
0, 3.28571, 0, 0, 0.431013,-0.0180626) , 
4, 0.771178, 0, 0, 0.507053,-0.00648167)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553623,-0.00506846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402174,0.0397884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26971,0.00168541) , 
8, 3.12045, 1, 0, 0.290941,0.0238125) , 
6, -1.90627, 0, 0, 0.496596,-0.00757049)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647766,0.00372865) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404651,-0.0131982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379412,0.00105601) , 
8, 3.3441, 1, 0, 0.386897,-0.0105351) , 
8, 2.60867, 1, 0, 0.50306,-0.000737619)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512338,6.57778e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7,0.0640386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.230769,0.00492787) , 
5, -2.87037, 0, 0, 0.434783,0.100292) , 
8, 6.04109, 1, 0, 0.508995,0.00452143)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641399,-0.00833138) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546939,0.00951312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322957,-0.00388275) , 
4, 0.410542, 0, 0, 0.460421,0.0143758) , 
1, 0.773044, 0, 0, 0.506711,0.00386001)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508065,-0.00691571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484848,0.0182194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301802,-0.00201391) , 
8, 2.85624, 1, 0, 0.379845,0.0228864) , 
4, 0.227262, 0, 0, 0.489118,-0.0150325)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
