// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Tue Oct 14 14:43:10 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 3157
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "3157" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
numJets_40                    numJets_40                    numJets_40                    numJets_40                                                      'F'    [0,11]
MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_D_mass_of_leps_jets MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_mass_of_leps_jets                                           'F'    [0.298561811447,0.968418717384]
jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt                                                 'F'    [25.0757904053,182.589538574]
jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex                                         'F'    [0.679019451141,1]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0402120128274,0.999996304512]
Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq                                           'F'    [-12.109536171,2.87168049812]
Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq                                           'F'    [-11.6571483612,2.39190387726]
Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq                                          'F'    [-20.3663883209,3.0130417347]
log_chiSquared_               log_chiSquared_               log_chiSquared_               log_chiSquared_                                                 'F'    [-2.36038327217,8.4930562973]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numJets_40", "MT_of_leps_jets_mass_of_leps_jets", "jets_by_pt_5_pt", "jets_by_CSV_1_btagCombinedSecVertex", "jets_by_CSV_2_btagCombinedSecVertex", "Match_ttbar_jj_Bq_bqq", "Match_ttbar_jj_Bqq_bq", "Match_ttbar_jj_Bqq_bqq", "log_chiSquared_" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 11;
      fVmin[1] = 0.298561811447144;
      fVmax[1] = 0.968418717384338;
      fVmin[2] = 25.0757904052734;
      fVmax[2] = 182.589538574219;
      fVmin[3] = 0.679019451141357;
      fVmax[3] = 1;
      fVmin[4] = 0.0402120128273964;
      fVmax[4] = 0.999996304512024;
      fVmin[5] = -12.1095361709595;
      fVmax[5] = 2.87168049812317;
      fVmin[6] = -11.6571483612061;
      fVmax[6] = 2.3919038772583;
      fVmin[7] = -20.3663883209229;
      fVmax[7] = 3.01304173469543;
      fVmin[8] = -2.36038327217102;
      fVmax[8] = 8.49305629730225;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663055,0.032611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435897,-0.0128205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177986,-0.0644028) , 
2, 45.7306, 0, 0, 0.269289,-0.230711) , 
5, -1.15719, 0, 0, 0.498737,-0.00126263)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72583,0.0419506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564103,0.012943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231118,-0.0509133) , 
2, 48.182, 0, 0, 0.328342,-0.160822) , 
5, -0.514197, 0, 0, 0.497543,-0.00317193)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748276,0.0437665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460952,-0.00459046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220524,-0.0518645) , 
1, 0.627064, 0, 0, 0.348932,-0.132186) , 
6, -0.371789, 0, 0, 0.497121,-0.00234325)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790094,0.0498594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611702,0.0209084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293333,-0.0358859) , 
2, 47.5778, 0, 0, 0.399645,-0.0831075) , 
7, -1.44018, 0, 0, 0.506452,0.00705767)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.730408,0.0344052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460241,-0.00248263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225873,-0.0450295) , 
1, 0.657596, 0, 0, 0.333703,-0.124771) , 
5, -0.490903, 0, 0, 0.498052,-0.00308252)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757072,0.0362129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484487,0.00497016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238095,-0.0418909) , 
3, 0.923576, 0, 0, 0.345078,-0.105117) , 
5, -0.387335, 0, 0, 0.503193,0.00269997)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612476,0.0178312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507576,0.00373457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188295,-0.0521715) , 
1, 0.749026, 0, 0, 0.268571,-0.182674) , 
3, 0.893007, 0, 0, 0.498421,-0.00282343)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569092,0.0125725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647059,0.010006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144262,-0.0608289) , 
6, 0.187038, 0, 0, 0.235925,-0.228267) , 
2, 32.6, 0, 0, 0.491228,-0.00687476)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620821,0.0177816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477273,-0.00136353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173077,-0.0503651) , 
1, 0.747821, 0, 0, 0.24635,-0.181229) , 
3, 0.893042, 0, 0, 0.492163,-0.00601595)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716567,0.0350294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688073,0.0246507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282472,-0.0328949) , 
4, 0.725772, 0, 0, 0.400893,-0.0755125) , 
2, 47.5989, 0, 0, 0.498458,0.000228157)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711443,0.0265163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46,0.00031279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225806,-0.0352989) , 
1, 0.681337, 0, 0, 0.317647,-0.0987693) , 
5, -0.825481, 0, 0, 0.519439,0.0162004)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.699324,0.0237426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429752,-0.00356427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158879,-0.0427443) , 
0, 4.04762, 0, 0, 0.302632,-0.0987952) , 
5, -1.02911, 0, 0, 0.526718,0.020063)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572458,0.0110822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530303,0.00405113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1875,-0.0531872) , 
1, 0.770148, 0, 0, 0.254438,-0.190488) , 
0, 3.42857, 0, 0, 0.504726,0.000110409)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6461,0.0208792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589928,0.0160754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266667,-0.0359296) , 
0, 5.2381, 0, 0, 0.330042,-0.115428) , 
1, 0.646781, 0, 0, 0.503189,0.00124806)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655249,0.0174876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40625,-0.00877922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142415,-0.0464732) , 
3, 0.89319, 0, 0, 0.28,-0.118421) , 
6, -1.1695, 0, 0, 0.494937,-0.00446546)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826633,0.0366044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529887,0.00549321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242928,-0.0345539) , 
0, 4.19048, 0, 0, 0.388525,-0.0623825) , 
5, 0.267142, 0, 0, 0.496292,-0.00721598)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59726,0.0105101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642857,0.0271952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185366,-0.0404297) , 
4, 0.679168, 0, 0, 0.240343,-0.138697) , 
3, 0.877739, 0, 0, 0.490711,-0.0077412)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668401,0.0218775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518957,0.00225951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24714,-0.0354135) , 
0, 4.28571, 0, 0, 0.380675,-0.0709781) , 
1, 0.681337, 0, 0, 0.516585,0.0095172)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726916,0.0275906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493233,-0.00123525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0401037) , 
2, 36.6289, 0, 0, 0.379723,-0.0689497) , 
8, 2.15319, 1, 0, 0.49059,-0.008298)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627976,0.0136757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39881,-0.00400672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205656,-0.0351255) , 
4, 0.451548, 0, 0, 0.263914,-0.109732) , 
6, -1.58841, 0, 0, 0.498403,0.000190984)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57856,0.0110423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310204,-0.0209643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111111,-0.0645959) , 
0, 2.14286, 0, 0, 0.249292,-0.143336) , 
0, 3.14286, 0, 0, 0.504762,0.00578048)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602216,0.0113997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578947,0.0108852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22869,-0.0381172) , 
2, 55.1984, 0, 0, 0.286458,-0.123805) , 
1, 0.615125, 0, 0, 0.486297,-0.013568)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785855,0.0272069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525271,0.00629068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228669,-0.029323) , 
1, 0.649439, 0, 0, 0.372807,-0.048384) , 
6, -0.104892, 0, 0, 0.500303,0.00218386)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.639731,0.0135408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653543,0.0165349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241071,-0.029482) , 
4, 0.67296, 0, 0, 0.317322,-0.0853666) , 
3, 0.923765, 0, 0, 0.499366,-0.00369233)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563209,0.00774989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295154,-0.0263931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111111,-0.0588896) , 
0, 2.14286, 0, 0, 0.235821,-0.147234) , 
0, 3.42857, 0, 0, 0.493308,-0.00510868)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599817,0.0116842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332402,-0.0189211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.092437,-0.0526563) , 
0, 3.42857, 0, 0, 0.272537,-0.105702) , 
1, 0.585643, 0, 0, 0.500319,0.00294652)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53525,0.00585234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122449,-0.0756589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.046875,-0.0533616) , 
5, -0.702162, 0, 0, 0.079646,-0.246938) , 
0, 2.09524, 0, 0, 0.502541,0.00536614)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752747,0.0253835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0217599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315534,-0.0176314) , 
2, 54.6715, 0, 0, 0.378486,-0.0418905) , 
4, 0.684094, 0, 0, 0.510323,0.0107425)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.785558,0.0282348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66443,0.0219474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343392,-0.0145246) , 
2, 62.692, 0, 0, 0.386487,-0.0387368) , 
7, -1.57529, 0, 0, 0.502872,0.00611473)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628083,0.0100456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588235,0.0160544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209016,-0.0303917) , 
2, 68.231, 0, 0, 0.244898,-0.102001) , 
6, -1.51104, 0, 0, 0.498431,-0.00661098)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702586,0.021178) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921875,0.0464843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371622,-0.0149365) , 
7, 0.636255, 0, 0, 0.403636,-0.0469154) , 
2, 48.202, 0, 0, 0.492327,-0.00589641)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764302,0.0267189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55144,0.00507546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295691,-0.0184409) , 
1, 0.678438, 0, 0, 0.402934,-0.0328458) , 
8, 1.97356, 1, 0, 0.50188,0.00512571)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573517,0.00683169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361842,-0.0124372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182609,-0.0404779) , 
0, 3.04762, 0, 0, 0.253927,-0.106661) , 
2, 32.5764, 0, 0, 0.494498,-0.00502954)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549694,0.00281672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235294,-0.00827288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205607,-0.0394219) , 
8, 4.06694, 1, 0, 0.212766,-0.130562) , 
5, -2.37014, 0, 0, 0.489937,-0.0137047)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733146,0.0229701) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468538,-0.00467268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126374,-0.0501757) , 
2, 29.4516, 0, 0, 0.417284,-0.042418) , 
0, 5.14286, 0, 0, 0.488861,-0.0114849)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606947,0.0116989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345013,-0.0133934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0747664,-0.0516075) , 
3, 0.831923, 0, 0, 0.284519,-0.0800828) , 
1, 0.585643, 0, 0, 0.508906,0.0089228)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622371,0.0108291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661538,0.0204873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219565,-0.0236425) , 
4, 0.690812, 0, 0, 0.274286,-0.0653176) , 
3, 0.893007, 0, 0, 0.506047,0.00782409)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629268,0.0115129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388158,-0.00982292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0833333,-0.0548173) , 
0, 2.09524, 0, 0, 0.342179,-0.0598652) , 
2, 39.0997, 0, 0, 0.495443,-0.00263076)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552106,0.00468365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219512,-0.0140994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125828,-0.0477653) , 
8, 4.14428, 0, 0, 0.158798,-0.12848) , 
3, 0.801298, 0, 0, 0.494325,-0.00290916)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634672,0.00968715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423729,-0.000402275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180556,-0.030741) , 
3, 0.954194, 0, 0, 0.260708,-0.0743397) , 
6, -1.52948, 0, 0, 0.505777,-0.000225882)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.883495,0.0365453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711957,0.0266819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407407,-0.00866122) , 
1, 0.811507, 0, 0, 0.449071,-0.0144582) , 
5, 0.854131, 0, 0, 0.50677,0.00440321)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612711,0.00721275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.277293,-0.0168321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0875,-0.0503123) , 
5, -3.75092, 0, 0, 0.249071,-0.0785519) , 
3, 0.893022, 0, 0, 0.486084,-0.00832104)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692607,0.0186409) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702703,0.0296049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326676,-0.0116398) , 
1, 0.843755, 0, 0, 0.362581,-0.0268025) , 
3, 0.938861, 0, 0, 0.527167,0.0236205)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631579,0.00824257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23913,-0.0185051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117647,-0.0530345) , 
4, 0.145491, 0, 0, 0.227006,-0.0809634) , 
6, -1.62211, 0, 0, 0.500317,-0.00462906)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703158,0.0177145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669291,0.0170791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339367,-0.0162927) , 
0, 5.14286, 0, 0, 0.413005,-0.0320168) , 
1, 0.745133, 0, 0, 0.49845,-0.00228472)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616525,0.0103912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818182,0.0297172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235507,-0.0269286) , 
5, 0.810513, 0, 0, 0.306836,-0.0687176) , 
2, 36.6289, 0, 0, 0.492689,-0.00305605)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615865,0.00743424) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471698,-0.000932842) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141643,-0.0319754) , 
1, 0.748967, 0, 0, 0.217865,-0.0776389) , 
3, 0.877739, 0, 0, 0.500316,-0.00200515)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581373,0.00652914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675676,0.0263674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245322,-0.0275289) , 
2, 66.3437, 0, 0, 0.302703,-0.0729099) , 
7, -5.82118, 0, 0, 0.485785,-0.00903003)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57598,0.00742063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289855,-0.0419425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253247,-0.0139132) , 
3, 0.984715, 0, 0, 0.259947,-0.0698636) , 
1, 0.556804, 0, 0, 0.501562,0.00510674)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688547,0.012876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60223,0.0117914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241087,-0.0225139) , 
7, -2.62784, 0, 0, 0.354312,-0.0411889) , 
4, 0.542935, 0, 0, 0.506353,-0.000489999)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653587,0.0127329) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651429,0.0104681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263757,-0.0120441) , 
4, 0.774347, 0, 0, 0.360399,-0.0204558) , 
1, 0.646781, 0, 0, 0.524467,0.0179075)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539589,0.00223624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213333,-0.0268435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0384615,-0.0665295) , 
7, -8.66579, 1, 0, 0.168317,-0.124582) , 
6, -2.97609, 0, 0, 0.491699,-0.00881117)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80787,0.0199567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396912,-0.00461467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0666667,-0.0672001) , 
6, -5.77853, 0, 0, 0.383944,-0.0262209) , 
7, -1.44018, 0, 0, 0.5,-0.000985908)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563328,0.00781146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.00157739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115607,-0.043671) , 
8, 2.22003, 1, 0, 0.214592,-0.096896) , 
2, 30.2397, 0, 0, 0.512256,0.0104357)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574864,0.00720142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213592,-0.0286137) , 
2, 29.8512, 0, 0, 0.525084,0.0104714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150685,-0.0478542) , 
5, -4.97562, 0, 0, 0.507653,0.00174155)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95082,0.0543166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572062,0.00125764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308943,-0.0171185) , 
2, 36.7247, 0, 0, 0.465392,-0.0205411) , 
8, 0.277279, 1, 0, 0.484157,-0.0134074)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709677,0.0176669) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674641,0.0146801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356725,-0.0114377) , 
1, 0.777031, 0, 0, 0.419173,-0.0210017) , 
2, 47.5778, 0, 0, 0.511538,0.00690326)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70347,0.0116205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.018356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322464,-0.013411) , 
2, 66.2987, 0, 0, 0.362179,-0.034026) , 
7, -2.50834, 0, 0, 0.5,-0.00382351)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80137,0.031906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.925234,0.0355994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433255,-0.00641674) , 
5, 1.10926, 0, 0, 0.471182,-0.0136608) , 
1, 0.842243, 0, 0, 0.502608,-0.00169145)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505405,0.000366921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.189655,-0.0504883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111111,-0.0281262) , 
2, 49.4756, 0, 0, 0.15534,-0.156306) , 
5, -4.26223, 0, 0, 0.482628,-0.00895892)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716463,0.0182273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789298,0.0111897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318367,-0.0140839) , 
7, -1.04884, 0, 0, 0.42846,-0.0304373) , 
2, 55.0784, 0, 0, 0.487243,-0.0103781)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551797,0.00713124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186047,-0.00559743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119565,-0.0445919) , 
3, 0.700872, 1, 0, 0.140741,-0.0980307) , 
3, 0.755478, 0, 0, 0.516088,0.0145146)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52752,0.003957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.12766,-0.0632121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0384615,-0.0395787) , 
6, -1.04433, 0, 0, 0.0808081,-0.154616) , 
0, 2.09524, 0, 0, 0.497997,0.00288408)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576599,0.00596681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331395,-0.0366672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165094,-0.0141726) , 
7, -2.79777, 0, 0, 0.239583,-0.0817048) , 
2, 32.6, 0, 0, 0.494275,-0.00361826)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540346,0.00428783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245161,-0.00971964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208333,-0.0553746) , 
3, 0.96943, 1, 0, 0.236453,-0.0722783) , 
1, 0.493492, 0, 0, 0.501571,0.00392407)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51968,0.00302171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27907,-0.0122585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.129032,-0.0491961) , 
5, -6.05162, 1, 0, 0.190476,-0.121936) , 
6, -4.31164, 0, 0, 0.49813,0.00170474)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604651,0.00639661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355556,-0.0207682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210526,0.000706767) , 
8, 3.10321, 1, 0, 0.294659,-0.0415912) , 
2, 35.3566, 0, 0, 0.500618,0.00153744)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583402,0.00673225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256281,-0.0099233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,-0.0384533) , 
3, 0.751056, 0, 0, 0.194529,-0.0578188) , 
3, 0.847152, 0, 0, 0.500647,0.00675643)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648366,0.00840989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497487,-0.00199179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215103,-0.0219725) , 
0, 4.19048, 0, 0, 0.349701,-0.0374474) , 
1, 0.680358, 0, 0, 0.4925,-0.00512743)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809211,0.0300908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712062,0.015233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407279,-0.00590659) , 
2, 55.0984, 0, 0, 0.462792,-0.00617988) , 
1, 0.840827, 0, 0, 0.496481,0.00403544)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716578,0.0109565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.929825,0.0348533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398116,-0.00812343) , 
7, 0.753661, 0, 0, 0.422857,-0.0229595) , 
0, 5.14286, 0, 0, 0.491557,-0.0088076)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531228,0.000452479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255814,-0.0467282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163043,-0.0050037) , 
5, -1.24553, 0, 0, 0.207865,-0.0900748) , 
1, 0.489949, 0, 0, 0.494589,-0.00880841)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.896552,0.0275254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482158,-0.000282394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12,-0.0350152) , 
2, 30.3259, 0, 0, 0.428466,-0.0147427) , 
6, 0.657288, 0, 0, 0.497154,-0.00172217)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569478,0.00534062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475,0.0113524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205387,-0.0281855) , 
2, 35.7499, 0, 0, 0.237389,-0.0678022) , 
0, 3.42857, 0, 0, 0.498736,0.000309646)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.804598,0.0263188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49179,-0.00145617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16875,-0.0308703) , 
1, 0.476999, 0, 0, 0.454282,-0.0145913) , 
1, 0.834545, 0, 0, 0.493557,-0.00345971)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507703,0.00217202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16,-0.0143745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145455,-0.0511864) , 
4, 0.334175, 1, 0, 0.152381,-0.103671) , 
1, 0.452752, 0, 0, 0.484355,0.000114914)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537383,0.00239157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.0498561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0677966,-0.0233164) , 
5, -0.707257, 0, 0, 0.1,-0.102969) , 
0, 2.14286, 0, 0, 0.510013,0.00127394)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602824,0.00642347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261972,-0.00581828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148148,-0.0415353) , 
7, -5.46295, 1, 0, 0.240826,-0.037948) , 
5, -1.80019, 0, 0, 0.502231,0.00552992)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744565,0.0190501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469971,-0.00346184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0753425,-0.0457264) , 
6, -2.83708, 0, 0, 0.421757,-0.0250875) , 
0, 5.14286, 0, 0, 0.497761,-0.00394604)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724138,0.01367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468224,-0.00124231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.165289,-0.029461) , 
1, 0.457992, 0, 0, 0.437448,-0.0119904) , 
1, 0.777031, 0, 0, 0.502274,0.0010513)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704225,0.0107689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.821429,0.0156112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319743,-0.00881947) , 
7, -0.461977, 0, 0, 0.396364,-0.0175669) , 
2, 47.5989, 0, 0, 0.492173,-0.000622261)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.897196,0.025894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767677,0.0232856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.00528699) , 
2, 70.0797, 0, 0, 0.426112,-0.011032) , 
7, -0.326877, 0, 0, 0.488806,-0.00106055)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540107,0.00677018) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292683,-0.0152991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123288,-0.0447789) , 
4, 0.379452, 0, 0, 0.184211,-0.110493) , 
6, -4.31164, 0, 0, 0.514907,0.0128592)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.766234,0.0107841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524116,-0.0155926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347052,-0.00134855) , 
1, 0.745133, 0, 0, 0.392562,-0.0180535) , 
8, 1.87626, 1, 0, 0.482759,-0.00617427)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498959,-0.00302319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195652,-0.0222741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15,-0.0433519) , 
8, 5.78117, 1, 0, 0.174419,-0.108831) , 
6, -4.6444, 0, 0, 0.480681,-0.0154909)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540184,0.00571192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1,-0.0539599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0806452,-0.0196861) , 
1, 0.659411, 0, 0, 0.0882353,-0.089011) , 
0, 2.14286, 0, 0, 0.511728,0.0124942)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523582,0.00497204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297872,-0.017744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111111,-0.0412941) , 
6, -2.50738, 0, 0, 0.206522,-0.0946101) , 
4, 0.142578, 0, 0, 0.504823,0.00976077)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519861,0.00245459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207792,-0.0301499) , 
4, 0.147906, 0, 0, 0.503968,0.00245904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0487805,-0.0605953) , 
1, 0.406324, 0, 0, 0.491951,-0.00149718)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611055,0.00591184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438406,-0.004345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137457,-0.0277205) , 
3, 0.923576, 0, 0, 0.283951,-0.044433) , 
1, 0.614995, 0, 0, 0.492318,-0.00322065)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543324,0.00423204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.16,-0.0437346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108696,-0.0169908) , 
2, 41.1625, 0, 0, 0.126761,-0.072204) , 
3, 0.7557, 0, 0, 0.505161,0.00605492)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713249,0.012623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520833,-0.0368128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374233,-0.00583189) , 
4, 0.955149, 0, 0, 0.381092,-0.0248205) , 
8, 2.35362, 1, 0, 0.497146,-0.00311091)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.93617,0.0433092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739362,-0.0251841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439174,0.000596577) , 
7, -0.605743, 0, 0, 0.476923,-0.00646603) , 
8, 0.621908, 1, 0, 0.504091,-0.000186706)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530938,0.00134891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162791,-0.01051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0860215,-0.0481923) , 
3, 0.700818, 1, 0, 0.110294,-0.0882195) , 
3, 0.755443, 0, 0, 0.496034,-0.00322786)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.941176,0.0376357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512635,0.000328902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.176471,-0.0263525) , 
1, 0.471596, 0, 0, 0.482577,-0.00541059) , 
5, 1.40127, 0, 0, 0.506849,-0.000905277)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545134,0.00283055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170213,-0.046136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11828,-0.016369) , 
7, -3.42901, 0, 0, 0.135714,-0.077253) , 
3, 0.755478, 0, 0, 0.508344,0.0016055)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567261,0.00390415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488889,-0.0392027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213235,-0.010108) , 
5, 0.652986, 0, 0, 0.252366,-0.0443007) , 
0, 3.14286, 0, 0, 0.502901,0.00132815)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.967213,0.0501721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.870588,0.0234497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460714,-0.00146397) , 
8, 0.740599, 1, 0, 0.484175,-0.00112271) , 
5, 1.52665, 0, 0, 0.503234,0.00298596)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890625,0.0367272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502516,0.00183188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,-0.023097) , 
4, 0.155108, 0, 0, 0.482322,-0.00014262) , 
0, 6.28571, 0, 0, 0.49904,0.00394413)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556522,0.00527065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219178,-0.0349811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183673,0.00740777) , 
3, 0.939248, 0, 0, 0.19883,-0.0411474) , 
2, 29.4516, 0, 0, 0.517086,0.0105809)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.748718,0.0169533) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496291,-0.000696312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0722892,-0.03744) , 
3, 0.725302, 0, 0, 0.471698,-0.00662603) , 
2, 62.5979, 0, 0, 0.50492,0.000519335)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74269,0.0114713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520885,-0.0229739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392901,-0.000342201) , 
2, 41.6765, 0, 0, 0.435458,-0.0251438) , 
2, 54.0715, 0, 0, 0.502554,-0.0115575)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535131,0.00362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326531,0.0091125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119266,-0.0384411) , 
4, 0.341243, 0, 0, 0.183544,-0.0687309) , 
6, -3.24063, 0, 0, 0.499681,0.00373005)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512262,-0.00155564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414634,-0.0026491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0740741,-0.0534463) , 
6, -1.88185, 0, 0, 0.221053,-0.0983084) , 
4, 0.146123, 0, 0, 0.494562,-0.0106666)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551858,0.00206133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604167,0.0172454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232558,-0.0228799) , 
8, 1.85579, 1, 0, 0.283668,-0.0540261) , 
4, 0.236004, 0, 0, 0.49482,-0.00640136)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553759,-0.000103313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317568,-0.0303601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193548,-0.00292153) , 
4, 0.42863, 0, 0, 0.254125,-0.053613) , 
0, 3.14286, 0, 0, 0.494805,-0.0108205)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626582,0.00231717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373041,-0.015217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,0.0135437) , 
1, 0.513909, 0, 0, 0.346701,-0.0346518) , 
2, 40.1729, 0, 0, 0.488164,-0.0132867)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627586,0.00512213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348148,-0.0331106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214286,0.00200965) , 
6, -0.695725, 0, 0, 0.246847,-0.0250642) , 
3, 0.893022, 0, 0, 0.492994,0.00233447)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.815981,0.0214705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465817,0.00432612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199313,-0.0148706) , 
1, 0.541229, 0, 0, 0.398614,0.000888917) , 
7, -1.44018, 0, 0, 0.508615,0.0161137)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552851,0.0075707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190476,0.0115723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11236,-0.0327022) , 
3, 0.70084, 1, 0, 0.137405,-0.0468239) , 
3, 0.755443, 0, 0, 0.518164,0.0187132)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.921875,0.0338671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591133,-0.00971629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395327,0.00236745) , 
1, 0.74175, 0, 0, 0.449187,-0.00389429) , 
8, 0.818755, 1, 0, 0.486908,0.00234015)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722672,0.0127869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.9,0.0279791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36699,-0.00747196) , 
8, 0.739393, 1, 0, 0.39633,-0.0186784) , 
2, 47.5778, 0, 0, 0.498106,-8.94122e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783217,0.0208157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52987,-0.00311718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23511,-0.020257) , 
1, 0.536189, 0, 0, 0.466079,-0.0201137) , 
1, 0.842363, 0, 0, 0.494125,-0.0129045)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745614,0.0123265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508974,-0.0120279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237875,0.00658171) , 
5, -1.43262, 0, 0, 0.412201,-0.0201157) , 
0, 5.2381, 0, 0, 0.485531,-0.00748603)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531773,0.0025751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145455,-0.0492291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0555556,-0.0213768) , 
2, 48.6805, 0, 0, 0.100917,-0.111088) , 
6, -4.29812, 0, 0, 0.502494,5.85115e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797071,0.010858) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395459,-0.00251449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0909091,-0.0441343) , 
1, 0.426154, 0, 0, 0.37756,-0.0139984) , 
7, -1.57529, 0, 0, 0.502811,-0.000942542)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57554,0.00408672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309677,-0.0306481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157068,-0.00730932) , 
4, 0.466314, 0, 0, 0.225434,-0.0548025) , 
0, 3.14286, 0, 0, 0.499687,-0.00182448)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6816,0.00228893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712329,0.0166843) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315101,-0.0110928) , 
2, 65.6105, 0, 0, 0.346827,-0.0266302) , 
4, 0.588655, 0, 0, 0.482781,-0.0129666)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.798246,0.0222872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491946,0.000438837) , 
2, 71.3394, 0, 0, 0.513716,0.00614822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.047619,-0.0563705) , 
1, 0.401167, 0, 0, 0.501823,0.00283894)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53292,0.00341318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.286344,-0.0217773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,0.0128051) , 
8, 5.05645, 1, 0, 0.286232,-0.0502305) , 
4, 0.223025, 0, 0, 0.48947,-0.000206908)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582573,0.00519837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220532,-0.0153961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173077,0.0146345) , 
8, 3.59703, 0, 0, 0.212698,-0.0334075) , 
5, -2.23599, 0, 0, 0.505921,0.0058608)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.95,0.0439487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584737,0.000869454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238589,-0.0113614) , 
5, -1.67364, 0, 0, 0.472837,-0.00881189) , 
8, 0.277279, 1, 0, 0.491296,-0.00538654)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.631155,0.00721205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35,-0.0446146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235294,-0.0011986) , 
8, 1.36796, 1, 0, 0.245161,-0.0162598) , 
3, 0.877762, 0, 0, 0.517699,0.0115094)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57744,0.00238743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454545,-0.0239726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229462,-0.00728215) , 
2, 55.5442, 0, 0, 0.28692,-0.039442) , 
7, -6.22559, 0, 0, 0.490886,-0.00660325)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527697,-0.00234764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289474,0.0343968) , 
3, 0.764977, 0, 0, 0.515193,-0.00279884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0789474,-0.0396157) , 
3, 0.724874, 0, 0, 0.493438,-0.00664949)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612903,0.00734375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37963,0.0162784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295405,-0.0147633) , 
8, 5.87142, 0, 0, 0.311504,-0.0279103) , 
7, -5.5201, 0, 0, 0.505668,0.00439831)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576441,0.00526671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362637,-0.0231765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152284,0.00231881) , 
6, -1.20394, 0, 0, 0.253298,-0.0348606) , 
1, 0.556804, 0, 0, 0.498731,0.00440007)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572774,0.00493876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35567,-0.00321654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106061,-0.0404239) , 
5, -3.7425, 0, 0, 0.319383,-0.0241483) , 
4, 0.26873, 0, 0, 0.50185,0.00412419)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55296,0.00267744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247525,-0.00543472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769231,-0.0596805) , 
7, -6.96152, 1, 0, 0.212598,-0.0415848) , 
5, -2.50845, 0, 0, 0.496749,2.53353e-05)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575758,-0.00445117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404612,0.0159686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211538,-0.0205487) , 
4, 0.14448, 0, 0, 0.370052,0.0288867) , 
4, 0.314433, 0, 0, 0.504192,0.00121751)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756906,0.0123697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36215,0.00544653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352846,-0.00975488) , 
8, 4.40279, 0, 0, 0.356663,-0.0108381) , 
7, -2.10573, 0, 0, 0.493695,0.0049398)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571293,-0.00398863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492126,0.0275947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267361,0.000868077) , 
0, 3.04762, 0, 0, 0.372694,0.0399475) , 
2, 35.4524, 0, 0, 0.503764,0.00518128)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.809816,0.0220179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592058,-0.00347368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418293,0.0103801) , 
1, 0.686157, 0, 0, 0.488355,0.0138438) , 
1, 0.838255, 0, 0, 0.522446,0.0190362)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572917,0.0069751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403226,0.00170178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137755,-0.0273367) , 
3, 0.954286, 0, 0, 0.240625,-0.0366408) , 
0, 3.14286, 0, 0, 0.505102,0.0100354)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.971429,0.0498685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497462,-0.00128221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368794,0.0193217) , 
4, 0.177324, 0, 0, 0.485526,0.00188022) , 
5, 1.4449, 0, 0, 0.506918,0.00553257)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586689,0.00184187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236364,-0.0479507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207792,-0.00840081) , 
1, 0.76377, 0, 0, 0.212121,-0.0480496) , 
6, -2.19473, 0, 0, 0.500633,-0.00671302)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64751,0.0012451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496124,-0.0185587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212389,-0.0029063) , 
6, -0.960483, 0, 0, 0.343266,-0.0332286) , 
1, 0.676903, 0, 0, 0.490136,-0.0152908)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614181,0.00506188) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393939,-0.0127848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143617,0.0147592) , 
5, -1.40065, 0, 0, 0.313356,-0.0204728) , 
2, 36.763, 0, 0, 0.500324,0.0021839)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657929,0.00548365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511628,-0.0357273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318801,-0.00307993) , 
8, 1.5308, 1, 0, 0.339024,-0.0192571) , 
3, 0.938861, 0, 0, 0.492735,-0.00161907)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533961,0.00235216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,0.00276225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0588235,-0.0533436) , 
2, 29.1982, 0, 0, 0.126214,-0.0512877) , 
0, 2.09524, 0, 0, 0.507547,0.00346094)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543847,-0.00105371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0852713,-0.0367981) , 
3, 0.755524, 0, 0, 0.504038,-0.00933927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378788,0.0244657) , 
8, 6.02803, 1, 0, 0.498711,-0.00574219)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510944,0.00308821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0317893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212766,0.0257412) , 
3, 0.867674, 0, 0, 0.234783,-0.0492708) , 
7, -10.3098, 0, 0, 0.490805,0.00497376)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535714,0.0369015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507163,-0.00361077) , 
8, 5.9089, 0, 0, 0.508264,-0.00522638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105263,-0.0374654) , 
6, -4.57701, 0, 0, 0.48822,-0.00992235)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806452,0.0163196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.698718,-0.0167732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391829,0.000320839) , 
8, 1.81774, 1, 0, 0.460763,-0.00892783) , 
1, 0.836769, 0, 0, 0.495466,-0.00362119)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530626,0.00166675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139535,-0.0495508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0714286,-0.0145572) , 
5, -0.371217, 0, 0, 0.0973451,-0.0825396) , 
0, 2.14286, 0, 0, 0.50031,-0.000969481)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577555,0.00810707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,-0.0271958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352423,0.00221018) , 
7, -5.50637, 0, 0, 0.360294,-0.00970363) , 
8, 3.87168, 1, 0, 0.505488,0.0126356)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520734,0.00506364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317073,-0.0151696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0487805,-0.0574133) , 
3, 0.878498, 0, 0, 0.182927,-0.104208) , 
4, 0.146122, 0, 0, 0.502898,0.00901079)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.987805,0.0482956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535088,-0.0022848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238606,-0.0166773) , 
2, 32.8592, 0, 0, 0.461996,-0.0165236) , 
7, 0.786429, 0, 0, 0.489028,-0.0123435)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790698,0.0334397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54109,0.00219667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299652,-0.0134772) , 
4, 0.223028, 0, 0, 0.495383,-0.00256761) , 
2, 86.7606, 0, 0, 0.503528,0.000595483)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747549,-0.011251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0217238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387678,0.0032919) , 
1, 0.842682, 0, 0, 0.416811,0.0158128) , 
7, -1.33882, 0, 0, 0.503201,0.00440977)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707965,-0.0291805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512281,0.00306656) , 
4, 0.955056, 0, 0, 0.526658,0.00332645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.106061,-0.0395129) , 
5, -5.19852, 0, 0, 0.509352,-0.00129364)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516293,-0.0044941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32,0.031475) , 
5, -3.47827, 0, 0, 0.506181,-0.00839528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0306548) , 
5, -4.97562, 0, 0, 0.487932,-0.0123559)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694444,-0.0206382) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558606,0.00501213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228856,-0.0113148) , 
1, 0.583427, 0, 0, 0.460341,0.00257017) , 
4, 0.908588, 0, 0, 0.497189,-0.00673049)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541879,-0.000556805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186992,-0.0364632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0985916,0.00841541) , 
2, 41.0406, 0, 0, 0.154639,-0.0785131) , 
6, -2.96012, 0, 0, 0.493937,-0.0112108)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609977,-0.0139313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689498,-0.0136193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37797,0.00539078) , 
4, 0.802578, 0, 0, 0.437555,0.00523362) , 
3, 0.984717, 0, 0, 0.485498,-0.00823414)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.935185,0.0324056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505873,-0.00265707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266376,0.0189106) , 
1, 0.509331, 0, 0, 0.469456,-0.00020234) , 
5, 1.29028, 0, 0, 0.50062,0.00399088)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567589,0.0064296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638298,0.0189639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228782,-0.0163253) , 
8, 1.85579, 1, 0, 0.289308,-0.0303811) , 
4, 0.223026, 0, 0, 0.511687,0.00938782)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491402,-0.00296791) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463415,0.00811486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,0.0555735) , 
2, 48.071, 0, 0, 0.419753,0.0842963) , 
8, 6.02025, 1, 0, 0.487759,-0.00417484)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772,-0.0016366) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715517,0.0277978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348279,0.00546684) , 
7, -1.43228, 0, 0, 0.387907,0.0258487) , 
5, -0.120227, 0, 0, 0.509841,0.0163092)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544828,-0.00318291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567686,0.016994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182292,-0.00935433) , 
3, 0.908426, 0, 0, 0.391924,0.0248395) , 
8, 4.38517, 1, 0, 0.504111,-0.000174197)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649123,0.0048822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378336,-0.0101981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188406,0.015691) , 
1, 0.510663, 0, 0, 0.344516,-0.0198419) , 
3, 0.93887, 0, 0, 0.499046,-0.00197479)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688722,0.0123378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501548,-0.0111604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352941,0.00865592) , 
1, 0.693765, 0, 0, 0.406215,0.0022217) , 
8, 2.6101, 1, 0, 0.526181,0.0158779)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.872881,0.0153173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511667,-0.0107587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348506,0.000144696) , 
4, 0.415762, 0, 0, 0.423638,-0.0163457) , 
5, 0.70765, 0, 0, 0.492528,-0.00859245)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548109,0.00250977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130435,-0.0408849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101695,0.0108316) , 
5, -0.710789, 0, 0, 0.114286,-0.0483525) , 
0, 2.14286, 0, 0, 0.519851,0.00406112)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,-0.00264351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357027,0.0146622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,-0.0214593) , 
7, -10.8738, 0, 0, 0.333333,0.0284129) , 
6, -1.03563, 0, 0, 0.51068,0.00911193)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53136,-0.000932499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0417989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.08,-0.0200415) , 
1, 0.696414, 0, 0, 0.111111,-0.0620335) , 
3, 0.755478, 0, 0, 0.492642,-0.00830922)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528827,0.00114891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341463,0.0449576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217391,0.0164222) , 
4, 0.280581, 0, 0, 0.275862,0.0785393) , 
5, -4.60738, 0, 0, 0.515038,0.00756352)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546726,-0.0018736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144231,-0.0356903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.107843,-0.00212965) , 
2, 37.4053, 0, 0, 0.126214,-0.0517864) , 
3, 0.786083, 0, 0, 0.491374,-0.0118991)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660377,0.00553053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332402,-0.00794956) , 
1, 0.650621, 0, 0, 0.504964,-0.00202687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37037,0.0408513) , 
7, -11.8038, 0, 0, 0.500319,0.00238538)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507565,-0.00462039) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446154,0.0294748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117647,0.00448864) , 
3, 0.893119, 0, 0, 0.278196,0.0580634) , 
5, -3.85349, 0, 0, 0.488343,-0.00772247)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498636,0.000852788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607143,0.0421874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268293,-0.00242318) , 
5, -4.6862, 0, 0, 0.463918,0.0807057) , 
8, 5.93496, 1, 0, 0.496481,0.00737349)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64219,0.000732242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380893,-0.00816032) , 
8, 2.80792, 1, 0, 0.506752,-0.0127068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295455,0.025011) , 
7, -12.5732, 0, 0, 0.500938,-0.0103577)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517556,-0.00211495) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360656,-0.00724239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324561,0.0323549) , 
5, -3.23917, 0, 0, 0.337143,0.0496781) , 
7, -9.63723, 0, 0, 0.497811,-0.000238233)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666163,0.00775369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56,-0.0190548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353383,-0.00169156) , 
4, 0.910115, 0, 0, 0.376392,-0.0120057) , 
8, 2.6101, 1, 0, 0.499359,0.0023245)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610568,-0.00190212) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44335,-0.00578769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248503,0.0282326) , 
2, 47.7048, 0, 0, 0.32216,0.0341703) , 
5, -1.40867, 0, 0, 0.511225,0.00798938)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625131,0.00650457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481132,-0.0311158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282908,-0.00576927) , 
6, -0.783254, 0, 0, 0.317073,-0.0333998) , 
7, -4.7801, 0, 0, 0.504459,-0.00143352)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735376,0.0067014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550725,-0.0211511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426618,-0.00354275) , 
2, 60.7384, 0, 0, 0.433962,-0.0139299) , 
0, 5.2381, 0, 0, 0.504918,-0.00618238)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707783,0.00955827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512048,-0.0208733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316947,-0.00398531) , 
2, 55.0784, 0, 0, 0.351438,-0.0228172) , 
4, 0.550584, 0, 0, 0.501235,-0.00154313)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739726,-0.00670946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507874,-0.000697872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305606,0.0151478) , 
3, 0.923587, 0, 0, 0.402451,0.0208085) , 
7, -1.83701, 0, 0, 0.512087,0.00843957)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704846,-0.02038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516355,-0.00132806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359918,0.0107397) , 
4, 0.288241, 0, 0, 0.45948,0.00879994) , 
4, 0.90858, 0, 0, 0.494911,-0.000104238)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.962963,0.0353164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541379,-0.00708673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283154,0.00422273) , 
3, 0.893007, 0, 0, 0.440476,-0.0100643) , 
7, 0.461152, 0, 0, 0.477214,-0.00562558)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573071,0.0064101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291667,-0.0125021) , 
4, 0.223028, 0, 0, 0.519256,0.00841101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119403,-0.0393191) , 
1, 0.43413, 0, 0, 0.502225,0.00395947)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.803738,0.0271592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515306,-0.00126096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.249027,-0.0150643) , 
7, -8.27457, 0, 0, 0.467551,-0.0115819) , 
2, 70.0974, 0, 0, 0.490909,-0.00526939)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.657084,-0.00900675) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715328,0.0184075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378821,-0.000644992) , 
4, 0.909733, 0, 0, 0.422602,0.00570374) , 
1, 0.739959, 0, 0, 0.496753,-0.00467957)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780488,0.0334487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659292,-0.014063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462025,0.00054215) , 
2, 57.8882, 0, 0, 0.491946,-0.00509725) , 
2, 82.6161, 0, 0, 0.499673,-0.00247627)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775726,0.0111636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,-0.0118841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337156,-0.000432089) , 
4, 0.730915, 0, 0, 0.409318,-0.0121717) , 
8, 1.842, 1, 0, 0.497154,-0.00271769)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884,0.0178484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617857,-0.0145202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363977,-0.00182124) , 
0, 5.2381, 0, 0, 0.41679,-0.014235) , 
5, 0.731507, 0, 0, 0.489975,-0.00642055)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529136,0.00524844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555556,0.0143807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,-0.0241114) , 
1, 0.688923, 0, 0, 0.333333,-0.0353223) , 
8, 5.59527, 1, 0, 0.512899,0.0114728)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765432,0.0178903) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752809,-0.012229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.406277,0.00221324) , 
8, 1.59383, 1, 0, 0.471711,0.000322318) , 
2, 65.5281, 0, 0, 0.501904,0.0053117)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.974684,0.0525166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64375,0.00667779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399414,-0.00470625) , 
3, 0.96943, 0, 0, 0.477394,-0.0027824) , 
5, 1.40127, 0, 0, 0.502211,0.00134235)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64,0.00485199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353846,-0.0383314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245174,-0.00122278) , 
8, 1.6225, 1, 0, 0.25729,-0.01654) , 
3, 0.893007, 0, 0, 0.501244,0.00365334)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736334,0.00990716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50243,-0.00642782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214559,0.0121628) , 
3, 0.832044, 0, 0, 0.444186,-0.0107931) , 
2, 55.0984, 0, 0, 0.500937,-0.00311768)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627854,-0.00884267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635897,0.0143768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331476,-0.00121658) , 
1, 0.711503, 0, 0, 0.438628,0.014284) , 
3, 0.984715, 0, 0, 0.492238,0.00257434)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680751,-0.0212674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710526,0.0168068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393301,-0.00289826) , 
1, 0.764064, 0, 0, 0.464789,0.00511359) , 
4, 0.909742, 0, 0, 0.494238,-0.00344108)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.830769,0.0228962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616883,-0.0252589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445398,-0.000466618) , 
2, 62.4881, 0, 0, 0.463788,-0.00916124) , 
1, 0.842682, 0, 0, 0.494253,-0.00333317)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735027,0.00663888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376663,-0.00438339) , 
4, 0.680068, 0, 0, 0.50589,-0.00170338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116279,-0.0368584) , 
7, -12.4468, 0, 0, 0.495226,-0.00461143)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692913,-0.0136143) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654206,-0.0263592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357294,0.00459263) , 
5, 0.160361, 0, 0, 0.387464,0.00516834) , 
4, 0.725765, 0, 0, 0.486867,-0.00915362)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564453,-0.0024276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654545,0.0263727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243968,0.000510945) , 
6, -1.14076, 0, 0, 0.369888,0.0272045) , 
4, 0.314436, 0, 0, 0.497439,0.00461836)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586066,0.000836641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215548,-0.0201505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.134831,0.0183365) , 
1, 0.540437, 0, 0, 0.196237,-0.0367495) , 
3, 0.847152, 0, 0, 0.494975,-0.00657505)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.745205,0.012252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491206,-0.00742568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322581,0.00646154) , 
7, -5.92449, 0, 0, 0.431707,-0.00765085) , 
1, 0.775711, 0, 0, 0.503448,0.0023173)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605991,-0.0129261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697674,0.014887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375736,-0.000830461) , 
3, 0.955524, 0, 0, 0.450768,0.00859471) , 
3, 0.98472, 0, 0, 0.494484,-0.00520499)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
