// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Tue Oct 14 16:05:53 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 5110
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "5110" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
numJets_40                    numJets_40                    numJets_40                    numJets_40                                                      'F'    [0,5]
MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_D_mass_of_leps_jets MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_mass_of_leps_jets                                           'F'    [0.26757144928,0.974646389484]
jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt                                                 'F'    [25.0017337799,138.676849365]
jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex                                         'F'    [0.679145395756,1]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0295466762036,0.999993860722]
Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq                                           'F'    [-13.6145925522,2.47275948524]
Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq                                           'F'    [-13.8269929886,2.38039278984]
FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31                                        'F'    [-0.991502642632,0.998721122742]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numJets_40", "MT_of_leps_jets_mass_of_leps_jets", "jets_by_pt_5_pt", "jets_by_CSV_1_btagCombinedSecVertex", "jets_by_CSV_2_btagCombinedSecVertex", "Match_ttbar_jj_Bq_bqq", "Match_ttbar_jj_Bqq_bq", "FinalBDT_ttZ_vs_ttbar_OS_Oct31" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 5;
      fVmin[1] = 0.267571449279785;
      fVmax[1] = 0.974646389484406;
      fVmin[2] = 25.0017337799072;
      fVmax[2] = 138.676849365234;
      fVmin[3] = 0.679145395755768;
      fVmax[3] = 1;
      fVmin[4] = 0.0295466762036085;
      fVmax[4] = 0.999993860721588;
      fVmin[5] = -13.6145925521851;
      fVmax[5] = 2.47275948524475;
      fVmin[6] = -13.8269929885864;
      fVmax[6] = 2.3803927898407;
      fVmin[7] = -0.991502642631531;
      fVmax[7] = 0.998721122741699;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686448,0.0372896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452459,-0.0095082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217842,-0.0564315) , 
1, 0.595076, 0, 0, 0.37151,-0.12849) , 
7, 0.5247, 0, 0, 0.512272,0.0122724)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66378,0.0310401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505447,0.00272042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279955,-0.0430376) , 
4, 0.676503, 0, 0, 0.356509,-0.137286) , 
1, 0.709728, 0, 0, 0.505339,0.00432079)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689312,0.0333403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448763,-0.00793704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242623,-0.048202) , 
7, -0.482207, 0, 0, 0.362577,-0.123456) , 
7, 0.526047, 0, 0, 0.503316,0.00130181)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726264,0.039283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570328,0.0138867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326907,-0.0313877) , 
5, -1.36877, 0, 0, 0.400701,-0.0876879) , 
1, 0.775958, 0, 0, 0.505351,0.00323464)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648515,0.0236909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41129,-0.0152584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206478,-0.0464573) , 
1, 0.623124, 0, 0, 0.320467,-0.143362) , 
7, 0.145692, 0, 0, 0.503956,0.00242857)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692732,0.027805) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.384276,-0.0160121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200704,-0.0517487) , 
0, 2.14286, 0, 0, 0.347458,-0.114224) , 
7, 0.524659, 0, 0, 0.497403,-0.00518772)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60262,0.0154869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.347345,-0.0180654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145907,-0.0606714) , 
3, 0.908342, 0, 0, 0.270123,-0.166761) , 
1, 0.60659, 0, 0, 0.507602,0.00671572)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654786,0.0247555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471154,-0.00535449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254687,-0.0418173) , 
0, 3.09524, 0, 0, 0.383249,-0.0979774) , 
5, -1.55882, 0, 0, 0.48749,-0.0139121)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622706,0.0200814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440874,-0.00986474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188406,-0.0523706) , 
0, 2.14286, 0, 0, 0.363313,-0.11072) , 
0, 3.09524, 0, 0, 0.510409,0.00750864)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694169,0.0300339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612546,0.0198386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331304,-0.0272042) , 
2, 35.8294, 0, 0, 0.421395,-0.0582741) , 
5, -1.30096, 0, 0, 0.516724,0.0129945)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612306,0.0140506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331811,-0.0208207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.108491,-0.0638174) , 
3, 0.862516, 0, 0, 0.27733,-0.148595) , 
1, 0.633771, 0, 0, 0.497837,-0.00591672)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725849,0.0285774) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477273,-0.000220548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290276,-0.0332998) , 
4, 0.363304, 0, 0, 0.406983,-0.0603238) , 
7, 0.809192, 0, 0, 0.500962,-0.00227727)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610264,0.0154978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546448,0.00684388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264276,-0.0345793) , 
6, -1.18447, 0, 0, 0.356568,-0.0985354) , 
0, 3.09524, 0, 0, 0.499414,-0.00126925)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689143,0.0276292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567619,0.0075813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319741,-0.0254163) , 
2, 35.8294, 0, 0, 0.400873,-0.0686407) , 
6, -1.45545, 0, 0, 0.502622,0.00201457)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664134,0.0190747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392094,-0.0111367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209677,-0.0399713) , 
3, 0.877792, 0, 0, 0.346709,-0.0850922) , 
1, 0.705285, 0, 0, 0.509758,0.00519602)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625644,0.0136493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355828,-0.0152568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229426,-0.0336402) , 
7, -0.693892, 0, 0, 0.307692,-0.103425) , 
7, 0.0509955, 0, 0, 0.497121,-0.00343304)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607595,0.0116108) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553846,0.0121543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219697,-0.0334793) , 
5, -0.391737, 0, 0, 0.249655,-0.131712) , 
1, 0.610023, 0, 0, 0.505507,0.00171503)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679632,0.0223677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471523,0.00215493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332938,-0.026698) , 
4, 0.402798, 0, 0, 0.398374,-0.060279) , 
6, -1.60897, 0, 0, 0.505047,0.0020559)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627422,0.0150364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414573,-0.00752794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24812,-0.0381405) , 
3, 0.893066, 0, 0, 0.358996,-0.0807907) , 
6, -2.37222, 0, 0, 0.500985,-0.00124397)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729314,0.0239587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438724,-0.00373682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220544,-0.0346938) , 
0, 2.14286, 0, 0, 0.396491,-0.0436903) , 
7, 0.714612, 0, 0, 0.506651,0.00693265)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616758,0.0129501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454,-0.00287622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272277,-0.0315234) , 
3, 0.954171, 0, 0, 0.35443,-0.0825574) , 
0, 3.09524, 0, 0, 0.503513,-0.0017579)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632128,0.0106812) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48495,0.00262298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268464,-0.0251547) , 
2, 35.5077, 0, 0, 0.324653,-0.0788766) , 
1, 0.676613, 0, 0, 0.495367,-0.00763805)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807107,0.0379863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624079,0.0116835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358611,-0.0152495) , 
6, -1.63242, 0, 0, 0.45573,-0.0241558) , 
1, 0.84232, 0, 0, 0.508591,0.00494981)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546029,0.00457318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229167,-0.0321156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0649351,-0.062527) , 
0, 1.04762, 0, 0, 0.194521,-0.164067) , 
0, 2.14286, 0, 0, 0.496319,-0.00533968)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736127,0.0218206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447392,-0.00398326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250435,-0.026253) , 
7, -0.504218, 0, 0, 0.379496,-0.0516083) , 
7, 0.714179, 0, 0, 0.50294,-0.000401347)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67284,0.0140426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412722,-0.00116149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250809,-0.0257796) , 
2, 29.2587, 0, 0, 0.335394,-0.0558045) , 
7, 0.335313, 0, 0, 0.504247,0.00351403)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634364,0.0139835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454774,0.00069076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28777,-0.0264798) , 
2, 29.0922, 0, 0, 0.348582,-0.0717378) , 
0, 3.09524, 0, 0, 0.511774,0.00501133)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587644,0.00791619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269231,-0.0192844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0584795,-0.059369) , 
3, 0.877798, 0, 0, 0.201869,-0.127527) , 
1, 0.570279, 0, 0, 0.505938,0.00107193)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59931,0.00610949) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587629,0.00844274) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283499,-0.0242984) , 
5, -0.438219, 0, 0, 0.337283,-0.0782076) , 
0, 3.09524, 0, 0, 0.486455,-0.0182008)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534007,0.00453565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435644,-0.00749048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203187,-0.0499143) , 
4, 0.435261, 0, 0, 0.269886,-0.157992) , 
3, 0.816688, 0, 0, 0.497231,-0.00479758)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555156,0.00846668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614679,0.00914596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313972,-0.0246915) , 
5, -1.53907, 0, 0, 0.390643,-0.0685684) , 
4, 0.310928, 0, 0, 0.499405,0.00134606)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.735294,0.0200372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470678,-0.000389337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311499,-0.0261951) , 
4, 0.306816, 0, 0, 0.416,-0.0400133) , 
1, 0.808495, 0, 0, 0.490812,-0.0105806)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670199,0.0173069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526219,0.00112334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273684,-0.0206993) , 
6, -2.65103, 0, 0, 0.430365,-0.0297496) , 
2, 35.8279, 0, 0, 0.502593,0.0023102)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.780269,0.0265947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499328,0.00262056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320433,-0.022223) , 
3, 0.893066, 0, 0, 0.445173,-0.0200282) , 
1, 0.834534, 0, 0, 0.503101,0.00256365)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654836,0.0113009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389635,-0.00436413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250871,-0.0207338) , 
7, -0.499812, 0, 0, 0.316895,-0.054232) , 
7, 0.148113, 0, 0, 0.508689,0.00417664)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559267,0.00675235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483806,-0.000773406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279208,-0.0329098) , 
3, 0.92362, 0, 0, 0.38038,-0.070106) , 
4, 0.356862, 0, 0, 0.488519,-0.0101142)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584242,0.00734598) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379494,-0.0074248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252941,-0.039201) , 
4, 0.173113, 0, 0, 0.356135,-0.0573794) , 
5, -3.05092, 0, 0, 0.502528,-0.000367985)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602864,0.0112646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728261,0.0208398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347235,-0.0158772) , 
1, 0.860303, 0, 0, 0.376569,-0.0546507) , 
2, 30.4177, 0, 0, 0.495638,-0.000423063)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640061,0.0131003) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393805,-0.0044036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267062,-0.0310341) , 
4, 0.214391, 0, 0, 0.359388,-0.0480976) , 
5, -2.12363, 0, 0, 0.503145,0.00516895)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67624,0.0149815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47711,-0.0038425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207386,-0.0284197) , 
0, 2.09524, 0, 0, 0.422857,-0.0353542) , 
2, 35.8279, 0, 0, 0.5,-0.00502848)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754639,0.0192588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459923,-0.00319839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0328929) , 
7, -0.811043, 0, 0, 0.425573,-0.0271976) , 
7, 0.903699, 0, 0, 0.488556,-0.00714717)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655145,0.00824997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366063,-0.00767783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138614,-0.036446) , 
1, 0.47574, 0, 0, 0.329337,-0.0483881) , 
1, 0.704816, 0, 0, 0.493661,-0.00624237)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664286,0.00858845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55814,0.017249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303136,-0.0139317) , 
2, 46.2877, 0, 0, 0.320908,-0.0477231) , 
7, 0.33537, 0, 0, 0.494387,-0.00541638)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589235,0.0113273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.70297,0.0223261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36444,-0.0134658) , 
5, -0.649315, 0, 0, 0.394996,-0.0417399) , 
4, 0.399241, 0, 0, 0.503358,0.00809813)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625,0.0100408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435216,0.000876516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29097,-0.0190359) , 
4, 0.362129, 0, 0, 0.363333,-0.0358195) , 
6, -2.46414, 0, 0, 0.504231,0.00591599)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.865,0.0392852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563218,0.0049626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347945,-0.0155856) , 
2, 30.2563, 0, 0, 0.461306,-0.018786) , 
1, 0.875302, 0, 0, 0.493434,-0.00566647)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551209,0.00549312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534247,0.00659137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282851,-0.0290626) , 
4, 0.515337, 0, 0, 0.344538,-0.0785679) , 
3, 0.87777, 0, 0, 0.502758,-0.000875078)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.746537,0.0152264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426554,-0.00277774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0932203,-0.0410814) , 
1, 0.442173, 0, 0, 0.40572,-0.0193325) , 
7, 0.809176, 0, 0, 0.5,0.00240701)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683236,0.0136201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478261,0.00367176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329154,-0.015194) , 
4, 0.491658, 0, 0, 0.387833,-0.0306451) , 
6, -1.63242, 0, 0, 0.504224,0.00319303)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528534,0.00310325) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523077,0.00674965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189474,-0.039789) , 
4, 0.468912, 0, 0, 0.27451,-0.103223) , 
3, 0.786097, 0, 0, 0.502961,0.00108275)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743506,0.0256841) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488406,-0.00169943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0350899) , 
3, 0.770818, 0, 0, 0.462418,-0.0174841) , 
2, 46.0137, 0, 0, 0.495935,-0.00288882)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625372,0.00902322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302839,-0.0241225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293135,-0.00436632) , 
6, -2.21035, 0, 0, 0.296729,-0.049652) , 
7, -0.138603, 0, 0, 0.514398,0.00765349)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55023,0.00351339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231405,-0.0102992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179688,-0.0401904) , 
6, -2.14203, 1, 0, 0.213514,-0.0828321) , 
7, -0.705018, 0, 0, 0.501181,0.000147405)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770138,0.017972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594702,0.00398497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337255,-0.0103376) , 
6, -1.63242, 0, 0, 0.433005,-0.0199168) , 
7, 0.903957, 0, 0, 0.500591,-0.00234719)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723711,0.0197281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500891,-0.00168929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210243,-0.0223266) , 
0, 2.09524, 0, 0, 0.448393,-0.0201385) , 
0, 4.04762, 0, 0, 0.500985,-0.0011342)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55795,0.00378543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590028,3.05964e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231102,-0.0218971) , 
1, 0.718508, 0, 0, 0.38835,-0.0447933) , 
3, 0.908342, 0, 0, 0.502952,-0.00407978)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762911,0.0199988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560998,0.00207662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331693,-0.0116919) , 
2, 30.4148, 0, 0, 0.449952,-0.017723) , 
5, -0.355053, 0, 0, 0.502773,-0.00177008)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.759443,0.0145918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453933,-0.000306404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302682,-0.019932) , 
6, -6.35433, 0, 0, 0.434591,-0.0113192) , 
7, 0.903957, 0, 0, 0.498821,0.00166243)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565836,0.00636727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411141,-0.00643593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186441,-0.0497947) , 
5, -7.77622, 0, 0, 0.394834,-0.038055) , 
3, 0.908327, 0, 0, 0.510204,0.00502707)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55647,0.00319321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199203,-0.0121538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196581,-0.0411939) , 
4, 0.636458, 1, 0, 0.19837,-0.0802542) , 
0, 2.14286, 0, 0, 0.504892,-0.00054124)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569436,0.00724788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469835,-0.0152272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276786,0.00696147) , 
7, 0.14869, 0, 0, 0.396376,-0.0300739) , 
3, 0.908349, 0, 0, 0.510753,0.00912814)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670466,0.00829538) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740385,0.0144995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354037,-0.010336) , 
1, 0.86965, 0, 0, 0.37991,-0.0349014) , 
6, -1.60857, 0, 0, 0.491263,-0.00922443)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57931,0.00892959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459514,-0.0183984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288089,0.00573924) , 
7, 0.339852, 0, 0, 0.387134,-0.0369256) , 
4, 0.310928, 0, 0, 0.512245,0.0101592)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561075,0.00382661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527586,0.00574387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290741,-0.0211757) , 
4, 0.454691, 0, 0, 0.373494,-0.0431217) , 
3, 0.908344, 0, 0, 0.499803,-0.00375733)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542396,0.000718783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193431,-0.0175443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16092,-0.0446173) , 
5, -1.69599, 1, 0, 0.185596,-0.0913573) , 
7, -0.707222, 0, 0, 0.492664,-0.0102713)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608098,0.00705747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434434,-0.00410404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140351,-0.0274639) , 
7, -0.707236, 0, 0, 0.379788,-0.0299431) , 
2, 30.4177, 0, 0, 0.500766,0.000846828)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614224,0.00653184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524631,0.000150567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285891,-0.0182336) , 
0, 3.04762, 0, 0, 0.365733,-0.0454538) , 
2, 30.4148, 0, 0, 0.498465,-0.00729048)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59922,0.00519907) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544776,0.0148006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19702,-0.0184647) , 
5, -1.01355, 0, 0, 0.260163,-0.0402964) , 
1, 0.610748, 0, 0, 0.500395,0.00305866)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688889,0.0129389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477945,-0.000698202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24,-0.024734) , 
6, -6.2449, 0, 0, 0.455571,-0.0111904) , 
2, 41.241, 0, 0, 0.496314,-0.000411032)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578711,0.00434295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263514,-0.0257999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242353,-0.00639723) , 
5, -1.68154, 0, 0, 0.247818,-0.0450426) , 
7, -0.515742, 0, 0, 0.50505,0.00320004)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603914,0.00623747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542373,0.0179155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345972,-0.0100739) , 
6, -2.07192, 0, 0, 0.356373,-0.033057) , 
5, -2.52308, 0, 0, 0.497689,-0.000454858)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598201,0.00407676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388393,-0.00512184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139241,-0.0385937) , 
6, -6.56637, 0, 0, 0.371977,-0.0266969) , 
2, 30.4148, 0, 0, 0.491117,-0.00420493)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649452,0.00307517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402174,-0.0222987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306985,-0.00816543) , 
2, 42.0309, 0, 0, 0.320755,-0.0400857) , 
1, 0.709728, 0, 0, 0.48549,-0.0139206)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529462,0.00151653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.119718,-0.0399735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109375,-0.0187869) , 
7, -0.797875, 0, 0, 0.116505,-0.104754) , 
1, 0.469593, 0, 0, 0.496075,-0.00302615)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54007,0.00278722) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.22093,-0.00439895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145833,-0.0343582) , 
5, -2.1993, 1, 0, 0.19403,-0.0538328) , 
7, -0.79963, 0, 0, 0.5039,0.00405964)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613514,0.00491633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376078,-0.00476687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.148148,-0.03316) , 
3, 0.816684, 0, 0, 0.337511,-0.0325045) , 
0, 3.09524, 0, 0, 0.494802,-0.0030243)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.769231,0.0280344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588421,0.00869233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411157,-0.00598058) , 
4, 0.634199, 0, 0, 0.481266,-0.000121472) , 
2, 51.269, 0, 0, 0.501548,0.0073865)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793522,0.018295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502695,0.00311505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295848,-0.0127754) , 
6, -4.02069, 0, 0, 0.444714,-0.00460808) , 
7, 0.903707, 0, 0, 0.512128,0.00848426)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519567,0.00104717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133333,-0.0100883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.09375,-0.04984) , 
7, -0.324778, 1, 0, 0.115108,-0.0899934) , 
1, 0.445339, 0, 0, 0.497442,-0.00112214)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789062,0.0189727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447301,-0.000527946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440415,-0.0207804) , 
4, 0.953777, 1, 0, 0.446679,-0.00941406) , 
1, 0.839965, 0, 0, 0.49881,0.00200227)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68872,0.0100177) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414704,-0.0012186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321033,-0.0155245) , 
4, 0.16818, 0, 0, 0.399522,-0.0134925) , 
6, -1.47851, 0, 0, 0.502313,0.00447496)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492164,-0.000442736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507353,-0.0372149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377778,-0.00807128) , 
6, -2.709, 0, 0, 0.455752,-0.0971242) , 
4, 0.953769, 1, 0, 0.488983,-0.0100063)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547354,0.0018482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212828,-0.00778458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0536092) , 
5, -0.143209, 1, 0, 0.211488,-0.0464779) , 
0, 2.14286, 0, 0, 0.49848,-0.000706898)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625255,0.0100553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506024,0.0199045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345703,-0.00596364) , 
4, 0.953769, 0, 0, 0.357724,-0.014408) , 
5, -2.53038, 0, 0, 0.510465,0.0154745)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601549,0.00524347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431418,-0.00443898) , 
4, 0.537876, 0, 0, 0.511553,0.000627178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0897436,-0.0374979) , 
0, 1.19048, 0, 0, 0.498625,-0.00261058)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555407,0.00265531) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219124,-0.00797012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16,-0.0364019) , 
2, 28.4696, 1, 0, 0.202279,-0.0513896) , 
0, 2.14286, 0, 0, 0.507698,0.00183908)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554795,0.00536391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539519,0.00655857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264706,-0.015226) , 
2, 32.0699, 0, 0, 0.373806,-0.0198039) , 
3, 0.893048, 0, 0, 0.501408,0.00867024)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548988,0.00268823) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410811,-0.0204002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228814,0.00619723) , 
7, 0.159149, 0, 0, 0.339934,-0.0416258) , 
3, 0.877792, 0, 0, 0.497987,-0.00231324)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540747,0.00305962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234043,-0.00372973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0408163,-0.0470412) , 
2, 30.3287, 0, 0, 0.135417,-0.0641427) , 
1, 0.469376, 0, 0, 0.510204,0.00599938)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514097,-0.000828558) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37037,-0.0105261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0525297) , 
4, 0.16818, 0, 0, 0.323529,-0.0742215) , 
6, -6.88097, 0, 0, 0.496013,-0.00982863)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.892857,0.0377034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49469,0.00170937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492823,-0.0152205) , 
4, 0.953782, 1, 0, 0.494532,0.000799769) , 
1, 0.90985, 0, 0, 0.507638,0.0045037)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.824034,0.0239617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485676,-0.000257281) , 
5, 0.174566, 0, 0, 0.517186,0.00632368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0506329,-0.0528949) , 
0, 1.19048, 0, 0, 0.502906,0.00170727)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535316,0.00289267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283871,-0.0257049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,0.0127429) , 
7, -0.120585, 0, 0, 0.26087,-0.0610829) , 
3, 0.770818, 0, 0, 0.513699,0.00526821)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706935,0.0111224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466085,-0.00253216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0512821,-0.0451483) , 
1, 0.423432, 0, 0, 0.45098,-0.0133251) , 
2, 41.241, 0, 0, 0.495172,-0.004042)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565217,0.00303246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245283,0.014557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178125,-0.0234078) , 
6, -5.97485, 1, 0, 0.194836,-0.0443234) , 
1, 0.540382, 0, 0, 0.503704,0.00234183)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.800499,0.0145463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458515,-0.00171587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311111,-0.0185218) , 
4, 0.168181, 0, 0, 0.439581,-0.0145878) , 
1, 0.839965, 0, 0, 0.497403,-0.00476562)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509502,-0.000251103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340206,-0.0231174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3,0.00993793) , 
3, 0.816697, 0, 0, 0.331967,-0.0684592) , 
6, -6.88097, 0, 0, 0.49185,-0.00764477)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60039,0.00497195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519031,-0.0108026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313726,0.00812468) , 
7, 0.240387, 0, 0, 0.430065,-0.0120749) , 
4, 0.630291, 0, 0, 0.498435,0.000267105)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526154,0.00283099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363158,-0.0130805) , 
5, -7.26202, 0, 0, 0.51359,0.00572009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.05,-0.0493525) , 
1, 0.402252, 0, 0, 0.502574,0.00278672)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616555,0.00336463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376623,-0.0193796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252427,0.0041423) , 
1, 0.682478, 0, 0, 0.3001,-0.0244691) , 
7, -0.0439457, 0, 0, 0.496599,-0.00153613)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770161,0.0104527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446958,-0.0016347) , 
7, 0.903949, 0, 0, 0.511469,0.0018045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.140351,-0.0400021) , 
3, 0.709703, 0, 0, 0.503147,-0.000835581)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608292,0.000955943) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,-0.0218062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261307,-0.00419171) , 
5, -1.96329, 0, 0, 0.276786,-0.0397097) , 
7, -0.138838, 0, 0, 0.490048,-0.0119055)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570352,0.00374129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.263345,-0.0238782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18797,0.0069057) , 
1, 0.620692, 0, 0, 0.226691,-0.0423835) , 
7, -0.51764, 0, 0, 0.496255,0.0017964)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576255,0.00287102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283871,-0.0283071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201511,-0.000524109) , 
7, 0.42526, 0, 0, 0.224638,-0.0316069) , 
1, 0.570279, 0, 0, 0.502287,0.00203375)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512071,0.00125393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392,-0.00950629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189655,-0.0426235) , 
4, 0.241165, 0, 0, 0.327869,-0.0770494) , 
5, -7.48608, 0, 0, 0.498821,-0.00132096)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519964,3.1032e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305936,-0.0323385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228346,0.0167673) , 
7, 0.159549, 0, 0, 0.277457,-0.0615349) , 
3, 0.816655, 0, 0, 0.487059,-0.00824891)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621887,0.00599213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365269,-0.00310727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259259,-0.0311414) , 
5, -9.57552, 0, 0, 0.360589,-0.0164072) , 
6, -2.37259, 0, 0, 0.496468,0.00340664)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771084,0.0120683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547208,-0.00927336) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325048,0.00346378) , 
1, 0.690977, 0, 0, 0.432792,-0.0118754) , 
7, 0.903707, 0, 0, 0.499407,-0.00168271)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484848,-0.00200984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858974,0.0233254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0380855) , 
7, 0.33548, 0, 0, 0.46789,-0.0760727) , 
4, 0.953782, 1, 0, 0.483386,-0.0132919)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580972,0.00437234) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240275,9.01211e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.0375981) , 
6, -1.47851, 1, 0, 0.230503,-0.0369076) , 
7, -0.517509, 0, 0, 0.501763,0.00430402)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522605,0.00304644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.220339,-0.0449229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211538,-0.00155776) , 
6, -2.45315, 0, 0, 0.214724,-0.0586227) , 
3, 0.755539, 0, 0, 0.503108,0.00685103)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57125,0.00543528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4846,-0.0182308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282869,0.00481297) , 
7, 0.526837, 0, 0, 0.382204,-0.0267836) , 
3, 0.923606, 0, 0, 0.499034,0.00228329)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592705,0.00107219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505721,-0.0168121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290038,-0.00476776) , 
1, 0.739789, 0, 0, 0.366667,-0.0342245) , 
2, 30.4177, 0, 0, 0.483504,-0.0144599)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514941,0.00309832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426829,-0.00369352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.113636,-0.0461252) , 
7, -0.586872, 0, 0, 0.31746,-0.0688025) , 
6, -8.48161, 0, 0, 0.505255,0.00736986)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525442,9.2405e-06) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516418,-0.000195827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247396,-0.0213579) , 
2, 32.0699, 0, 0, 0.37274,-0.0390739) , 
4, 0.260602, 0, 0, 0.482985,-0.0108395)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78719,0.0154279) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437099,-0.00153372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275862,-0.0307127) , 
6, -9.19631, 0, 0, 0.432614,-0.00884519) , 
7, 0.904071, 0, 0, 0.499416,0.00200682)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543517,0.00249187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15493,-0.00460221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150442,-0.0360444) , 
7, -0.326171, 1, 0, 0.152941,-0.0585234) , 
1, 0.500607, 0, 0, 0.503789,0.0024496)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74,0.0179868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503669,0.00393217) , 
2, 49.7069, 0, 0, 0.522447,0.0183541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,-0.0254695) , 
0, 1.19048, 0, 0, 0.510212,0.0158505)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597913,0.00622307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423267,-0.00462455) , 
4, 0.498824, 0, 0, 0.511798,0.00335495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0657895,-0.0430674) , 
0, 1.19048, 0, 0, 0.498421,6.14149e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614401,0.00573445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.754717,0.0253366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32516,-0.00940463) , 
1, 0.869551, 0, 0, 0.348133,-0.0280086) , 
6, -2.8228, 0, 0, 0.507872,0.00118514)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538034,0.002768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130435,0.0227223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115385,-0.0315369) , 
3, 0.816684, 1, 0, 0.118812,-0.0615909) , 
1, 0.477924, 0, 0, 0.504721,0.00466103)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628846,0.00621906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331939,-0.010141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222222,0.0113476) , 
1, 0.553994, 0, 0, 0.301205,-0.020646) , 
7, -0.043777, 0, 0, 0.501174,0.00547873)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609612,0.00558089) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525108,-0.0131306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314244,0.0079671) , 
7, 0.429942, 0, 0, 0.4209,-0.0122752) , 
4, 0.540614, 0, 0, 0.50819,0.00268072)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546416,-0.00667552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609333,-0.00388519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361702,0.00995963) , 
7, 0.526598, 0, 0, 0.474741,0.0125471) , 
3, 0.984724, 0, 0, 0.499198,-0.000194856)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522097,0.00308947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296296,0.00997811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27957,-0.0275424) , 
7, -0.685356, 1, 0, 0.283333,-0.0749707) , 
6, -6.95413, 0, 0, 0.499608,0.00304167)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526339,0.00134503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40678,0.0140663) , 
5, -6.43889, 0, 0, 0.515115,0.00916754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272727,-0.0223532) , 
5, -9.2305, 0, 0, 0.508915,0.00670767)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650412,0.00476508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368794,-0.0231121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302671,-0.00363365) , 
0, 4.04762, 0, 0, 0.310764,-0.0240088) , 
7, 0.145768, 0, 0, 0.500383,-0.00120282)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825911,0.0160395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685484,0.0158748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452602,-0.00378829) , 
2, 51.2667, 0, 0, 0.46529,-0.00978454) , 
1, 0.867885, 0, 0, 0.500595,-0.00417656)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549978,0.00197952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261905,0.0247588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188552,-0.0213667) , 
4, 0.181437, 1, 0, 0.19764,-0.0520934) , 
0, 2.14286, 0, 0, 0.504215,-0.000436179)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586995,-0.00846216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489721,0.00154712) , 
4, 0.861354, 0, 0, 0.512165,-0.00277167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0526316,-0.0437912) , 
0, 1.19048, 0, 0, 0.498426,-0.0056805)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574203,0.000605815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25969,-0.0204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.159091,-0.00476949) , 
0, 3.09524, 0, 0, 0.204947,-0.0411954) , 
1, 0.572919, 0, 0, 0.493007,-0.00729413)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714286,-0.0285597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599581,0.00850163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432249,-0.00269002) , 
4, 0.632489, 0, 0, 0.497942,0.00624533) , 
5, 0.802345, 0, 0, 0.506329,0.00281066)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558525,0.00178624) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350877,-0.00584815) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196721,-0.0300352) , 
4, 0.173113, 0, 0, 0.323699,-0.0363526) , 
5, -3.95046, 0, 0, 0.495123,-0.00519518)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604359,0.003708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354872,-0.00491188) , 
5, -2.74931, 0, 0, 0.506629,0.000969399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243902,-0.0386416) , 
4, 0.0855065, 0, 0, 0.502372,-0.00132708)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590053,-0.00641176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495652,-0.000960556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273921,0.0141527) , 
1, 0.639325, 0, 0, 0.399019,0.0164893) , 
6, -2.25029, 0, 0, 0.498431,-0.00377701)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.0270219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494248,-0.003339) , 
6, -9.16065, 1, 0, 0.494386,-0.00905707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487805,0.0433564) , 
4, 0.0812396, 0, 0, 0.494284,-0.00669793)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887931,0.028111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583633,-0.00548143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380518,0.00104187) , 
6, -2.08452, 0, 0, 0.473619,-0.00692461) , 
6, 0.681913, 0, 0, 0.492526,-0.00305638)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508547,-0.013155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604033,0.00843588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407674,-0.00177966) , 
4, 0.469533, 0, 0, 0.499146,0.0108027) , 
4, 0.953777, 0, 0, 0.5,0.00545965)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.641873,0.00289215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334,-0.0177267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284195,0.0032431) , 
4, 0.681059, 0, 0, 0.305699,-0.0258836) , 
7, 0.145768, 0, 0, 0.49272,-0.00582541)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723769,0.0127483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554894,-0.00928918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318282,0.00338662) , 
7, 0.0525665, 0, 0, 0.451752,-0.013754) , 
2, 41.241, 0, 0, 0.501569,-0.00311468)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7825,0.00973793) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483304,-0.00142994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261364,-0.0150889) , 
3, 0.862516, 0, 0, 0.43782,-0.014307) , 
1, 0.839352, 0, 0, 0.491951,-0.00731972)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697509,0.0118661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455898,-0.00173775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.031746,-0.0540859) , 
0, 1.14286, 0, 0, 0.442159,-0.0101352) , 
2, 39.0916, 0, 0, 0.499402,0.00154386)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52518,-0.0115508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57602,0.00646615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218487,-0.00843875) , 
1, 0.57479, 0, 0, 0.494747,0.0130019) , 
4, 0.908118, 0, 0, 0.499801,0.00395058)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517437,0.00231929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.000917249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125,-0.04383) , 
0, 4.14286, 0, 0, 0.327586,-0.0638278) , 
6, -8.42453, 0, 0, 0.508908,0.00498713)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584887,0.00746526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464918,-0.00131835) , 
3, 0.969448, 0, 0, 0.512972,0.00807404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254545,-0.0301224) , 
6, -9.62191, 0, 0, 0.507503,0.00547248)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616101,-0.00153935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383178,0.00338946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292876,0.0196388) , 
4, 0.407697, 0, 0, 0.349657,0.030755) , 
7, 0.0527037, 0, 0, 0.50832,0.00925636)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554948,0.00485285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478022,0.00479757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284974,-0.014459) , 
3, 0.923606, 0, 0, 0.378667,-0.0161697) , 
4, 0.260606, 0, 0, 0.503684,0.00762265)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620499,0.00436984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41484,-0.0128686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263473,0.00502666) , 
7, -0.139265, 0, 0, 0.345521,-0.0188077) , 
0, 3.09524, 0, 0, 0.50197,0.000889439)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677596,0.00637996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474934,-0.00491141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27789,0.00814708) , 
7, -0.423183, 0, 0, 0.415337,-0.00489043) , 
6, -1.45545, 0, 0, 0.509627,0.00467735)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678082,0.00393854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58,-0.0540906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389602,-0.00237119) , 
1, 0.903906, 0, 0, 0.395252,-0.0134768) , 
5, -1.35756, 0, 0, 0.491995,-0.00426013)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
