// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Mon Nov 17 17:28:43 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 2439
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "2439" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 9
MT_of_everything              MT_of_everything              MT_of_everything              MT_of_everything                                                'F'    [188.999298096,1774.0255127]
numMediumBJets                numMediumBJets                numMediumBJets                numMediumBJets                                                  'I'    [0,3]
Match_ttZ_3l_Bb               Match_ttZ_3l_Bb               Match_ttZ_3l_Bb               Match_ttZ_3l_Bb                                                 'F'    [-9.8359413147,1.78761184216]
Match_ttZ_3l_Bq               Match_ttZ_3l_Bq               Match_ttZ_3l_Bq               Match_ttZ_3l_Bq                                                 'F'    [-8.65219974518,1.39276385307]
Match_ttZ_3l_bq               Match_ttZ_3l_bq               Match_ttZ_3l_bq               Match_ttZ_3l_bq                                                 'F'    [-5.20502948761,1.60051989555]
Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq              Match_ttZ_3l_Bbq                                                'F'    [-13.6642150879,2.00651955605]
Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq              Match_ttZ_3l_Bqq                                                'F'    [-16.0809345245,2.03154420853]
Match_ttZ_3l_bqq              Match_ttZ_3l_bqq              Match_ttZ_3l_bqq              Match_ttZ_3l_bqq                                                'F'    [-14.9428005219,2.07152605057]
ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all    ZLike_mass_leplep_SFOS_all                                      'F'    [81.0130691528,100.984512329]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 9 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "MT_of_everything", "numMediumBJets", "Match_ttZ_3l_Bb", "Match_ttZ_3l_Bq", "Match_ttZ_3l_bq", "Match_ttZ_3l_Bbq", "Match_ttZ_3l_Bqq", "Match_ttZ_3l_bqq", "ZLike_mass_leplep_SFOS_all" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 188.999298095703;
      fVmax[0] = 1774.02551269531;
      fVmin[1] = 0;
      fVmax[1] = 3;
      fVmin[2] = -9.83594131469727;
      fVmax[2] = 1.78761184215546;
      fVmin[3] = -8.65219974517822;
      fVmax[3] = 1.39276385307312;
      fVmin[4] = -5.20502948760986;
      fVmax[4] = 1.60051989555359;
      fVmin[5] = -13.6642150878906;
      fVmax[5] = 2.00651955604553;
      fVmin[6] = -16.0809345245361;
      fVmax[6] = 2.03154420852661;
      fVmin[7] = -14.9428005218506;
      fVmax[7] = 2.07152605056763;
      fVmin[8] = 81.013069152832;
      fVmax[8] = 100.984512329102;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'I';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[9];
   double fVmax[9];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[9];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76462,0.052924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490481,-0.0019039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23773,-0.052454) , 
0, 415.432, 0, 0, 0.396581,-0.103419) , 
5, -0.978382, 0, 0, 0.499795,-0.000205002)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684551,0.0345477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411654,-0.0159025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139456,-0.0696379) , 
1, 0.142857, 0, 0, 0.352725,-0.137528) , 
5, -1.72461, 0, 0, 0.499795,-0.000184002)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684551,0.0311866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440678,-0.00914948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188161,-0.0544033) , 
0, 415.432, 0, 0, 0.352725,-0.123803) , 
5, -1.72461, 0, 0, 0.499795,-0.000171609)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76462,0.0416951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490481,-0.000244369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.23773,-0.0434613) , 
0, 415.432, 0, 0, 0.396581,-0.0803535) , 
5, -0.978382, 0, 0, 0.499795,-0.000168963)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.0293263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462905,-0.00558386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205534,-0.0464075) , 
0, 410.138, 0, 0, 0.373889,-0.0962522) , 
2, -0.979901, 0, 0, 0.499795,-0.000147672)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684551,0.0251132) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411654,-0.00975609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139456,-0.0576105) , 
1, 0.142857, 0, 0, 0.352725,-0.0979347) , 
5, -1.72461, 0, 0, 0.499795,-0.000149234)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76462,0.0336936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450803,-0.00445368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.15528,-0.0517938) , 
1, 0.142857, 0, 0, 0.396581,-0.0630475) , 
5, -0.978382, 0, 0, 0.499795,-0.000152805)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.0146263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715596,0.0200175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282216,-0.0330294) , 
5, -0.194768, 0, 0, 0.335593,-0.125891) , 
0, 415.432, 0, 0, 0.499795,-0.000139877)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.0112768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649123,0.0349229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251309,-0.0388544) , 
4, 0.438757, 0, 0, 0.287302,-0.155886) , 
5, -3.21706, 0, 0, 0.499795,-0.000141685)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0374135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478821,-0.0018486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177215,-0.049841) , 
0, 339.954, 0, 0, 0.42982,-0.045103) , 
1, 1.14286, 0, 0, 0.499795,-0.000147876)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00703119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226316,-0.0335456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0980392,-0.0604105) , 
6, -4.32073, 0, 0, 0.169096,-0.20761) , 
1, 0.142857, 0, 0, 0.499795,-0.000133955)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.0127866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443299,-0.00631472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251509,-0.0372723) , 
0, 361.344, 0, 0, 0.335593,-0.108853) , 
0, 415.432, 0, 0, 0.499795,-0.000156132)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.0100792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0361542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253496,-0.0356247) , 
7, -2.31181, 0, 0, 0.287302,-0.137546) , 
5, -3.21706, 0, 0, 0.499795,-0.000157419)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.0189765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624762,0.0074142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282313,-0.0275784) , 
2, -0.832931, 0, 0, 0.410092,-0.0671976) , 
0, 490.909, 0, 0, 0.499795,-0.000162619)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684551,0.0177069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756098,0.0609708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340167,-0.0164702) , 
6, 0.306546, 0, 0, 0.352725,-0.0662385) , 
5, -1.72461, 0, 0, 0.499795,-0.000162799)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.0174273) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437551,-0.00767626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225275,-0.0515034) , 
8, 95.2826, 1, 0, 0.410092,-0.061244) , 
0, 490.909, 0, 0, 0.499795,-0.000145915)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.0089094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0336113) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253496,-0.0319097) , 
7, -2.31181, 0, 0, 0.287302,-0.119711) , 
5, -3.21706, 0, 0, 0.499795,-0.000134477)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0304601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604046,0.0206291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39212,-0.0136997) , 
7, -1.51518, 0, 0, 0.42982,-0.0350148) , 
1, 1.14286, 0, 0, 0.499795,-0.000140749)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.0108521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366856,-0.0133742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21229,-0.0471335) , 
8, 86.7254, 0, 0, 0.335593,-0.0901604) , 
0, 415.432, 0, 0, 0.499795,-0.000107333)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00570031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226316,-0.0270816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0980392,-0.0534896) , 
6, -4.32073, 0, 0, 0.169096,-0.163525) , 
1, 0.142857, 0, 0, 0.499795,-0.000107441)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.0167834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520343,0.00755134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305221,-0.0204213) , 
0, 557.565, 0, 0, 0.373889,-0.0510201) , 
2, -0.979901, 0, 0, 0.499795,-0.000128695)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640385,0.0152422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493301,-0.00119097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256055,-0.0267137) , 
5, -3.01495, 0, 0, 0.395282,-0.0524766) , 
4, -0.019849, 0, 0, 0.499795,-0.000119006)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.0151991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437551,-0.00638701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225275,-0.0478375) , 
8, 95.2826, 1, 0, 0.410092,-0.0520577) , 
0, 490.909, 0, 0, 0.499795,-0.000118041)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00510502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247557,-0.0273425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0444444,-0.0764879) , 
8, 83.8766, 0, 0, 0.221591,-0.139789) , 
0, 339.954, 0, 0, 0.499795,-0.000110855)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.0073971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649123,0.0299034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251309,-0.0272383) , 
4, 0.438757, 0, 0, 0.287302,-0.0967082) , 
5, -3.21706, 0, 0, 0.499795,-0.000119898)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00892285) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363881,-0.0113758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188811,-0.045816) , 
8, 85.7758, 0, 0, 0.335593,-0.0726423) , 
0, 415.432, 0, 0, 0.499795,-0.000123853)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00476836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226316,-0.0223676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0980392,-0.0488193) , 
6, -4.32073, 0, 0, 0.169096,-0.134204) , 
1, 0.142857, 0, 0, 0.499795,-0.000122206)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0245563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604046,0.0188773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39212,-0.0114937) , 
7, -1.51518, 0, 0, 0.42982,-0.0268006) , 
1, 1.14286, 0, 0, 0.499795,-0.000137271)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00429418) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39267,-0.0184479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-0.0600652) , 
8, 98.2714, 1, 0, 0.32872,-0.143319) , 
8, 95.2784, 1, 0, 0.499795,-0.000108772)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.012965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480946,0.00158191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326625,-0.0243027) , 
7, -4.72783, 0, 0, 0.410092,-0.0435604) , 
0, 490.909, 0, 0, 0.499795,-0.000101638)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.00662353) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0292537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253496,-0.0249762) , 
7, -2.31181, 0, 0, 0.287302,-0.0852224) , 
5, -3.21706, 0, 0, 0.499795,-9.50245e-05)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.825967,0.0283284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464481,-0.00055088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283401,-0.0341088) , 
8, 84.8143, 0, 0, 0.442947,-0.0202016) , 
5, -0.232157, 0, 0, 0.499795,-9.93269e-05)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00796442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443299,-0.00139938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251509,-0.0267255) , 
0, 361.344, 0, 0, 0.335593,-0.0634361) , 
0, 415.432, 0, 0, 0.499795,-7.47326e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00392883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39267,-0.0168778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-0.0552509) , 
8, 98.2714, 1, 0, 0.32872,-0.129153) , 
8, 95.2784, 1, 0, 0.499795,-7.90401e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520211,0.00284606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0242398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139241,-0.0537632) , 
8, 90.5424, 0, 0, 0.214724,-0.17482) , 
5, -6.20196, 0, 0, 0.499795,-7.63472e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00410053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226316,-0.0195985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0980392,-0.0442648) , 
6, -4.32073, 0, 0, 0.169096,-0.112897) , 
1, 0.142857, 0, 0, 0.499795,-7.97347e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.0117184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709677,0.0338672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388889,-0.0123367) , 
6, 0.276526, 0, 0, 0.410092,-0.0385923) , 
0, 490.909, 0, 0, 0.499795,-9.46806e-05)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640385,0.0115981) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412355,-0.00590785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.182692,-0.0491125) , 
8, 83.8661, 0, 0, 0.395282,-0.038382) , 
4, -0.019849, 0, 0, 0.499795,-8.27936e-05)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00359786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39267,-0.0154793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-0.0509104) , 
8, 98.2714, 1, 0, 0.32872,-0.117062) , 
8, 95.2784, 1, 0, 0.499795,-7.89921e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0208477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447687,-0.00226896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178295,-0.0422521) , 
5, -6.58405, 0, 0, 0.42982,-0.0216197) , 
1, 1.14286, 0, 0, 0.499795,-7.68949e-05)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00390593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.380952,-0.000371439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.171642,-0.0366145) , 
7, -1.75, 0, 0, 0.221591,-0.10235) , 
0, 339.954, 0, 0, 0.499795,-6.66244e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.00546001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0269132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253496,-0.02121) , 
7, -2.31181, 0, 0, 0.287302,-0.0683637) , 
5, -3.21706, 0, 0, 0.499795,-7.63385e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.0108664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462754,0.000180962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320537,-0.0235328) , 
6, -3.81852, 0, 0, 0.410092,-0.0351818) , 
0, 490.909, 0, 0, 0.499795,-7.90697e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.0112872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395817,-0.00321041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0315266) , 
8, 85.7645, 0, 0, 0.373889,-0.0318824) , 
2, -0.979901, 0, 0, 0.499795,-7.39077e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00333085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39267,-0.0143477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-0.0475709) , 
8, 98.2714, 1, 0, 0.32872,-0.106569) , 
8, 95.2784, 1, 0, 0.499795,-6.80904e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00659742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366856,-0.00710674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21229,-0.0353806) , 
8, 86.7254, 0, 0, 0.335593,-0.0510373) , 
0, 415.432, 0, 0, 0.499795,-6.72322e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00346575) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175,-0.0501155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168317,-0.0227216) , 
2, -1.11121, 0, 0, 0.169096,-0.0930357) , 
1, 0.142857, 0, 0, 0.499795,-6.83029e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771654,0.0355844) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888199,0.0362929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454672,-0.00451621) , 
5, 0.514069, 0, 0, 0.484862,-0.00877806) , 
6, 0.306546, 0, 0, 0.499795,-7.38475e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520211,0.00230107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0184824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139241,-0.0464927) , 
8, 90.5424, 0, 0, 0.214724,-0.136222) , 
5, -6.20196, 0, 0, 0.499795,-4.46532e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00446079) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0241065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359743,-0.0215622) , 
0, 745.861, 0, 0, 0.389961,-0.0701866) , 
8, 93.3763, 1, 0, 0.499795,-4.99945e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519963,0.00306284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744186,0.00670265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276859,-0.0287315) , 
5, -0.390061, 0, 0, 0.347368,-0.0981645) , 
8, 84.8172, 0, 0, 0.499795,-4.65051e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00334563) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261324,-0.0162128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461538,-0.0618834) , 
0, 275.235, 0, 0, 0.221591,-0.085714) , 
0, 339.954, 0, 0, 0.499795,-4.68902e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640385,0.00927483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442982,-0.000470127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305955,-0.0198853) , 
6, -5.08823, 0, 0, 0.395282,-0.0296464) , 
4, -0.019849, 0, 0, 0.499795,-5.87173e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.00944488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605405,0.0172653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380524,-0.0113219) , 
6, -0.30848, 0, 0, 0.410092,-0.0298629) , 
0, 490.909, 0, 0, 0.499795,-5.56579e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00411144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0206008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359743,-0.0196934) , 
0, 745.861, 0, 0, 0.389961,-0.0641031) , 
8, 93.3763, 1, 0, 0.499795,-4.97367e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.00461376) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.62069,0.0247048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253496,-0.0183513) , 
7, -2.31181, 0, 0, 0.287302,-0.0560589) , 
5, -3.21706, 0, 0, 0.499795,-4.62426e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519963,0.00283607) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688889,0.0051524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283333,-0.0269586) , 
1, 1.14286, 0, 0, 0.347368,-0.0898744) , 
8, 84.8172, 0, 0, 0.499795,-4.92936e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00569326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367893,-0.00441838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268293,-0.0248898) , 
8, 88.6246, 0, 0, 0.335593,-0.0430384) , 
0, 415.432, 0, 0, 0.499795,-4.86207e-05)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0165512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604046,0.0133384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39212,-0.00771103) , 
7, -1.51518, 0, 0, 0.42982,-0.0160634) , 
1, 1.14286, 0, 0, 0.499795,-4.84956e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511767,0.00160263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.292683,-0.0229923) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.180328,-0.0486319) , 
7, -4.25321, 0, 0, 0.22549,-0.152801) , 
8, 98.1314, 1, 0, 0.499795,-3.60742e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520211,0.00200256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0155861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139241,-0.0421932) , 
8, 90.5424, 0, 0, 0.214724,-0.116007) , 
5, -6.20196, 0, 0, 0.499795,-3.76365e-05)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622255,0.0119025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543977,0.00308269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.0172044) , 
3, -0.322865, 0, 0, 0.452164,-0.0197971) , 
0, 566.386, 0, 0, 0.499795,-4.25436e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00266203) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39267,-0.011384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-0.0392158) , 
8, 98.2714, 1, 0, 0.32872,-0.082163) , 
8, 95.2784, 1, 0, 0.499795,-4.15716e-05)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00285302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175,-0.0461109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168317,-0.0187121) , 
2, -1.11121, 0, 0, 0.169096,-0.0742932) , 
1, 0.142857, 0, 0, 0.499795,-4.26539e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00284369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255556,-0.0379935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209924,-0.0124944) , 
3, 0.31932, 0, 0, 0.221591,-0.0711835) , 
0, 339.954, 0, 0, 0.499795,-4.74146e-05)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613821,0.0137158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.832237,0.0197869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404139,-0.00734174) , 
5, -0.232157, 0, 0, 0.470981,-0.0148906) , 
7, -1.9795, 0, 0, 0.499795,-4.75561e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647458,0.0185043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535654,0.00572761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410973,-0.0131036) , 
6, -3.72902, 0, 0, 0.479478,-0.0108225) , 
0, 717.341, 0, 0, 0.499795,-3.37275e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519963,0.0025644) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381974,-0.0145522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,-0.0456912) , 
8, 81.7365, 0, 0, 0.347368,-0.079498) , 
8, 84.8172, 0, 0, 0.499795,-2.9158e-05)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00360637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0168706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359743,-0.0171637) , 
0, 745.861, 0, 0, 0.389961,-0.0547649) , 
8, 93.3763, 1, 0, 0.499795,-2.9864e-05)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520211,0.00184744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304878,-0.013145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.123457,-0.041435) , 
3, -2.88776, 1, 0, 0.214724,-0.105406) , 
5, -6.20196, 0, 0, 0.499795,-2.82122e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00510826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358537,-0.00712937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461538,-0.0580968) , 
0, 275.172, 0, 0, 0.335593,-0.0377346) , 
0, 415.432, 0, 0, 0.499795,-3.40104e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771654,0.0276062) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632338,0.00658049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378076,-0.00774431) , 
4, -0.019849, 0, 0, 0.484862,-0.00638047) , 
6, 0.306546, 0, 0, 0.499795,-4.23218e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.00754961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480946,0.0019561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326625,-0.015858) , 
7, -4.72783, 0, 0, 0.410092,-0.0230211) , 
0, 490.909, 0, 0, 0.499795,-3.37743e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519963,0.00236879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566038,0.00328293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297414,-0.0243273) , 
4, 0.527137, 0, 0, 0.347368,-0.0727443) , 
8, 84.8172, 0, 0, 0.499795,-3.26008e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547274,0.00304742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424658,0.0111066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256131,-0.0195575) , 
3, -0.250235, 0, 0, 0.284091,-0.0561223) , 
5, -3.96328, 0, 0, 0.499795,-3.25372e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00332911) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439678,-0.00634485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262069,-0.0291487) , 
8, 97.3623, 1, 0, 0.389961,-0.0499799) , 
8, 93.3763, 1, 0, 0.499795,-3.50465e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0142159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447687,-0.00143343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178295,-0.0301031) , 
5, -6.58405, 0, 0, 0.42982,-0.0131832) , 
1, 1.14286, 0, 0, 0.499795,-3.48603e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622255,0.0101101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503043,0.00302677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387013,-0.0137834) , 
6, -3.54951, 0, 0, 0.452164,-0.0163015) , 
0, 566.386, 0, 0, 0.499795,-3.1954e-05)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00458371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367893,-0.00274119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268293,-0.0218831) , 
8, 88.6246, 0, 0, 0.335593,-0.033349) , 
0, 415.432, 0, 0, 0.499795,-2.86748e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00243407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175,-0.0422533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168317,-0.0160062) , 
2, -1.11121, 0, 0, 0.169096,-0.0617006) , 
1, 0.142857, 0, 0, 0.499795,-2.95037e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890244,0.029362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0100994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438227,-0.00486125) , 
7, -1.9795, 0, 0, 0.471648,-0.00663357) , 
5, 0.514069, 0, 0, 0.499795,-3.34957e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00310246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441065,-0.00244705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337255,-0.0215453) , 
6, -3.84149, 0, 0, 0.389961,-0.0459623) , 
8, 93.3763, 1, 0, 0.499795,-1.92724e-05)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00296594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794118,0.0124783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340796,-0.0163805) , 
5, -0.390061, 0, 0, 0.406383,-0.0495868) , 
8, 86.7192, 0, 0, 0.499795,-1.90331e-05)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00238213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255556,-0.0353139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209924,-0.00907392) , 
3, 0.31932, 0, 0, 0.221591,-0.0576703) , 
0, 339.954, 0, 0, 0.499795,-1.8297e-05)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647458,0.0152681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535654,0.00447717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410973,-0.0105145) , 
6, -3.72902, 0, 0, 0.479478,-0.00863969) , 
0, 717.341, 0, 0, 0.499795,-2.02317e-05)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.00732349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520343,0.00481551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305221,-0.00990274) , 
0, 557.565, 0, 0, 0.373889,-0.0189036) , 
2, -0.979901, 0, 0, 0.499795,-1.73246e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511767,0.00118186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241379,-0.0376153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204545,-0.0161998) , 
2, -1.42893, 0, 0, 0.22549,-0.107498) , 
8, 98.1314, 1, 0, 0.499795,-1.66781e-05)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573798,0.00332254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649123,0.023329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251309,-0.0141126) , 
4, 0.438757, 0, 0, 0.287302,-0.0381716) , 
5, -3.21706, 0, 0, 0.499795,-1.74761e-05)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519963,0.00206469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381974,-0.0112873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192308,-0.0403066) , 
8, 81.7365, 0, 0, 0.347368,-0.0618307) , 
8, 84.8172, 0, 0, 0.499795,-1.98451e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00411129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358537,-0.00552243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461538,-0.0548411) , 
0, 275.172, 0, 0, 0.335593,-0.0294119) , 
0, 415.432, 0, 0, 0.499795,-2.09037e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00286672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666667,0.0138884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359743,-0.0137306) , 
0, 745.861, 0, 0, 0.389961,-0.0419627) , 
8, 93.3763, 1, 0, 0.499795,-2.85593e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00214706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239726,-0.00299238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116751,-0.0301449) , 
3, -0.718469, 0, 0, 0.169096,-0.053515) , 
1, 0.142857, 0, 0, 0.499795,-2.66436e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771654,0.0229338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.888199,0.0258552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454672,-0.0027951) , 
5, 0.514069, 0, 0, 0.484862,-0.00503938) , 
6, 0.306546, 0, 0, 0.499795,-3.38044e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520211,0.00143734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.00821232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139241,-0.0354231) , 
8, 90.5424, 0, 0, 0.214724,-0.0787276) , 
5, -6.20196, 0, 0, 0.499795,-1.94512e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00258017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584416,0.00911992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371501,-0.0153077) , 
8, 86.1697, 0, 0, 0.406383,-0.0424028) , 
8, 86.7192, 0, 0, 0.499795,-2.3523e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.0038539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36699,-0.00111921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291892,-0.0163737) , 
8, 89.5742, 0, 0, 0.335593,-0.0273381) , 
0, 415.432, 0, 0, 0.499795,-2.20744e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00195299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,0.0120728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315574,-0.0202106) , 
6, -6.86271, 1, 0, 0.32872,-0.0569807) , 
8, 95.2784, 1, 0, 0.499795,-2.21907e-05)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547274,0.00242343) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425926,0.00819863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237952,-0.0187631) , 
3, -3.51767, 1, 0, 0.284091,-0.043087) , 
5, -3.96328, 0, 0, 0.499795,-2.19688e-05)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647458,0.0133955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622222,0.011467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446233,-0.00527983) , 
7, -1.70589, 0, 0, 0.479478,-0.00740449) , 
0, 717.341, 0, 0, 0.499795,-2.46919e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.0113611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447687,-0.000958963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178295,-0.0266059) , 
5, -6.58405, 0, 0, 0.42982,-0.00997808) , 
1, 1.14286, 0, 0, 0.499795,-1.99475e-05)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.00577428) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480946,0.00146919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326625,-0.0121947) , 
7, -4.72783, 0, 0, 0.410092,-0.0167897) , 
0, 490.909, 0, 0, 0.499795,-1.93518e-05)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00258437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441065,-0.00157573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337255,-0.0185144) , 
6, -3.84149, 0, 0, 0.389961,-0.0371742) , 
8, 93.3763, 1, 0, 0.499795,-1.87706e-05)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00240733) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481884,-0.00299725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298969,-0.0215887) , 
8, 83.9985, 0, 0, 0.406383,-0.0391319) , 
8, 86.7192, 0, 0, 0.499795,-1.8255e-05)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00194254) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255556,-0.0322011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209924,-0.00601374) , 
3, 0.31932, 0, 0, 0.221591,-0.045773) , 
0, 339.954, 0, 0, 0.499795,-1.83254e-05)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00189777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175,-0.0397695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168317,-0.0118078) , 
2, -1.11121, 0, 0, 0.169096,-0.0465145) , 
1, 0.142857, 0, 0, 0.499795,-1.94214e-05)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511767,0.00100369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241379,-0.0329744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204545,-0.0129766) , 
2, -1.42893, 0, 0, 0.22549,-0.0891698) , 
8, 98.1314, 1, 0, 0.499795,-2.20876e-05)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688525,0.00596699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520343,0.00427479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305221,-0.00827913) , 
0, 557.565, 0, 0, 0.373889,-0.0149318) , 
2, -0.979901, 0, 0, 0.499795,-2.18945e-05)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509762,0.000893057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.0151906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.0406632) , 
7, -10.3112, 0, 0, 0.216867,-0.0978413) , 
4, -2.93651, 0, 0, 0.499795,-2.04887e-05)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545107,0.0042878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60181,0.0103466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40989,-0.00900371) , 
0, 717.341, 0, 0, 0.447392,-0.019073) , 
6, -4.00595, 0, 0, 0.499795,-2.16571e-05)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890244,0.0237205) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561056,0.00214714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293421,-0.00856004) , 
5, -2.86651, 0, 0, 0.471648,-0.00476703) , 
5, 0.514069, 0, 0, 0.499795,-1.95261e-05)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00342494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358537,-0.00444363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461538,-0.0519829) , 
0, 275.172, 0, 0, 0.335593,-0.0237741) , 
0, 415.432, 0, 0, 0.499795,-1.31327e-05)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00222918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584416,0.00753176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371501,-0.0131965) , 
8, 86.1697, 0, 0, 0.406383,-0.0358062) , 
8, 86.7192, 0, 0, 0.499795,-1.99964e-05)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.0024146) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439678,-0.00432844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262069,-0.0221758) , 
8, 97.3623, 1, 0, 0.389961,-0.0342611) , 
8, 93.3763, 1, 0, 0.499795,-1.87204e-05)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.771654,0.0192393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601648,0.00972623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463039,-0.00324228) , 
7, -1.79288, 0, 0, 0.484862,-0.0040337) , 
6, 0.306546, 0, 0, 0.499795,-1.89697e-05)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.00991871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447687,-0.000768821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178295,-0.0242023) , 
5, -6.58405, 0, 0, 0.42982,-0.00844819) , 
1, 1.14286, 0, 0, 0.499795,-1.39354e-05)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622255,0.00693118) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543977,0.00262393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.0113769) , 
3, -0.322865, 0, 0, 0.452164,-0.0105376) , 
0, 566.386, 0, 0, 0.499795,-1.4009e-05)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00316831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360158,-0.0087281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188976,0.0197254) , 
2, -2.07036, 0, 0, 0.335593,-0.021824) , 
0, 415.432, 0, 0, 0.499795,-1.41014e-05)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00207937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794118,0.0107279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340796,-0.0118745) , 
5, -0.390061, 0, 0, 0.406383,-0.0331459) , 
8, 86.7192, 0, 0, 0.499795,-1.61479e-05)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00226896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552632,-0.0214937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344059,-0.00460788) , 
2, -0.34369, 0, 0, 0.389961,-0.0319438) , 
8, 93.3763, 1, 0, 0.499795,-1.51025e-05)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509762,0.00079957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,-0.013633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146341,-0.0373195) , 
7, -10.3112, 0, 0, 0.216867,-0.086216) , 
4, -2.93651, 0, 0, 0.499795,-1.17432e-05)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00161839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175,-0.037264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168317,-0.00971106) , 
2, -1.11121, 0, 0, 0.169096,-0.0389385) , 
1, 0.142857, 0, 0, 0.499795,-1.33408e-05)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703297,0.0137341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49745,-0.000164801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18,-0.0241733) , 
5, -6.94819, 0, 0, 0.483385,-0.00436957) , 
7, -0.359092, 0, 0, 0.499795,-1.56317e-05)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647458,0.0108259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566256,0.00292935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346336,-0.00854131) , 
3, -0.414614, 0, 0, 0.479478,-0.00576507) , 
0, 717.341, 0, 0, 0.499795,-1.58021e-05)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00298156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360158,-0.008181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188976,0.0179859) , 
2, -2.07036, 0, 0, 0.335593,-0.0203933) , 
0, 415.432, 0, 0, 0.499795,-1.45491e-05)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511767,0.00083398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254545,-0.0279289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191489,-0.0107142) , 
4, -0.48231, 0, 0, 0.22549,-0.0724147) , 
8, 98.1314, 1, 0, 0.499795,-1.5997e-05)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00195918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481884,-0.00200206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298969,-0.0184495) , 
8, 83.9985, 0, 0, 0.406383,-0.0310435) , 
8, 86.7192, 0, 0, 0.499795,-1.58664e-05)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640385,0.00457145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40937,-0.0019416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206186,-0.0264873) , 
4, -2.7363, 0, 0, 0.395282,-0.0130827) , 
4, -0.019849, 0, 0, 0.499795,-1.57364e-05)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529412,0.00204731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552632,-0.019482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344059,-0.00406988) , 
2, -0.34369, 0, 0, 0.389961,-0.0286019) , 
8, 93.3763, 1, 0, 0.499795,-1.61536e-05)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775304,0.00916417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447687,-0.000806742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178295,-0.0211524) , 
5, -6.58405, 0, 0, 0.42982,-0.00765193) , 
1, 1.14286, 0, 0, 0.499795,-1.30971e-05)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546718,0.00158193) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255556,-0.0298157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209924,-0.00325329) , 
3, 0.31932, 0, 0, 0.221591,-0.0361943) , 
0, 339.954, 0, 0, 0.499795,-1.27357e-05)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50284,-0.00101551) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689655,0.0395682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304348,-0.00430125) , 
5, -5.78355, 0, 0, 0.453333,0.0572963) , 
3, -2.91222, 0, 0, 0.499795,-1.38391e-05)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545107,0.00370668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447475,-0.00714068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446809,0.013634) , 
3, -2.91222, 0, 0, 0.447392,-0.0160853) , 
6, -4.00595, 0, 0, 0.499795,-1.18005e-05)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890244,0.0208311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561056,0.00187994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293421,-0.00739144) , 
5, -2.86651, 0, 0, 0.471648,-0.00392376) , 
5, 0.514069, 0, 0, 0.499795,-1.11637e-05)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622255,0.00619482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543977,0.00226755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316901,-0.00999747) , 
3, -0.322865, 0, 0, 0.452164,-0.00921178) , 
0, 566.386, 0, 0, 0.499795,-6.75052e-06)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651007,0.0182676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499332,-0.000653712) , 
0, 839.659, 0, 0, 0.508772,0.00198358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0222222,-0.0549931) , 
0, 264.477, 0, 0, 0.499795,-7.23356e-06)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00185468) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481884,-0.00212971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298969,-0.017152) , 
8, 83.9985, 0, 0, 0.406383,-0.0290757) , 
8, 86.7192, 0, 0, 0.499795,-1.18934e-05)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526901,0.00243769) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714286,0.0215123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419214,-0.00755476) , 
6, 0.143919, 0, 0, 0.436214,-0.0213035) , 
8, 92.4253, 1, 0, 0.499795,-1.19782e-05)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529951,0.0020582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,0.019387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383104,-0.0102594) , 
7, -11.1704, 1, 0, 0.404437,-0.0243216) , 
6, -5.73095, 0, 0, 0.499795,-1.02772e-05)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593308,0.00269694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36699,0.000517115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291892,-0.0132596) , 
8, 89.5742, 0, 0, 0.335593,-0.0181881) , 
0, 415.432, 0, 0, 0.499795,-9.87402e-06)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522791,0.00129252) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4,0.0190468) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315574,-0.0153182) , 
6, -6.86271, 1, 0, 0.32872,-0.0359384) , 
8, 95.2784, 1, 0, 0.499795,-1.04634e-05)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547274,0.0016728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425926,0.00939918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237952,-0.0146665) , 
3, -3.51767, 1, 0, 0.284091,-0.0283938) , 
5, -3.96328, 0, 0, 0.499795,-1.09726e-05)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522092,0.00172209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470588,-0.00420135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0886076,-0.0338776) , 
0, 339.954, 0, 0, 0.406383,-0.0268948) , 
8, 86.7192, 0, 0, 0.499795,-1.29758e-05)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553912,0.00136337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239726,0.00262787) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.116751,-0.0244943) , 
3, -0.718469, 0, 0, 0.169096,-0.0322071) , 
1, 0.142857, 0, 0, 0.499795,-1.5867e-05)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505069,-0.00123202) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697248,0.0366776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29375,-0.00804188) , 
3, -0.227811, 0, 0, 0.457249,0.036846) , 
7, -10.0816, 0, 0, 0.499795,-2.02774e-05)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613821,0.00674606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475028,-0.000502208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42069,-0.0165612) , 
7, -2.5992, 1, 0, 0.470981,-0.00663229) , 
7, -1.9795, 0, 0, 0.499795,-1.5977e-05)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545107,0.00323756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447475,-0.00636589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446809,0.0124753) , 
3, -2.91222, 0, 0, 0.447392,-0.0138821) , 
6, -4.00595, 0, 0, 0.499795,-1.40181e-05)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622093,0.00402578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480946,0.00139325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326625,-0.00904501) , 
7, -4.72783, 0, 0, 0.410092,-0.0111433) , 
0, 490.909, 0, 0, 0.499795,-1.30605e-05)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.890244,0.019214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561056,0.00157215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293421,-0.00643203) , 
5, -2.86651, 0, 0, 0.471648,-0.00349327) , 
5, 0.514069, 0, 0, 0.499795,-1.25484e-05)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526901,0.00227915) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.714286,0.018373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419214,-0.00692616) , 
6, 0.143919, 0, 0, 0.436214,-0.0196899) , 
8, 92.4253, 1, 0, 0.499795,-8.45233e-06)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505069,-0.00120488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697248,0.0344567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29375,-0.00659577) , 
3, -0.227811, 0, 0, 0.457249,0.0359852) , 
7, -10.0816, 0, 0, 0.499795,-7.2341e-06)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
