// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : abrinke1
Date           : Tue Oct 14 16:03:28 2014
Host           : Linux lxbuild168.cern.ch 2.6.18-308.16.1.el5 #1 SMP Thu Oct 4 14:02:28 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/crc.nd.edu/user/a/abrinke1/TMVAv412
Training events: 5348
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "200" [Number of trees in the forest]
BoostType: "Grad" [Boosting type for the trees in the forest]
UseBaggedGrad: "True" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "5.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
nCuts: "20" [Number of steps during node cut optimisation]
NNodesMax: "5" [Max number of nodes in tree]
NegWeightTreatment: "ignorenegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "3" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "5348" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "40" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
numJets_40                    numJets_40                    numJets_40                    numJets_40                                                      'F'    [0,11]
MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_D_mass_of_leps_jets MT_of_leps_jets_mass_of_leps_jets   MT_of_leps_jets_mass_of_leps_jets                                           'F'    [0.290375322104,0.96065813303]
jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt               jets_by_pt_5_pt                                                 'F'    [25.0757904053,221.394836426]
jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex jets_by_CSV_1_btagCombinedSecVertex                                         'F'    [0.679019451141,1]
jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex jets_by_CSV_2_btagCombinedSecVertex                                         'F'    [0.0389463827014,0.999999880791]
Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq         Match_ttbar_jj_Bq_bqq                                           'F'    [-11.9318189621,2.87168049812]
Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq         Match_ttbar_jj_Bqq_bq                                           'F'    [-11.8823432922,3.19305086136]
Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq        Match_ttbar_jj_Bqq_bqq                                          'F'    [-20.1767807007,3.28406143188]
log_chiSquared_               log_chiSquared_               log_chiSquared_               log_chiSquared_                                                 'F'    [-4.06729269028,8.31077766418]
FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31      FinalBDT_ttZ_vs_ttbar_OS_Oct31                                        'F'    [-0.994243502617,0.999186873436]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "numJets_40", "MT_of_leps_jets_mass_of_leps_jets", "jets_by_pt_5_pt", "jets_by_CSV_1_btagCombinedSecVertex", "jets_by_CSV_2_btagCombinedSecVertex", "Match_ttbar_jj_Bq_bqq", "Match_ttbar_jj_Bqq_bq", "Match_ttbar_jj_Bqq_bqq", "log_chiSquared_", "FinalBDT_ttZ_vs_ttbar_OS_Oct31" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 11;
      fVmin[1] = 0.2903753221035;
      fVmax[1] = 0.960658133029938;
      fVmin[2] = 25.0757904052734;
      fVmax[2] = 221.394836425781;
      fVmin[3] = 0.679019451141357;
      fVmax[3] = 1;
      fVmin[4] = 0.0389463827013969;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -11.9318189620972;
      fVmax[5] = 2.87168049812317;
      fVmin[6] = -11.8823432922363;
      fVmax[6] = 3.19305086135864;
      fVmin[7] = -20.1767807006836;
      fVmax[7] = 3.28406143188477;
      fVmin[8] = -4.0672926902771;
      fVmax[8] = 8.31077766418457;
      fVmin[9] = -0.994243502616882;
      fVmax[9] = 0.999186873435974;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686246,0.0372493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38125,-0.02375) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.162829,-0.0674342) , 
9, -0.551425, 0, 0, 0.27484,-0.22516) , 
9, 0.33471, 0, 0, 0.492058,-0.00794251)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723348,0.0410032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436823,-0.0123405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212821,-0.0516558) , 
9, -0.379903, 0, 0, 0.328367,-0.156371) , 
9, 0.619484, 0, 0, 0.491624,-0.007117)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6702,0.0283663) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401099,-0.0113599) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.213333,-0.0490905) , 
2, 53.1537, 0, 0, 0.244917,-0.21181) , 
9, 0.144756, 0, 0, 0.498883,-0.0010225)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679839,0.0339564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466488,-0.00698442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217458,-0.0519853) , 
1, 0.633512, 0, 0, 0.35025,-0.13792) , 
5, -0.492386, 0, 0, 0.505116,0.00574161)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.770396,0.0429163) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499414,0.00126267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255091,-0.0399489) , 
5, -0.747976, 0, 0, 0.371781,-0.0992221) , 
9, 0.809336, 0, 0, 0.501135,0.00157864)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646778,0.0203393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359589,-0.0170922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186228,-0.045455) , 
9, -0.497245, 0, 0, 0.240602,-0.176258) , 
9, -0.0448331, 0, 0, 0.501726,0.00131326)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.743924,0.0331489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451356,-0.00435217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231368,-0.0378954) , 
5, -0.585916, 0, 0, 0.321756,-0.115669) , 
9, 0.619548, 0, 0, 0.503361,0.00329072)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618464,0.0184054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460159,-0.0039571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222045,-0.0474376) , 
2, 43.8122, 0, 0, 0.328014,-0.133918) , 
6, -0.982605, 0, 0, 0.496078,-0.00506342)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750988,0.0309243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45007,0.000876679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282696,-0.0299409) , 
2, 40.0887, 0, 0, 0.352493,-0.0813633) , 
9, 0.714645, 0, 0, 0.50092,0.00389896)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678363,0.0190292) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393145,-0.00751741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175362,-0.0403522) , 
9, -0.465699, 0, 0, 0.266442,-0.122554) , 
9, 0.239783, 0, 0, 0.499083,-0.00198989)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605711,0.0149703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510949,0.00723009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219686,-0.0432466) , 
2, 62.4699, 0, 0, 0.267303,-0.16126) , 
6, -1.41737, 0, 0, 0.49906,-0.00248356)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621319,0.0162037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8,0.0595791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283825,-0.0303599) , 
1, 0.861015, 0, 0, 0.30642,-0.120816) , 
6, -1.1142, 0, 0, 0.502568,0.00200798)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68574,0.0252267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514577,0.0048099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277469,-0.0313025) , 
2, 43.8192, 0, 0, 0.379962,-0.0713343) , 
7, -2.3882, 0, 0, 0.505208,0.006265)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.774648,0.0293227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410401,-0.00521728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200617,-0.0464353) , 
3, 0.863134, 0, 0, 0.371494,-0.0592874) , 
9, 0.809336, 0, 0, 0.503655,0.00403085)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654279,0.024519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629758,0.0109965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319079,-0.0242137) , 
7, -1.43527, 0, 0, 0.419175,-0.0580916) , 
2, 47.5952, 0, 0, 0.497017,-0.00140003)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.783908,0.0428137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514477,0.00302168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246964,-0.0390977) , 
0, 3.42857, 0, 0, 0.456769,-0.0269085) , 
1, 0.805473, 0, 0, 0.508991,0.00849523)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679317,0.0162239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360802,-0.00928577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185008,-0.0320666) , 
9, -0.506444, 0, 0, 0.258364,-0.0979248) , 
9, 0.145651, 0, 0, 0.508845,0.00479075)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587691,0.011476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.864407,0.0529714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279799,-0.0303274) , 
7, 0.038448, 0, 0, 0.320093,-0.107773) , 
1, 0.609558, 0, 0, 0.5026,0.00122779)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659403,0.0159912) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388711,-0.00725342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264516,-0.0410867) , 
3, 0.877722, 0, 0, 0.347578,-0.0827521) , 
5, -0.490903, 0, 0, 0.493757,-0.0100735)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765035,0.0297909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552381,0.00699198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309783,-0.0230738) , 
2, 43.7728, 0, 0, 0.414609,-0.0438365) , 
7, -1.10688, 0, 0, 0.508838,0.00317857)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.796721,0.0277935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512017,0.00472275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311252,-0.0221353) , 
2, 40.1228, 0, 0, 0.404565,-0.0418143) , 
9, 0.904303, 0, 0, 0.494193,-0.0050292)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570558,0.0080078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35412,-0.017605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20339,-0.0465416) , 
3, 0.923576, 0, 0, 0.294355,-0.124637) , 
2, 34.518, 0, 0, 0.494842,-0.00849307)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619858,0.0120238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.202505,-0.0237496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0927152,-0.0456917) , 
7, -8.15832, 0, 0, 0.17619,-0.115075) , 
9, -0.519617, 0, 0, 0.518033,0.0150793)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573075,0.00845283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532468,0.00975938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203822,-0.0391926) , 
2, 71.2081, 0, 0, 0.25,-0.135506) , 
5, -2.0471, 0, 0, 0.507913,0.00222874)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753846,0.0322184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501266,0.00290165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307692,-0.0311553) , 
3, 0.89319, 0, 0, 0.449814,-0.0263664) , 
1, 0.790038, 0, 0, 0.508982,0.00573372)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741497,0.0168379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556886,0.0164646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296024,-0.0161763) , 
1, 0.799707, 0, 0, 0.32459,-0.0532735) , 
9, 0.619546, 0, 0, 0.506109,0.00113459)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56385,0.00720419) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326087,0.0226618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.254098,-0.0350102) , 
8, 4.74273, 0, 0, 0.2603,-0.127611) , 
0, 3.38095, 0, 0, 0.503003,-0.000807139)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.731361,0.02226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6,0.0147921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338266,-0.0176658) , 
2, 55.1431, 0, 0, 0.394693,-0.0444823) , 
7, -1.60108, 0, 0, 0.501884,-0.000428814)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.719212,0.0263098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574219,0.00627167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307246,-0.0213107) , 
1, 0.673394, 0, 0, 0.440019,-0.0301113) , 
0, 5.19048, 0, 0, 0.503748,0.00230858)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644462,0.0162749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449786,-0.000334257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235683,-0.0363735) , 
3, 0.908291, 0, 0, 0.379856,-0.0494271) , 
1, 0.681324, 0, 0, 0.504932,0.00689152)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569827,0.0073481) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330827,-0.0527385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227642,-0.0187712) , 
9, 0.522922, 0, 0, 0.25498,-0.117408) , 
0, 3.14286, 0, 0, 0.510027,0.00272987)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567062,0.0058216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511628,0.00189305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179954,-0.0372916) , 
1, 0.774936, 0, 0, 0.234286,-0.120885) , 
5, -2.14596, 0, 0, 0.50276,-0.00349176)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589909,0.00642359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32069,-0.00804316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206383,-0.0382382) , 
3, 0.954375, 0, 0, 0.25,-0.10711) , 
6, -1.62983, 0, 0, 0.491422,-0.0117998)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.718913,0.0177088) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617021,0.0141955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31652,-0.0169312) , 
0, 5.28571, 0, 0, 0.381307,-0.041028) , 
7, -1.88294, 0, 0, 0.500926,-0.000802733)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650296,0.00896646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219512,-0.0170582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201031,-0.0343271) , 
4, 0.912479, 1, 0, 0.215827,-0.0809768) , 
9, -0.0449909, 0, 0, 0.491551,-0.00548781)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581055,0.00772303) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.0431017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.183486,-0.0199889) , 
9, 0.615844, 0, 0, 0.22623,-0.108459) , 
5, -1.92115, 0, 0, 0.499624,-0.000230771)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644934,0.0143209) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655602,0.0169942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344723,-0.015831) , 
1, 0.798755, 0, 0, 0.392811,-0.0425438) , 
2, 43.7728, 0, 0, 0.499072,0.000153423)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523236,0.00345215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276119,-0.0450536) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1875,0.0154773) , 
9, -0.519975, 0, 0, 0.262658,-0.159209) , 
3, 0.816583, 0, 0, 0.492045,-0.00669571)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65634,0.0116588) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409375,0.00063751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261076,-0.0260771) , 
3, 0.938861, 0, 0, 0.335692,-0.0500349) , 
5, -0.747976, 0, 0, 0.503008,0.00112763)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772196,0.015218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412214,-0.00494932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206383,-0.0263821) , 
2, 32.6759, 0, 0, 0.357865,-0.0413974) , 
9, 0.80942, 0, 0, 0.492413,-0.00896845)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619348,0.00662597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.20034,-0.011833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181818,-0.0421452) , 
6, -0.0257397, 1, 0, 0.196078,-0.0749702) , 
9, -0.329768, 0, 0, 0.497938,-0.00199626)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605894,0.00758619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188,-0.0323415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164103,-0.0105179) , 
5, -0.815249, 0, 0, 0.173438,-0.0731875) , 
9, -0.518738, 0, 0, 0.501136,0.0059286)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664013,0.0163504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.747368,0.0214491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395993,-0.0115453) , 
5, 0.89398, 0, 0, 0.446519,-0.0272191) , 
2, 53.1537, 0, 0, 0.498851,-0.00461074)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563327,0.00705516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394737,-0.0356784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219072,-0.0141266) , 
9, 0.523055, 0, 0, 0.268519,-0.0801237) , 
0, 3.33333, 0, 0, 0.503389,0.00618324)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648511,0.0114417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.793103,0.0412015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335389,-0.0142164) , 
1, 0.854258, 0, 0, 0.354982,-0.0457133) , 
7, -3.38857, 0, 0, 0.502928,0.000156386)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668309,0.0166782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487597,-0.00212809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303657,-0.0256892) , 
3, 0.908291, 0, 0, 0.430882,-0.0361237) , 
2, 53.8916, 0, 0, 0.485466,-0.0124377)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.610929,0.00823294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591398,0.0175032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227831,-0.0217461) , 
1, 0.793487, 0, 0, 0.268765,-0.0614347) , 
6, -1.41737, 0, 0, 0.504518,0.00355963)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526127,0.00435488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238636,-0.043287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127273,-0.0048154) , 
9, -0.330516, 0, 0, 0.212121,-0.139322) , 
3, 0.786013, 0, 0, 0.499635,0.00377619)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574411,0.00484968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153846,-0.0130243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.131579,-0.0419787) , 
6, -0.437574, 1, 0, 0.146751,-0.0810411) , 
9, -0.709468, 0, 0, 0.499633,0.00180255)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813505,0.0276893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507766,1.83035e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237895,-0.0217397) , 
0, 3.33333, 0, 0, 0.453032,-0.0159605) , 
8, 1.13768, 1, 0, 0.495288,-0.00249178)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586245,0.0063972) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670455,0.0211951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276569,-0.0193844) , 
5, -0.121668, 0, 0, 0.316456,-0.0569299) , 
7, -5.56798, 0, 0, 0.499445,-0.00151183)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595932,0.00880245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480565,0.00765951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27037,-0.0234104) , 
4, 0.728716, 0, 0, 0.342649,-0.0464605) , 
1, 0.602318, 0, 0, 0.517033,0.00922148)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531678,0.00466119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555556,0.0167398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246324,-0.0335717) , 
4, 0.597728, 0, 0, 0.290221,-0.100218) , 
3, 0.817501, 0, 0, 0.502827,0.00373837)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.760626,0.0230609) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504756,0.000573764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250943,-0.0212145) , 
2, 32.6182, 0, 0, 0.443942,-0.0162863) , 
1, 0.801067, 0, 0, 0.497179,0.000909345)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812102,0.0185925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424034,-0.00384817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126761,-0.0402993) , 
6, -4.20803, 0, 0, 0.40325,-0.0240522) , 
9, 0.904351, 0, 0, 0.499812,-0.00313647)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.72807,0.0253928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711078,0.0105485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380547,-0.00805693) , 
5, 0.234746, 0, 0, 0.476005,-0.0104276) , 
2, 62.5004, 0, 0, 0.508475,0.00336637)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572306,0.00681686) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375,-0.0342097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223684,-0.00964822) , 
9, 0.520057, 0, 0, 0.265267,-0.0638431) , 
0, 3.14286, 0, 0, 0.511364,0.00810264)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575646,0.00480677) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557471,0.00398632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.211604,-0.0255808) , 
6, 0.30347, 0, 0, 0.290789,-0.0641215) , 
2, 34.4603, 0, 0, 0.494166,-0.00513519)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590211,0.00512394) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35503,-0.0069339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224138,-0.0323962) , 
4, 0.370987, 0, 0, 0.301754,-0.062552) , 
7, -5.51576, 0, 0, 0.495789,-0.00743382)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801034,0.0213696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459582,-0.00180147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166667,-0.0465205) , 
3, 0.724874, 0, 0, 0.448819,-0.0127073) , 
8, 1.23759, 1, 0, 0.499813,-0.000259344)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8125,0.0223555) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521401,0.00196743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355353,-0.012324) , 
4, 0.41054, 0, 0, 0.461157,-0.0119524) , 
8, 1.00668, 1, 0, 0.500367,-0.00245486)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558576,0.00484919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434174,-0.00353126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178707,-0.0359548) , 
7, -5.43717, 0, 0, 0.325806,-0.061449) , 
3, 0.877722, 0, 0, 0.503973,-0.000576476)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594417,0.00831471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378099,-0.00356504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203125,-0.0260244) , 
4, 0.376668, 0, 0, 0.317568,-0.0382812) , 
2, 34.4243, 0, 0, 0.514609,0.0113426)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63154,0.00798486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409692,-0.00627838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1125,-0.0375649) , 
6, -3.45331, 0, 0, 0.372973,-0.0353779) , 
1, 0.673394, 0, 0, 0.505279,-0.00186419)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557962,0.00344962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.176471,0.0154296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12406,-0.0320701) , 
3, 0.924564, 1, 0, 0.136752,-0.0728281) , 
9, -0.804397, 0, 0, 0.503326,0.0019107)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.813433,0.0153529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40051,-0.020037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392749,-0.00377227) , 
4, 0.909595, 0, 0, 0.394235,-0.0267018) , 
9, 0.904252, 0, 0, 0.497608,-0.00782342)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514184,-0.000609246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314815,0.018123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145161,-0.0529477) , 
8, 4.20002, 0, 0, 0.196629,-0.107638) , 
3, 0.770728, 0, 0, 0.493373,-0.00915966)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579487,0.0083561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611765,0.0218447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192941,-0.0266154) , 
6, 0.118149, 0, 0, 0.262745,-0.0588286) , 
1, 0.545721, 0, 0, 0.518644,0.0138259)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715542,0.0217956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65643,0.00642137) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31938,-0.0108775) , 
7, -2.56389, 0, 0, 0.469983,-0.0111477) , 
2, 62.4699, 0, 0, 0.501309,0.000427307)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588018,0.00889713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691919,0.0167397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413455,-0.0084093) , 
2, 62.6471, 0, 0, 0.447385,-0.0190208) , 
3, 0.96943, 0, 0, 0.50369,0.00144968)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608803,0.00457233) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.194631,-0.0374513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181146,-0.00593676) , 
5, -0.0489856, 0, 0, 0.184058,-0.0489807) , 
9, -0.423348, 0, 0, 0.500737,0.000486036)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565094,0.00463976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371681,-0.0545831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2343,-0.00478348) , 
9, 0.710022, 0, 0, 0.263757,-0.0586227) , 
1, 0.545721, 0, 0, 0.5051,0.00209311)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555187,0.00174417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545455,0.00754719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207039,-0.0225251) , 
1, 0.802752, 0, 0, 0.247723,-0.0619927) , 
0, 3.14286, 0, 0, 0.491729,-0.00770495)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536058,0.00462061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238095,-0.0590313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.17037,-0.0234837) , 
6, -0.765976, 0, 0, 0.186441,-0.110792) , 
3, 0.770728, 0, 0, 0.512907,0.0082744)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703139,0.00735217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753425,0.0240089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349701,-0.00921424) , 
1, 0.858372, 0, 0, 0.368354,-0.0277484) , 
7, -2.17198, 0, 0, 0.506865,-0.00555204)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.816327,0.0142544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680412,0.0272403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379728,-0.00771901) , 
2, 76.4548, 0, 0, 0.39375,-0.0219641) , 
9, 0.904275, 0, 0, 0.492823,-0.00636495)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706376,0.0113905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.739003,0.0153399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373016,-0.0116305) , 
1, 0.801067, 0, 0, 0.432304,-0.0265016) , 
0, 5.2381, 0, 0, 0.49278,-0.0118466)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52345,0.0031843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137255,-0.0552252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130841,-0.0281153) , 
9, 0.323026, 0, 0, 0.132911,-0.130917) , 
6, -4.38577, 0, 0, 0.500374,0.00290192)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54718,0.00336324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530822,0.00696539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317376,-0.0213895) , 
3, 0.954378, 0, 0, 0.390187,-0.0407364) , 
4, 0.36669, 0, 0, 0.496411,-0.00512103)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57177,0.00374561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406504,-0.0228529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184127,-0.00289855) , 
9, 0.14395, 0, 0, 0.28164,-0.0441035) , 
2, 32.6237, 0, 0, 0.510373,0.00136851)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81383,0.0165578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577381,-0.0277594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431797,-0.00239171) , 
8, 1.5748, 1, 0, 0.442258,-0.015082) , 
8, 1.23759, 1, 0, 0.493736,-0.00595029)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555838,0.0037124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404175,-0.017903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1875,0.0143803) , 
9, -0.140041, 0, 0, 0.342857,-0.039454) , 
3, 0.893007, 0, 0, 0.497967,-0.00107204)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.675799,0.011307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523322,0.00136721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373147,-0.00926982) , 
4, 0.684103, 0, 0, 0.436216,-0.0168905) , 
2, 53.1712, 0, 0, 0.493455,-0.0034146)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702417,0.00550083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31746,-0.0127916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263415,0.00320788) , 
8, 3.59532, 1, 0, 0.293217,-0.0223196) , 
9, 0.429506, 0, 0, 0.494249,-0.00188578)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608395,0.00630853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222689,-0.0205666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175439,0.00333792) , 
5, -0.676914, 0, 0, 0.193093,-0.0251987) , 
9, -0.519376, 0, 0, 0.509016,0.0118053)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.82764,0.0156265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410661,-0.00280717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125,-0.0490524) , 
8, 6.71365, 1, 0, 0.405131,-0.013751) , 
9, 0.904236, 0, 0, 0.505535,0.000684569)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523064,0.000824524) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326733,-0.015073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0846154,-0.0502417) , 
1, 0.679782, 0, 0, 0.190476,-0.103678) , 
3, 0.786346, 0, 0, 0.493446,-0.00656462)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533775,0.00144411) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273038,-0.0150174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142857,-0.0461503) , 
4, 0.909011, 1, 0, 0.256716,-0.064664) , 
7, -9.00495, 0, 0, 0.498077,-0.0038733)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588448,0.00269832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409836,0.00197156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278302,-0.0166049) , 
3, 0.969584, 0, 0, 0.326347,-0.03302) , 
7, -4.90756, 0, 0, 0.489865,-0.00653)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523537,0.000580928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409836,-0.00269856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14346,-0.027353) , 
2, 57.9845, 0, 0, 0.233983,-0.0566696) , 
7, -9.00495, 0, 0, 0.484043,-0.00597349)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506757,-0.00216833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,0.0503263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27,-0.00601581) , 
6, -2.31889, 0, 0, 0.38961,0.0517066) , 
8, 5.26872, 1, 0, 0.493274,-0.000742608)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.848297,0.0234166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505783,0.000204057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218487,-0.0157432) , 
0, 3.14286, 0, 0, 0.448276,-0.00933829) , 
7, -0.00914492, 0, 0, 0.496113,-0.000206376)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512509,0.00401566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.288889,-0.0461771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245614,-0.0197387) , 
5, -1.98425, 0, 0, 0.264706,-0.122233) , 
4, 0.138488, 0, 0, 0.503285,0.00874503)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636364,0.00414585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237762,-0.0311576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200546,-0.00518721) , 
6, 0.297361, 0, 0, 0.206621,-0.0349196) , 
9, -0.23464, 0, 0, 0.497604,-0.00123155)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.727273,0.0182097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634583,0.00748198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345409,-0.00482353) , 
8, 2.74961, 1, 0, 0.489199,0.00450156) , 
2, 62.6368, 0, 0, 0.519245,0.0117211)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520048,0.000134133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.162791,-0.0530741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119565,-0.0200859) , 
9, -0.0438017, 0, 0, 0.133333,-0.10178) , 
0, 2.09524, 0, 0, 0.50019,-0.00478285)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.778524,0.0237131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496418,-0.00147315) , 
2, 75.3941, 0, 0, 0.513085,-0.000220537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135593,-0.0412183) , 
1, 0.403158, 0, 0, 0.504456,-0.00318834)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764302,0.014673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502769,0.00165749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289562,-0.013569) , 
3, 0.893173, 0, 0, 0.445696,-0.00771865) , 
1, 0.801067, 0, 0, 0.498117,0.00155514)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547983,0.00164374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483296,4.66039e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24507,-0.0276869) , 
3, 0.908291, 0, 0, 0.378109,-0.0411268) , 
4, 0.365199, 0, 0, 0.496209,-0.00863736)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524715,0.00391342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.170732,-0.0461561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141176,-0.0142577) , 
9, -0.142718, 0, 0, 0.150794,-0.0817096) , 
6, -4.46232, 0, 0, 0.50762,0.00909294)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652514,0.00490715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477717,-0.0115812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.173913,-0.000671025) , 
9, -0.518771, 0, 0, 0.394438,-0.0313942) , 
2, 47.5952, 0, 0, 0.48137,-0.0151612)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516575,0.00233689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177419,-0.0161256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0487805,-0.0607688) , 
7, -13.2555, 0, 0, 0.126214,-0.109189) , 
5, -4.88253, 0, 0, 0.501327,0.00342744)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.723626,0.00974497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.31562,-0.0131718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271408,0.00291606) , 
4, 0.644998, 0, 0, 0.292366,-0.0191763) , 
9, 0.429635, 0, 0, 0.510919,0.00718757)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567507,0.00411681) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390244,-0.0211952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153846,-0.00392329) , 
9, -0.141287, 0, 0, 0.263158,-0.0422557) , 
1, 0.545721, 0, 0, 0.508715,0.00342124)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786058,0.0155001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.794702,0.0136662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396101,-0.0051768) , 
7, -0.16463, 0, 0, 0.449578,-0.0101395) , 
1, 0.805473, 0, 0, 0.502062,-0.00102859)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691803,0.0114265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505799,0.00191633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.236686,-0.0141371) , 
7, -6.5368, 0, 0, 0.439534,-0.00584729) , 
0, 5.2381, 0, 0, 0.49719,0.00407977)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591848,0.00514156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343558,0.00245717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294574,-0.0161008) , 
8, 4.55942, 0, 0, 0.321918,-0.0182349) , 
7, -5.46681, 0, 0, 0.503187,0.00575061)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683007,0.0112299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497622,-0.000110346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219444,-0.0209572) , 
2, 30.4514, 0, 0, 0.44858,-0.0115754) , 
2, 53.1537, 0, 0, 0.502638,-0.00016056)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589546,0.00495043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535836,0.00597684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344944,-0.012479) , 
3, 0.954217, 0, 0, 0.420732,-0.0164178) , 
4, 0.684106, 0, 0, 0.495271,-0.00194709)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564993,0.00617647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430939,-0.0230003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.208451,0.00510124) , 
9, 0.427547, 0, 0, 0.283582,-0.0200047) , 
1, 0.545721, 0, 0, 0.508436,0.0129625)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710606,0.0046377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3903,-0.015537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244589,0.000299667) , 
6, -0.367308, 0, 0, 0.291083,-0.0196928) , 
9, 0.429728, 0, 0, 0.497945,-0.00250902)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51643,0.000915046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333333,-0.041883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189189,-0.00664435) , 
9, 0.901784, 0, 0, 0.220339,-0.0514086) , 
3, 0.786013, 0, 0, 0.490559,-0.00166027)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530405,-0.00683986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709273,0.0145155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426087,0.000207286) , 
0, 5.28571, 0, 0, 0.489601,0.0111888) , 
3, 0.984715, 0, 0, 0.503187,-0.000145753)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553736,0.00106451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.135802,-0.0101252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0615385,-0.0530598) , 
2, 47.5952, 1, 0, 0.12013,-0.060252) , 
9, -0.804396, 0, 0, 0.504089,-0.00364004)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513369,0.00251678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463415,0.00555464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203704,-0.0423665) , 
3, 0.940511, 0, 0, 0.315789,-0.0815344) , 
4, 0.138488, 0, 0, 0.50645,0.00529557)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.752252,0.0154006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61848,0.00281881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304193,-0.00811149) , 
7, -3.57598, 0, 0, 0.475436,-0.00681382) , 
2, 70.1415, 0, 0, 0.498324,-0.00231108)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680603,0.00329916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.26699,-0.0170198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24774,0.00544213) , 
4, 0.600632, 0, 0, 0.257899,-0.0257314) , 
9, 0.239909, 0, 0, 0.492395,-0.00532127)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587617,0.00421051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376812,0.00825488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279279,-0.0188145) , 
8, 5.09466, 0, 0, 0.316667,-0.0257126) , 
7, -5.49782, 0, 0, 0.497601,0.000918764)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.855072,0.0239165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762963,0.00959781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43047,-0.0037467) , 
5, 0.756895, 0, 0, 0.484076,-0.00621811) , 
1, 0.867741, 0, 0, 0.503396,-0.00256856)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520056,-0.00177225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518072,0.0286542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253589,-0.00817634) , 
6, -2.82033, 0, 0, 0.39738,0.0409798) , 
8, 4.68522, 1, 0, 0.498463,0.00236116)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539033,-0.0170673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629339,0.012564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433646,-0.00400861) , 
4, 0.692721, 0, 0, 0.506918,0.00676631) , 
4, 0.954232, 0, 0, 0.510173,0.000520585)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862069,0.0373658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513389,0.000500446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20354,-0.0184433) , 
3, 0.786013, 0, 0, 0.486621,-0.00311582) , 
1, 0.896822, 0, 0, 0.494764,-0.000689818)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546744,0.00183168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647887,0.0272524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332382,-0.0132274) , 
4, 0.777474, 0, 0, 0.361399,-0.0303466) , 
3, 0.908291, 0, 0, 0.493274,-0.00436489)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53159,0.00429134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183673,-0.0464738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126437,-0.014402) , 
9, -0.0473248, 0, 0, 0.147059,-0.0878116) , 
0, 2.38095, 0, 0, 0.511637,0.00898916)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775229,0.0129954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469154,-0.000324491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158333,-0.0215842) , 
3, 0.755824, 0, 0, 0.452284,-0.00423004) , 
1, 0.801067, 0, 0, 0.505478,0.00298105)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559259,0.00171682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40411,-0.0321487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204082,-5.87044e-05) , 
9, 0.617119, 0, 0, 0.258364,-0.0333727) , 
1, 0.545721, 0, 0, 0.499259,-0.0020853)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572005,-0.00331157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518987,0.0260869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352708,0.00268979) , 
7, -5.46293, 0, 0, 0.392354,0.0278954) , 
8, 3.51822, 1, 0, 0.506593,0.0031682)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577348,-0.00549843) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582969,0.000595566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246753,0.016575) , 
9, -0.234443, 0, 0, 0.488238,0.0145663) , 
4, 0.862707, 0, 0, 0.512704,0.00581726)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514122,0.00182559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215686,-5.36608e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.138462,-0.0360872) , 
8, 5.72253, 1, 0, 0.172414,-0.0679565) , 
6, -4.75022, 0, 0, 0.499635,0.00292682)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659832,0.00658335) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555556,-0.0132965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301942,0.00155326) , 
5, -0.0698226, 0, 0, 0.391985,-0.0138374) , 
2, 44.3342, 0, 0, 0.499625,0.000471557)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525397,0.00289372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195122,-0.0440219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.161765,-8.2333e-05) , 
9, -0.144272, 0, 0, 0.174312,-0.0628625) , 
6, -4.90569, 0, 0, 0.511161,0.00657847)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662791,0.00449718) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229358,0.00729696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221774,-0.0219514) , 
4, 0.593177, 1, 0, 0.225322,-0.032751) , 
9, -0.0443797, 0, 0, 0.50905,-0.00182431)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529961,0.00379043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3,0.00432967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0877193,-0.0530097) , 
4, 0.551232, 0, 0, 0.196581,-0.0655018) , 
1, 0.433027, 0, 0, 0.515445,0.00911347)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527184,-0.000343954) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434125,-0.0170382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198529,0.0153024) , 
9, -0.32515, 0, 0, 0.380634,-0.0385261) , 
4, 0.276218, 0, 0, 0.494171,-0.00954416)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510908,-0.00114928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169811,-0.0114876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125,-0.0436219) , 
4, 0.788613, 1, 0, 0.157534,-0.0640928) , 
0, 2.09524, 0, 0, 0.491564,-0.00713351)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850649,0.0254305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569645,0.00196333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40836,-0.00749075) , 
4, 0.728582, 0, 0, 0.473035,-0.0125128) , 
1, 0.86121, 0, 0, 0.494182,-0.00780559)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634561,-0.00424099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632653,-0.0104361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368266,0.0056466) , 
8, 1.5284, 1, 0, 0.40875,0.010404) , 
1, 0.712361, 0, 0, 0.498684,0.00061834)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526669,0.00196031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.269663,-0.00282768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0921053,-0.0475235) , 
4, 0.438604, 0, 0, 0.187879,-0.0630384) , 
1, 0.449966, 0, 0, 0.505935,0.00224657)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578994,0.00502872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.168394,-0.000881964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.141176,-0.0327982) , 
1, 0.702782, 1, 0, 0.163482,-0.0228124) , 
9, -0.709474, 0, 0, 0.50749,0.0100194)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753769,0.0199884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.854077,0.0167386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.435966,-0.00545443) , 
7, 0.268076, 0, 0, 0.475344,-0.0128446) , 
2, 71.8184, 0, 0, 0.496072,-0.00746615)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.805046,0.0126683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.445825,-0.00365523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356098,0.0120654) , 
8, 5.69185, 1, 0, 0.437528,-0.00769213) , 
7, -0.364917, 0, 0, 0.497927,-0.000685968)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591373,0.00520387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358491,-0.000764325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227758,-0.023398) , 
4, 0.319858, 0, 0, 0.315972,-0.0254142) , 
7, -5.72356, 0, 0, 0.500762,0.0030482)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677049,0.00690402) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440538,-0.00757912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329545,0.0232793) , 
8, 5.88138, 1, 0, 0.435707,-0.0210436) , 
2, 53.1586, 0, 0, 0.491641,-0.0110828)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519371,0.00162038) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463415,0.00392434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.153846,-0.0431512) , 
3, 0.939921, 0, 0, 0.273585,-0.0807968) , 
4, 0.138488, 0, 0, 0.509768,0.00195883)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580522,0.000855338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44519,-0.000981087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188341,-0.0183187) , 
1, 0.620606, 0, 0, 0.316909,-0.0276845) , 
7, -5.4456, 0, 0, 0.494324,-0.00716285)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.874016,0.0252087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534653,-0.0114154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470704,-0.00010592) , 
4, 0.908471, 0, 0, 0.483438,-0.0074769) , 
1, 0.867547, 0, 0, 0.502065,-0.00404884)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.665406,-0.00715252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385687,0.00295854) , 
5, -0.227554, 0, 0, 0.497914,-0.0032649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,0.0423672) , 
5, -6.50874, 0, 0, 0.495345,-0.000964152)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524564,0.00194196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.253425,-0.0049459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12766,-0.0476504) , 
8, 6.23404, 1, 0, 0.222798,-0.0521687) , 
7, -10.1707, 0, 0, 0.502636,0.00209184)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713128,0.00782562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80315,0.0175626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408619,-0.0054188) , 
1, 0.858372, 0, 0, 0.433025,-0.0137395) , 
0, 5.14286, 0, 0, 0.497753,-0.00500215)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88601,0.0208196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599589,-0.0068058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383543,0.00193922) , 
1, 0.705312, 0, 0, 0.46836,-0.00525131) , 
7, 0.584293, 0, 0, 0.498504,-0.00148002)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522873,-0.00400928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469388,0.0420303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28841,0.000336561) , 
2, 30.5954, 0, 0, 0.326226,0.0270548) , 
2, 31.5178, 0, 0, 0.488136,-0.00621605)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695,-0.0150365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483916,0.00293234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157895,-0.027038) , 
6, -4.4721, 0, 0, 0.464881,0.00469876) , 
6, 0.741427, 0, 0, 0.499253,-0.00228437)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707641,0.00862445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552116,-0.00490448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253468,0.00834179) , 
9, 0.0504531, 0, 0, 0.417707,0.00166364) , 
8, 2.20152, 1, 0, 0.515947,0.0103538)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.802667,0.00844051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578313,-0.0254768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438024,-0.00203689) , 
8, 1.57494, 1, 0, 0.448097,-0.01242) , 
8, 1.23759, 1, 0, 0.497581,-0.00753329)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537572,-0.0097472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.88189,0.0311835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467245,0.000771441) , 
5, 1.17047, 0, 0, 0.491148,0.00725701) , 
4, 0.909589, 0, 0, 0.5,9.19465e-06)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649072,0.00219651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.273616,-0.0227211) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197605,0.000204851) , 
1, 0.691867, 0, 0, 0.221538,-0.0283016) , 
9, -0.0449909, 0, 0, 0.494628,-0.00563629)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592954,0.00431025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448441,-0.0100909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197248,0.00225949) , 
9, 0.0497699, 0, 0, 0.320047,-0.0149863) , 
7, -5.72356, 0, 0, 0.506672,0.00495656)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505982,0.00149251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243902,-0.000715717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195122,-0.0496364) , 
3, 0.939985, 1, 0, 0.219512,-0.0867672) , 
8, 6.34265, 1, 0, 0.497194,0.00202257)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585533,0.00436634) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496644,-0.00271899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192201,-0.01837) , 
1, 0.539728, 0, 0, 0.432353,-0.0183095) , 
4, 0.771178, 0, 0, 0.489901,-0.00612979)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535514,-0.00129249) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498305,0.0227311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243346,-0.00549355) , 
6, -2.74411, 0, 0, 0.378136,0.033006) , 
8, 4.5033, 1, 0, 0.502965,0.00351879)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56882,0.00235768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303644,-0.0186622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16263,0.00353822) , 
9, -0.0471331, 0, 0, 0.227612,-0.0252992) , 
6, -2.10574, 0, 0, 0.500374,0.00114675)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683109,-0.0110585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437109,0.00464354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343023,-0.022327) , 
4, 0.954657, 1, 0, 0.42872,0.00711326) , 
8, 1.82703, 1, 0, 0.494226,-0.00323762)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645894,0.00225837) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274336,-0.0238449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.205298,-0.00111963) , 
5, -0.117353, 0, 0, 0.221203,-0.0253885) , 
9, -0.0438204, 0, 0, 0.491475,-0.00446705)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6716,-0.00393783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396177,0.00729317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139535,-0.0321291) , 
6, -6.62221, 0, 0, 0.389103,0.0204936) , 
7, -2.3882, 0, 0, 0.504733,0.00699964)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530488,-0.00797278) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57201,0.00700225) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392461,-0.0018676) , 
3, 0.923576, 0, 0, 0.496011,0.0111527) , 
4, 0.909524, 0, 0, 0.502478,0.00429845)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557621,0.00281091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38961,-0.0292178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209845,0.00160916) , 
9, 0.522225, 0, 0, 0.261111,-0.0282677) , 
0, 3.28571, 0, 0, 0.498143,0.00170196)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525896,0.00267511) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205882,-0.000204136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0746269,-0.0449641) , 
8, 5.85853, 1, 0, 0.153846,-0.0521819) , 
5, -3.85349, 0, 0, 0.502426,0.00499098)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506584,-0.000684029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611111,0.0332574) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231579,-0.00396207) , 
1, 0.648851, 0, 0, 0.447964,0.0644175) , 
4, 0.183831, 0, 0, 0.501697,0.00334795)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577347,0.00384683) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.427083,-0.0146221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195187,0.0091818) , 
9, 0.049034, 0, 0, 0.312665,-0.0152892) , 
2, 34.4603, 0, 0, 0.502064,0.00466599)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724515,0.00811493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421563,-0.00190288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265,-0.025219) , 
4, 0.185746, 0, 0, 0.404646,-0.0144435) , 
8, 2.05012, 1, 0, 0.503178,-0.00239157)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621958,0.00152852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23053,0.0138977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188324,-0.0202517) , 
4, 0.457564, 1, 0, 0.204225,-0.028272) , 
9, -0.234841, 0, 0, 0.490189,-0.00542252)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.74,0.013159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418994,-0.0156642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418038,-0.00221616) , 
4, 0.863969, 0, 0, 0.418209,-0.0152904) , 
6, 0.321547, 0, 0, 0.501667,-0.00104162)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608408,-0.00226714) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339602,0.0119742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26087,-0.0268021) , 
4, 0.130471, 0, 0, 0.334018,0.0278266) , 
5, -1.1652, 0, 0, 0.507202,0.0055616)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516517,-0.000511454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75,0.0592894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290566,0.00102674) , 
6, -1.12656, 0, 0, 0.370717,0.038074) , 
8, 5.26872, 1, 0, 0.498869,0.00316482)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606957,0.00931556) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487741,-0.00802742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194444,0.00978188) , 
9, -0.424118, 0, 0, 0.417443,-0.0158086) , 
4, 0.683346, 0, 0, 0.499623,0.00381304)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507989,-0.00200085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587302,0.0437733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175676,-0.0103893) , 
6, -3.39536, 0, 0, 0.364964,0.0565796) , 
8, 5.95305, 1, 0, 0.500388,-0.0031361)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582929,0.00360084) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450722,-0.00352659) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195652,-0.0327579) , 
8, 5.95305, 1, 0, 0.436795,-0.0167664) , 
4, 0.77507, 0, 0, 0.492268,-0.00611622)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552463,-0.00816091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595238,0.0113883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445118,0.000203181) , 
3, 0.969584, 0, 0, 0.491887,0.0121623) , 
4, 0.908468, 0, 0, 0.502668,0.00550401)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505464,-0.000753199) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431373,0.0698054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196721,-0.00191372) , 
8, 5.87314, 1, 0, 0.303571,0.0884366) , 
7, -11.5174, 0, 0, 0.497008,0.00135769)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569385,0.00338693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563707,-0.0173442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.288646,0.00111704) , 
9, 0.619416, 0, 0, 0.402722,-0.0217414) , 
3, 0.954146, 0, 0, 0.490744,-0.00448769)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.827532,0.0147707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588608,-0.0227976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397035,0.00112224) , 
1, 0.826817, 0, 0, 0.412329,-0.0029947) , 
9, 0.904315, 0, 0, 0.51283,0.0072526)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725373,0.0113085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532189,-0.0101155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394224,0.00108477) , 
1, 0.700462, 0, 0, 0.42711,-0.00567597) , 
1, 0.769149, 0, 0, 0.503238,0.00462431)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.80916,0.018706) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646081,-0.00933201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380865,-0.000149742) , 
5, -0.079075, 0, 0, 0.470801,-0.0103976) , 
0, 6.42857, 0, 0, 0.487758,-0.00733289)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51761,0.00235238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2,-0.00171418) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0425532,-0.053662) , 
8, 6.05937, 1, 0, 0.127451,-0.0733654) , 
6, -4.98362, 0, 0, 0.502472,0.00442082)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573421,0.0032138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424363,-0.00529527) , 
3, 0.954217, 0, 0, 0.50191,-0.00283968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326923,0.0348688) , 
5, -6.58927, 0, 0, 0.498502,-0.000788695)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567366,0.00503078) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428571,-0.0296728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.204819,-0.00729382) , 
9, 0.711951, 0, 0, 0.252372,-0.0382624) , 
1, 0.545721, 0, 0, 0.50524,0.00598965)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621359,-0.020766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53606,0.0042532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232092,-0.0128457) , 
2, 30.4174, 0, 0, 0.495616,0.00704028) , 
2, 81.1669, 0, 0, 0.500367,0.00453542)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529749,-0.00188783) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471264,-0.000209121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267281,0.0341134) , 
9, 0.622158, 0, 0, 0.358056,0.0457746) , 
3, 0.847152, 0, 0, 0.504511,0.00145043)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568008,0.00322165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293269,-0.00642284) , 
7, -6.59556, 0, 0, 0.501739,0.00322948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392857,0.0323039) , 
8, 6.54248, 1, 0, 0.499432,0.00522054)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51185,-0.00239646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5,0.0478905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25,-0.0157382) , 
4, 0.595098, 0, 0, 0.377049,0.0564611) , 
8, 6.03516, 1, 0, 0.505844,-0.00484583)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643543,-0.00524174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48412,0.00761649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329289,-0.00301833) , 
4, 0.365197, 0, 0, 0.432836,0.0136265) , 
1, 0.731835, 0, 0, 0.506532,0.00307269)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59433,0.00357716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448529,-0.0204996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431246,-0.0026575) , 
4, 0.600225, 0, 0, 0.434076,-0.0187296) , 
4, 0.773277, 0, 0, 0.495156,-0.00737797)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55872,0.00207779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137457,-0.0105004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0434783,-0.0515516) , 
4, 0.956738, 1, 0, 0.124629,-0.0444441) , 
9, -0.802692, 0, 0, 0.502864,0.000280625)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584081,0.000708299) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332903,-0.0124429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168224,0.0324115) , 
0, 3.28571, 0, 0, 0.312925,-0.029391) , 
7, -5.71669, 0, 0, 0.494374,-0.00819782)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682115,0.00443415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34,0.0433484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25575,-0.00808665) , 
8, 6.30693, 0, 0, 0.259455,-0.020097) , 
9, 0.240119, 0, 0, 0.502061,-0.000504415)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61828,-0.00599998) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4456,0.00437874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.22884,-0.00963894) , 
7, -7.94713, 0, 0, 0.40153,0.00578178) , 
1, 0.703434, 0, 0, 0.49162,-0.00468251)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553874,0.00152637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285714,0.0116584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189711,-0.0200017) , 
7, -11.4753, 1, 0, 0.211443,-0.0359521) , 
6, -2.54996, 0, 0, 0.501888,-0.00125595)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531915,0.00116635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229008,-0.00876268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.12766,-0.0644725) , 
2, 56.1345, 1, 0, 0.213592,-0.0545121) , 
1, 0.495102, 0, 0, 0.495565,-0.00290329)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531357,-0.000369547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537688,0.0288503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.248677,-0.00207684) , 
1, 0.601478, 0, 0, 0.396907,0.0469296) , 
8, 5.05099, 1, 0, 0.51215,0.00569641)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8144,0.00804211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589333,-0.0162208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351205,-0.00300849) , 
9, 0.72261, 0, 0, 0.395086,-0.0184699) , 
9, 0.903919, 0, 0, 0.493609,-0.00927201)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
